-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			AUTORIZACIONES
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			ALEX DE LA ROSA // HECTOR A. GONZALEZ 
-- // Fecha creación:	15/OCT/2018
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0]
GO

-- //////////////////////////////////////////////////////////////




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE --->  LISTADO
-- //////////////////////////////////////////////////////////////

-- EXECUTE [PG_LI_AUTORIZACION] 0,0,0, '', -1,-1,-1,-1
	

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_AUTORIZACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_AUTORIZACION]
GO	


CREATE PROCEDURE [dbo].[PG_LI_AUTORIZACION]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_D_AUTORIZACION				VARCHAR(100),
	-- ===========================
	@PP_K_ESTATUS_AUTORIZACION		INT,
	@PP_K_TIPO_AUTORIZACION			INT,
	@PP_K_MODO_AUTORIZACION			INT,
	@PP_K_ROL_AUTORIZACION			INT
AS			

	DECLARE @VP_MENSAJE		VARCHAR(300)	= ''
	
	-- ///////////////////////////////////////////

	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_DATA_ACCESO_SELECT]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
													8, -- @PP_K_DATA_SISTEMA,	
													@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	-- ///////////////////////////////////////////

	DECLARE @VP_LI_N_REGISTROS		INT
	
	SET @VP_LI_N_REGISTROS = 1000
	
	EXECUTE [dbo].[PG_SK_CONFIGURACION_LI_N_REGISTROS_GET]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE,
															1, -- WIWI // @VP_L_APLICAR_MAX_ROWS,
															@OU_LI_N_REGISTROS = @VP_LI_N_REGISTROS		OUTPUT																
	-- =========================================	
	
	DECLARE @VP_K_FOLIO		INT

	EXECUTE [dbo].[PG_RN_OBTENER_ID_X_REFERENCIA]	@PP_D_AUTORIZACION, 
													@OU_K_ELEMENTO = @VP_K_FOLIO	OUTPUT
	-- =========================================
	
	IF NOT (@VP_MENSAJE='')
		SET @VP_LI_N_REGISTROS = 0

	-- ///////////////////////////////////////////

	SELECT	TOP ( @VP_LI_N_REGISTROS )		
			AUTORIZACION.*,
			D_USUARIO AS D_USUARIO_CAMBIO,
			D_ESTATUS_AUTORIZACION, D_TIPO_AUTORIZACION, 
			S_ESTATUS_AUTORIZACION, S_TIPO_AUTORIZACION, 
			-- ===================================			
			MAU1.D_MODO_AUTORIZACION AS MAU1_D_MODO_AUTORIZACION, MAU2.D_MODO_AUTORIZACION AS MAU2_D_MODO_AUTORIZACION, MAU3.D_MODO_AUTORIZACION AS MAU3_D_MODO_AUTORIZACION, MAU4.D_MODO_AUTORIZACION AS MAU4_D_MODO_AUTORIZACION, MAU5.D_MODO_AUTORIZACION AS MAU5_D_MODO_AUTORIZACION,
			MAU1.S_MODO_AUTORIZACION AS MAU1_S_MODO_AUTORIZACION, MAU2.S_MODO_AUTORIZACION AS MAU2_S_MODO_AUTORIZACION, MAU3.S_MODO_AUTORIZACION AS MAU3_S_MODO_AUTORIZACION, MAU4.S_MODO_AUTORIZACION AS MAU4_S_MODO_AUTORIZACION, MAU5.S_MODO_AUTORIZACION AS MAU5_S_MODO_AUTORIZACION,
			-- ===================================			
			ROL1A.D_ROL_AUTORIZACION AS ROL1A_D_ROL_AUTORIZACION, 
			ROL2A.D_ROL_AUTORIZACION AS ROL2A_D_ROL_AUTORIZACION, 
			ROL3A.D_ROL_AUTORIZACION AS ROL3A_D_ROL_AUTORIZACION, 
			ROL4A.D_ROL_AUTORIZACION AS ROL4A_D_ROL_AUTORIZACION, 
			ROL5A.D_ROL_AUTORIZACION AS ROL5A_D_ROL_AUTORIZACION,
			-- ===================================			
			ROL1B.D_ROL_AUTORIZACION AS ROL1B_D_ROL_AUTORIZACION, 
			ROL2B.D_ROL_AUTORIZACION AS ROL2B_D_ROL_AUTORIZACION, 
			ROL3B.D_ROL_AUTORIZACION AS ROL3B_D_ROL_AUTORIZACION, 
			ROL4B.D_ROL_AUTORIZACION AS ROL4B_D_ROL_AUTORIZACION, 
			ROL5B.D_ROL_AUTORIZACION AS ROL5B_D_ROL_AUTORIZACION,
			-- ===================================			
			ROL1C.D_ROL_AUTORIZACION AS ROL1C_D_ROL_AUTORIZACION, 
			ROL2C.D_ROL_AUTORIZACION AS ROL2C_D_ROL_AUTORIZACION, 
			ROL3C.D_ROL_AUTORIZACION AS ROL3C_D_ROL_AUTORIZACION, 
			ROL4C.D_ROL_AUTORIZACION AS ROL4C_D_ROL_AUTORIZACION, 
			ROL5C.D_ROL_AUTORIZACION AS ROL5C_D_ROL_AUTORIZACION
			-- ===================================			
	FROM	AUTORIZACION, USUARIO,
			ESTATUS_AUTORIZACION, TIPO_AUTORIZACION,
			-- ===================================			
			MODO_AUTORIZACION AS MAU1, MODO_AUTORIZACION AS MAU2, MODO_AUTORIZACION AS MAU3, MODO_AUTORIZACION AS MAU4, MODO_AUTORIZACION AS MAU5, 
			ROL_AUTORIZACION AS ROL1A, ROL_AUTORIZACION AS ROL1B, ROL_AUTORIZACION AS ROL1C,
			ROL_AUTORIZACION AS ROL2A, ROL_AUTORIZACION AS ROL2B, ROL_AUTORIZACION AS ROL2C,
			ROL_AUTORIZACION AS ROL3A, ROL_AUTORIZACION AS ROL3B, ROL_AUTORIZACION AS ROL3C,
			ROL_AUTORIZACION AS ROL4A, ROL_AUTORIZACION AS ROL4B, ROL_AUTORIZACION AS ROL4C,
			ROL_AUTORIZACION AS ROL5A, ROL_AUTORIZACION AS ROL5B, ROL_AUTORIZACION AS ROL5C
			-- ===================================
	WHERE	AUTORIZACION.K_ESTATUS_AUTORIZACION=ESTATUS_AUTORIZACION.K_ESTATUS_AUTORIZACION
	AND		AUTORIZACION.K_TIPO_AUTORIZACION=TIPO_AUTORIZACION.K_TIPO_AUTORIZACION
			-- ===================================
	AND		AUTORIZACION.K_MODO_AUTORIZACION_P1=MAU1.K_MODO_AUTORIZACION
	AND		AUTORIZACION.K_MODO_AUTORIZACION_P2=MAU2.K_MODO_AUTORIZACION
	AND		AUTORIZACION.K_MODO_AUTORIZACION_P3=MAU3.K_MODO_AUTORIZACION
	AND		AUTORIZACION.K_MODO_AUTORIZACION_P4=MAU4.K_MODO_AUTORIZACION
	AND		AUTORIZACION.K_MODO_AUTORIZACION_P5=MAU5.K_MODO_AUTORIZACION
			-- ===================================
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P1A=ROL1A.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P2A=ROL2A.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P3A=ROL3A.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P4A=ROL4A.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P5A=ROL5A.K_ROL_AUTORIZACION
			-- ===================================
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P1B=ROL1B.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P2B=ROL2B.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P3B=ROL3B.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P4B=ROL4B.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P5B=ROL5B.K_ROL_AUTORIZACION
			-- ===================================
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P1C=ROL1C.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P2C=ROL2C.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P3C=ROL3C.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P4C=ROL4C.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P5C=ROL5C.K_ROL_AUTORIZACION
			-- ===================================
	AND		(	
				K_AUTORIZACION=@VP_K_FOLIO
			OR	D_AUTORIZACION			LIKE '%'+@PP_D_AUTORIZACION+'%' 	
			OR	S_AUTORIZACION			LIKE '%'+@PP_D_AUTORIZACION+'%' 
			OR	C_AUTORIZACION			LIKE '%'+@PP_D_AUTORIZACION+'%' 
	--		OR 	LIMITE_INFERIOR			LIKE '%'+@PP_D_AUTORIZACION+'%'
	--		OR 	LIMITE_SUPERIOR			LIKE '%'+@PP_D_AUTORIZACION+'%'
			)			
			-- =====================
	AND		( @PP_K_ESTATUS_AUTORIZACION=-1		OR	AUTORIZACION.K_ESTATUS_AUTORIZACION=@PP_K_ESTATUS_AUTORIZACION )
	AND		( @PP_K_TIPO_AUTORIZACION=-1		OR	AUTORIZACION.K_TIPO_AUTORIZACION=@PP_K_TIPO_AUTORIZACION )
			-- =====================
	AND		( @PP_K_MODO_AUTORIZACION=-1		OR	AUTORIZACION.K_MODO_AUTORIZACION_P1=@PP_K_MODO_AUTORIZACION
												OR	AUTORIZACION.K_MODO_AUTORIZACION_P2=@PP_K_MODO_AUTORIZACION 
												OR	AUTORIZACION.K_MODO_AUTORIZACION_P3=@PP_K_MODO_AUTORIZACION
												OR	AUTORIZACION.K_MODO_AUTORIZACION_P4=@PP_K_MODO_AUTORIZACION
												OR	AUTORIZACION.K_MODO_AUTORIZACION_P5=@PP_K_MODO_AUTORIZACION		)

	AND		( @PP_K_ROL_AUTORIZACION=-1			
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P1A=@PP_K_ROL_AUTORIZACION
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P2A=@PP_K_ROL_AUTORIZACION
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P3A=@PP_K_ROL_AUTORIZACION
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P4A=@PP_K_ROL_AUTORIZACION
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P5A=@PP_K_ROL_AUTORIZACION

			OR	AUTORIZACION.K_ROL_AUTORIZACION_P1B=@PP_K_ROL_AUTORIZACION
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P2B=@PP_K_ROL_AUTORIZACION
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P3B=@PP_K_ROL_AUTORIZACION
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P4B=@PP_K_ROL_AUTORIZACION
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P5B=@PP_K_ROL_AUTORIZACION

			OR	AUTORIZACION.K_ROL_AUTORIZACION_P1C=@PP_K_ROL_AUTORIZACION
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P2C=@PP_K_ROL_AUTORIZACION
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P3C=@PP_K_ROL_AUTORIZACION
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P4C=@PP_K_ROL_AUTORIZACION
			OR	AUTORIZACION.K_ROL_AUTORIZACION_P5C=@PP_K_ROL_AUTORIZACION

			)
			-- =====================
	AND		AUTORIZACION.K_USUARIO_CAMBIO=USUARIO.K_USUARIO
	AND		AUTORIZACION.L_BORRADO=0
			-- =====================
	ORDER BY K_AUTORIZACION DESC

	-- //////////////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SEEK 
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_AUTORIZACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_AUTORIZACION]
GO	

CREATE PROCEDURE [dbo].[PG_SK_AUTORIZACION]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_K_AUTORIZACION			INT
AS			

	DECLARE @VP_MENSAJE		VARCHAR(300)	= ''
	
	-- ///////////////////////////////////////////

	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_DATA_ACCESO_SELECT]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
													8, -- @PP_K_DATA_SISTEMA,	
													@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	-- ///////////////////////////////////////////

	DECLARE @VP_LI_N_REGISTROS	INT = 1000
	
	IF NOT (@VP_MENSAJE='')
		SET @VP_LI_N_REGISTROS = 0

	-- ///////////////////////////////////////////
	
	SELECT	TOP ( @VP_LI_N_REGISTROS )		
			AUTORIZACION.*,
			D_USUARIO AS D_USUARIO_CAMBIO,
			D_ESTATUS_AUTORIZACION, D_TIPO_AUTORIZACION, 
			S_ESTATUS_AUTORIZACION, S_TIPO_AUTORIZACION, 
			-- ===================================			
			MAU1.D_MODO_AUTORIZACION AS MAU1_D_MODO_AUTORIZACION, MAU2.D_MODO_AUTORIZACION AS MAU2_D_MODO_AUTORIZACION, MAU3.D_MODO_AUTORIZACION AS MAU3_D_MODO_AUTORIZACION, MAU4.D_MODO_AUTORIZACION AS MAU4_D_MODO_AUTORIZACION, MAU5.D_MODO_AUTORIZACION AS MAU5_D_MODO_AUTORIZACION,
			-- ===================================			
			ROL1A.D_ROL_AUTORIZACION AS ROL1A_D_ROL_AUTORIZACION, 
			ROL2A.D_ROL_AUTORIZACION AS ROL2A_D_ROL_AUTORIZACION, 
			ROL3A.D_ROL_AUTORIZACION AS ROL3A_D_ROL_AUTORIZACION, 
			ROL4A.D_ROL_AUTORIZACION AS ROL4A_D_ROL_AUTORIZACION, 
			ROL5A.D_ROL_AUTORIZACION AS ROL5A_D_ROL_AUTORIZACION,
			-- ===================================			
			ROL1B.D_ROL_AUTORIZACION AS ROL1B_D_ROL_AUTORIZACION, 
			ROL2B.D_ROL_AUTORIZACION AS ROL2B_D_ROL_AUTORIZACION, 
			ROL3B.D_ROL_AUTORIZACION AS ROL3B_D_ROL_AUTORIZACION, 
			ROL4B.D_ROL_AUTORIZACION AS ROL4B_D_ROL_AUTORIZACION, 
			ROL5B.D_ROL_AUTORIZACION AS ROL5B_D_ROL_AUTORIZACION,
			-- ===================================			
			ROL1C.D_ROL_AUTORIZACION AS ROL1C_D_ROL_AUTORIZACION, 
			ROL2C.D_ROL_AUTORIZACION AS ROL2C_D_ROL_AUTORIZACION, 
			ROL3C.D_ROL_AUTORIZACION AS ROL3C_D_ROL_AUTORIZACION, 
			ROL4C.D_ROL_AUTORIZACION AS ROL4C_D_ROL_AUTORIZACION, 
			ROL5C.D_ROL_AUTORIZACION AS ROL5C_D_ROL_AUTORIZACION
			-- ===================================			
	FROM	AUTORIZACION, USUARIO,
			ESTATUS_AUTORIZACION, TIPO_AUTORIZACION,
			-- ===================================			
			MODO_AUTORIZACION AS MAU1, MODO_AUTORIZACION AS MAU2, MODO_AUTORIZACION AS MAU3, MODO_AUTORIZACION AS MAU4, MODO_AUTORIZACION AS MAU5, 
			ROL_AUTORIZACION AS ROL1A, ROL_AUTORIZACION AS ROL1B, ROL_AUTORIZACION AS ROL1C,
			ROL_AUTORIZACION AS ROL2A, ROL_AUTORIZACION AS ROL2B, ROL_AUTORIZACION AS ROL2C,
			ROL_AUTORIZACION AS ROL3A, ROL_AUTORIZACION AS ROL3B, ROL_AUTORIZACION AS ROL3C,
			ROL_AUTORIZACION AS ROL4A, ROL_AUTORIZACION AS ROL4B, ROL_AUTORIZACION AS ROL4C,
			ROL_AUTORIZACION AS ROL5A, ROL_AUTORIZACION AS ROL5B, ROL_AUTORIZACION AS ROL5C
			-- ===================================
	WHERE	AUTORIZACION.K_ESTATUS_AUTORIZACION=ESTATUS_AUTORIZACION.K_ESTATUS_AUTORIZACION
	AND		AUTORIZACION.K_TIPO_AUTORIZACION=TIPO_AUTORIZACION.K_TIPO_AUTORIZACION
			-- ===================================
	AND		AUTORIZACION.K_MODO_AUTORIZACION_P1=MAU1.K_MODO_AUTORIZACION
	AND		AUTORIZACION.K_MODO_AUTORIZACION_P2=MAU2.K_MODO_AUTORIZACION
	AND		AUTORIZACION.K_MODO_AUTORIZACION_P3=MAU3.K_MODO_AUTORIZACION
	AND		AUTORIZACION.K_MODO_AUTORIZACION_P4=MAU4.K_MODO_AUTORIZACION
	AND		AUTORIZACION.K_MODO_AUTORIZACION_P5=MAU5.K_MODO_AUTORIZACION
			-- ===================================
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P1A=ROL1A.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P2A=ROL2A.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P3A=ROL3A.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P4A=ROL4A.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P5A=ROL5A.K_ROL_AUTORIZACION
			-- ===================================
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P1B=ROL1B.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P2B=ROL2B.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P3B=ROL3B.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P4B=ROL4B.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P5B=ROL5B.K_ROL_AUTORIZACION
			-- ===================================
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P1C=ROL1C.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P2C=ROL2C.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P3C=ROL3C.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P4C=ROL4C.K_ROL_AUTORIZACION
	AND		AUTORIZACION.K_ROL_AUTORIZACION_P5C=ROL5C.K_ROL_AUTORIZACION
			-- ===================================
	AND		AUTORIZACION.K_USUARIO_CAMBIO=USUARIO.K_USUARIO
	AND		AUTORIZACION.L_BORRADO=0
	AND		AUTORIZACION.K_AUTORIZACION=@PP_K_AUTORIZACION
			-- =====================
	ORDER BY K_AUTORIZACION DESC


	-- //////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> INSERT
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_IN_AUTORIZACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_IN_AUTORIZACION]
GO


CREATE PROCEDURE [dbo].[PG_IN_AUTORIZACION] 
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================		
	@PP_D_AUTORIZACION				VARCHAR(100),		
	@PP_S_AUTORIZACION				VARCHAR(10),		
	@PP_C_AUTORIZACION				VARCHAR(500),				
	-- ===========================
	@PP_K_ESTATUS_AUTORIZACION		INT,
	@PP_K_TIPO_AUTORIZACION			INT,	
	@PP_LIMITE_INFERIOR				DECIMAL(19,4),		
	@PP_LIMITE_SUPERIOR				DECIMAL(19,4),				
	-- ===========================
	@PP_K_MODO_AUTORIZACION_P1		INT,
	@PP_N_DIAS_AUTORIZACION_P1		INT,
	@PP_K_ROL_AUTORIZACION_P1A		INT,
	@PP_K_ROL_AUTORIZACION_P1B		INT,
	@PP_K_ROL_AUTORIZACION_P1C		INT,
	-- ===========================
	@PP_K_MODO_AUTORIZACION_P2		INT,
	@PP_N_DIAS_AUTORIZACION_P2		INT,
	@PP_K_ROL_AUTORIZACION_P2A		INT,
	@PP_K_ROL_AUTORIZACION_P2B		INT,
	@PP_K_ROL_AUTORIZACION_P2C		INT,
	-- ===========================
	@PP_K_MODO_AUTORIZACION_P3		INT,
	@PP_N_DIAS_AUTORIZACION_P3		INT,
	@PP_K_ROL_AUTORIZACION_P3A		INT,
	@PP_K_ROL_AUTORIZACION_P3B		INT,
	@PP_K_ROL_AUTORIZACION_P3C		INT,
	-- ===========================
	@PP_K_MODO_AUTORIZACION_P4		INT,
	@PP_N_DIAS_AUTORIZACION_P4		INT,
	@PP_K_ROL_AUTORIZACION_P4A		INT,
	@PP_K_ROL_AUTORIZACION_P4B		INT,
	@PP_K_ROL_AUTORIZACION_P4C		INT,
	-- ===========================
	@PP_K_MODO_AUTORIZACION_P5		INT,
	@PP_N_DIAS_AUTORIZACION_P5		INT,
	@PP_K_ROL_AUTORIZACION_P5A		INT,
	@PP_K_ROL_AUTORIZACION_P5B		INT,
	@PP_K_ROL_AUTORIZACION_P5C		INT
AS			

	DECLARE @VP_MENSAJE		VARCHAR(300)	= ''
	DECLARE @VP_K_AUTORIZACION			INT = 0

	-- /////////////////////////////////////////////////////////////////////
	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_AUTORIZACION_INSERT]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
														@VP_K_AUTORIZACION, @PP_D_AUTORIZACION,
														@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	-- /////////////////////////////////////////////////////////////////////
	
	IF @VP_MENSAJE=''
		BEGIN

		EXECUTE [dbo].[PG_SK_CATALOGO_K_MAX_GET]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE,
													'AUTORIZACION', 
													@OU_K_TABLA_DISPONIBLE = @VP_K_AUTORIZACION			OUTPUT

	-- /////////////////////////////////////////////////////////////////////

		INSERT INTO AUTORIZACION
			(	
			[K_AUTORIZACION], [D_AUTORIZACION],
			[S_AUTORIZACION], [C_AUTORIZACION],	
			-- =====================
			[K_ESTATUS_AUTORIZACION], [K_TIPO_AUTORIZACION],
			[LIMITE_INFERIOR],	[LIMITE_SUPERIOR],
			-- =====================
			[K_MODO_AUTORIZACION_P1], [N_DIAS_AUTORIZACION_P1],
			[K_ROL_AUTORIZACION_P1A], [K_ROL_AUTORIZACION_P1B], [K_ROL_AUTORIZACION_P1C],
			-- =====================
			[K_MODO_AUTORIZACION_P2], [N_DIAS_AUTORIZACION_P2],
			[K_ROL_AUTORIZACION_P2A], [K_ROL_AUTORIZACION_P2B], [K_ROL_AUTORIZACION_P2C],
			-- =====================
			[K_MODO_AUTORIZACION_P3], [N_DIAS_AUTORIZACION_P3],
			[K_ROL_AUTORIZACION_P3A], [K_ROL_AUTORIZACION_P3B], [K_ROL_AUTORIZACION_P3C],
			-- =====================
			[K_MODO_AUTORIZACION_P4], [N_DIAS_AUTORIZACION_P4],
			[K_ROL_AUTORIZACION_P4A], [K_ROL_AUTORIZACION_P4B], [K_ROL_AUTORIZACION_P4C],
			-- =====================
			[K_MODO_AUTORIZACION_P5], [N_DIAS_AUTORIZACION_P5],
			[K_ROL_AUTORIZACION_P5A], [K_ROL_AUTORIZACION_P5B], [K_ROL_AUTORIZACION_P5C],
			-- =====================
			[K_USUARIO_ALTA], [F_ALTA], [K_USUARIO_CAMBIO], [F_CAMBIO],
			[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]
			)
		VALUES
			(
			@VP_K_AUTORIZACION, @PP_D_AUTORIZACION,
			@PP_S_AUTORIZACION,	@PP_C_AUTORIZACION,
			-- ===========================
			@PP_K_ESTATUS_AUTORIZACION,	@PP_K_TIPO_AUTORIZACION,
			@PP_LIMITE_INFERIOR, @PP_LIMITE_SUPERIOR,
			-- ===========================
			@PP_K_MODO_AUTORIZACION_P1, @PP_N_DIAS_AUTORIZACION_P1,
			@PP_K_ROL_AUTORIZACION_P1A, @PP_K_ROL_AUTORIZACION_P1B, @PP_K_ROL_AUTORIZACION_P1C,
			-- ===========================
			@PP_K_MODO_AUTORIZACION_P2, @PP_N_DIAS_AUTORIZACION_P2,	
			@PP_K_ROL_AUTORIZACION_P2A, @PP_K_ROL_AUTORIZACION_P2B,	@PP_K_ROL_AUTORIZACION_P2C,		
			-- ===========================
			@PP_K_MODO_AUTORIZACION_P3, @PP_N_DIAS_AUTORIZACION_P3,
			@PP_K_ROL_AUTORIZACION_P3A, @PP_K_ROL_AUTORIZACION_P3B, @PP_K_ROL_AUTORIZACION_P3C,
			-- ===========================
			@PP_K_MODO_AUTORIZACION_P4, @PP_N_DIAS_AUTORIZACION_P4,
			@PP_K_ROL_AUTORIZACION_P4A, @PP_K_ROL_AUTORIZACION_P4B, @PP_K_ROL_AUTORIZACION_P4C,
			-- ===========================
			@PP_K_MODO_AUTORIZACION_P5, @PP_N_DIAS_AUTORIZACION_P5,
			@PP_K_ROL_AUTORIZACION_P5A, @PP_K_ROL_AUTORIZACION_P5B, @PP_K_ROL_AUTORIZACION_P5C,
			-- ===========================
			@PP_K_USUARIO_ACCION, GETDATE(), @PP_K_USUARIO_ACCION, GETDATE(),
			0, NULL, NULL )
		END
	
	-- /////////////////////////////////////////////////////////////////////

	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Crear] la [Autorización]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#AUT.'+CONVERT(VARCHAR(10),@VP_K_AUTORIZACION)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'
				
		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @VP_K_AUTORIZACION AS CLAVE

	-- //////////////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> UPDATE
-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_AUTORIZACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_AUTORIZACION]
GO


CREATE PROCEDURE [dbo].[PG_UP_AUTORIZACION]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================		
	@PP_K_AUTORIZACION				INT,
	@PP_D_AUTORIZACION				VARCHAR(100),		
	@PP_S_AUTORIZACION				VARCHAR(10),		
	@PP_C_AUTORIZACION				VARCHAR(500),				
	-- ===========================
	@PP_K_ESTATUS_AUTORIZACION		INT,
	@PP_K_TIPO_AUTORIZACION			INT,	
	@PP_LIMITE_INFERIOR				DECIMAL(19,4),		
	@PP_LIMITE_SUPERIOR				DECIMAL(19,4),				
	-- ===========================
	@PP_K_MODO_AUTORIZACION_P1		INT,
	@PP_N_DIAS_AUTORIZACION_P1		INT,
	@PP_K_ROL_AUTORIZACION_P1A		INT,
	@PP_K_ROL_AUTORIZACION_P1B		INT,
	@PP_K_ROL_AUTORIZACION_P1C		INT,
	-- ===========================
	@PP_K_MODO_AUTORIZACION_P2		INT,
	@PP_N_DIAS_AUTORIZACION_P2		INT,
	@PP_K_ROL_AUTORIZACION_P2A		INT,
	@PP_K_ROL_AUTORIZACION_P2B		INT,
	@PP_K_ROL_AUTORIZACION_P2C		INT,
	-- ===========================
	@PP_K_MODO_AUTORIZACION_P3		INT,
	@PP_N_DIAS_AUTORIZACION_P3		INT,
	@PP_K_ROL_AUTORIZACION_P3A		INT,
	@PP_K_ROL_AUTORIZACION_P3B		INT,
	@PP_K_ROL_AUTORIZACION_P3C		INT,
	-- ===========================
	@PP_K_MODO_AUTORIZACION_P4		INT,
	@PP_N_DIAS_AUTORIZACION_P4		INT,
	@PP_K_ROL_AUTORIZACION_P4A		INT,
	@PP_K_ROL_AUTORIZACION_P4B		INT,
	@PP_K_ROL_AUTORIZACION_P4C		INT,
	-- ===========================
	@PP_K_MODO_AUTORIZACION_P5		INT,
	@PP_N_DIAS_AUTORIZACION_P5		INT,
	@PP_K_ROL_AUTORIZACION_P5A		INT,
	@PP_K_ROL_AUTORIZACION_P5B		INT,
	@PP_K_ROL_AUTORIZACION_P5C		INT
AS

	DECLARE @VP_MENSAJE		VARCHAR(300)	= ''

	-- /////////////////////////////////////////////////////////////////////

	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_AUTORIZACION_UPDATE]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
														@PP_K_AUTORIZACION, 
														@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
															
	-- /////////////////////////////////////////////////////////////////////

	IF @VP_MENSAJE=''
		BEGIN
	
		UPDATE	AUTORIZACION
		SET		
				[D_AUTORIZACION]			=	@PP_D_AUTORIZACION,		
				[S_AUTORIZACION]			=	@PP_S_AUTORIZACION,		
				[C_AUTORIZACION]			=	@PP_C_AUTORIZACION,		
				-- =====================	=	-- =========================
				[K_ESTATUS_AUTORIZACION]	=	@PP_K_ESTATUS_AUTORIZACION,
				[K_TIPO_AUTORIZACION]		=	@PP_K_TIPO_AUTORIZACION,
				[LIMITE_INFERIOR]			=	@PP_LIMITE_INFERIOR,	
				[LIMITE_SUPERIOR]			=	@PP_LIMITE_SUPERIOR,		
				-- =====================	=	-- =========================
				[K_MODO_AUTORIZACION_P1]	=	@PP_K_MODO_AUTORIZACION_P1,
				[N_DIAS_AUTORIZACION_P1]	=	@PP_N_DIAS_AUTORIZACION_P1,
				[K_ROL_AUTORIZACION_P1A]	=	@PP_K_ROL_AUTORIZACION_P1A,
				[K_ROL_AUTORIZACION_P1B]	=	@PP_K_ROL_AUTORIZACION_P1B,
				[K_ROL_AUTORIZACION_P1C]	=	@PP_K_ROL_AUTORIZACION_P1C,
				-- =====================	=	-- =========================
				[K_MODO_AUTORIZACION_P2]	=	@PP_K_MODO_AUTORIZACION_P2,
				[N_DIAS_AUTORIZACION_P2]	=	@PP_N_DIAS_AUTORIZACION_P2,
				[K_ROL_AUTORIZACION_P2A]	=	@PP_K_ROL_AUTORIZACION_P2A,
				[K_ROL_AUTORIZACION_P2B]	=	@PP_K_ROL_AUTORIZACION_P2B,
				[K_ROL_AUTORIZACION_P2C]	=	@PP_K_ROL_AUTORIZACION_P2C,
				-- =====================	=	-- =========================
				[K_MODO_AUTORIZACION_P3]	=	@PP_K_MODO_AUTORIZACION_P3,
				[N_DIAS_AUTORIZACION_P3]	=	@PP_N_DIAS_AUTORIZACION_P3,
				[K_ROL_AUTORIZACION_P3A]	=	@PP_K_ROL_AUTORIZACION_P3A,
				[K_ROL_AUTORIZACION_P3B]	=	@PP_K_ROL_AUTORIZACION_P3B,
				[K_ROL_AUTORIZACION_P3C]	=	@PP_K_ROL_AUTORIZACION_P3C,
				-- =====================	=	-- =========================
				[K_MODO_AUTORIZACION_P4]	=	@PP_K_MODO_AUTORIZACION_P4,
				[N_DIAS_AUTORIZACION_P4]	=	@PP_N_DIAS_AUTORIZACION_P4,
				[K_ROL_AUTORIZACION_P4A]	=	@PP_K_ROL_AUTORIZACION_P4A,
				[K_ROL_AUTORIZACION_P4B]	=	@PP_K_ROL_AUTORIZACION_P4B,
				[K_ROL_AUTORIZACION_P4C]	=	@PP_K_ROL_AUTORIZACION_P4C,
				-- =====================	=	-- =========================
				[K_MODO_AUTORIZACION_P5]	=	@PP_K_MODO_AUTORIZACION_P5,
				[N_DIAS_AUTORIZACION_P5]	=	@PP_N_DIAS_AUTORIZACION_P5,
				[K_ROL_AUTORIZACION_P5A]	=	@PP_K_ROL_AUTORIZACION_P5A,
				[K_ROL_AUTORIZACION_P5B]	=	@PP_K_ROL_AUTORIZACION_P5B,
				[K_ROL_AUTORIZACION_P5C]	=	@PP_K_ROL_AUTORIZACION_P5C,
				-- ====================
				[F_CAMBIO]				= GETDATE(), 
				[K_USUARIO_CAMBIO]		= @PP_K_USUARIO_ACCION
		WHERE	K_AUTORIZACION=@PP_K_AUTORIZACION
		AND		L_BORRADO=0

		END

	-- /////////////////////////////////////////////////////////////////////
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Actualizar] la [Autorización]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#AUT.'+CONVERT(VARCHAR(10),@PP_K_AUTORIZACION)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'

		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_AUTORIZACION AS CLAVE

	-- /////////////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_DL_AUTORIZACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_DL_AUTORIZACION]
GO


CREATE PROCEDURE [dbo].[PG_DL_AUTORIZACION]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_K_AUTORIZACION		INT
AS

	DECLARE @VP_MENSAJE		VARCHAR(300)
	
	SET		@VP_MENSAJE		= ''

	-- /////////////////////////////////////////////////////////////////////
	
	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_AUTORIZACION_DELETE]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
														@PP_K_AUTORIZACION, 
														@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
															
	-- /////////////////////////////////////////////////////////////////////

	IF @VP_MENSAJE=''
		BEGIN
	
		UPDATE	AUTORIZACION
		SET		
				[L_BORRADO]				= 1,
				-- ====================
				[F_BAJA]				= GETDATE(), 
				[K_USUARIO_BAJA]		= @PP_K_USUARIO_ACCION
		WHERE	K_AUTORIZACION=@PP_K_AUTORIZACION
		AND		L_BORRADO=0

		END

	-- /////////////////////////////////////////////////////////////////////
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Borrar] la [Autorización]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#AUT.'+CONVERT(VARCHAR(10),@PP_K_AUTORIZACION)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'
		
		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_AUTORIZACION AS CLAVE

	-- /////////////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////////////////////////////////////////////////////
