-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			PYF18_R700_50.c_SP_MonitoreoAutorizacionFirma
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			MONITOREO_AUTORIZACION_FIRMA
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- //////////////////////////////////////////////////////////////
-- // Autor:			ALEX DE LA ROSA // HECTOR A. GONZALEZ 
-- // Fecha creación:	22/OCT/2018
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0]
GO


-- //////////////////////////////////////////////////////////////




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE --->  LISTADO AUTORIZACION_FIRMA
-- //////////////////////////////////////////////////////////////


/*
EXECUTE [dbo].[PG_LI_AUTORIZACION_FIRMA] 0,0,0,'',	-1,-1,-1,	-1,-1,-1,NULL,NULL 
*/


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_AUTORIZACION_FIRMA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_AUTORIZACION_FIRMA]
GO	


CREATE PROCEDURE [dbo].[PG_LI_AUTORIZACION_FIRMA]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================
	@PP_D_AUTORIZACION_FIRMA			VARCHAR(100),
	-- ==============================
	@PP_K_ZONA_UO						INT,
	@PP_K_RAZON_SOCIAL					INT,
	@PP_K_UNIDAD_OPERATIVA				INT,
	-- ==============================
	@PP_K_TIPO_AUTORIZACION				INT,
	@PP_K_AUTORIZACION					INT,
	@PP_K_ESTATUS_FIRMA					INT,
	-- ==============================
	@PP_F_INICIO						DATE,
	@PP_F_FIN							DATE,
	-- ==============================
	@PP_L_SOLO_AUTORIZACION_DIRECTA		INT
AS			

	DECLARE @VP_MENSAJE		VARCHAR(300)	= ''
	
	-- ///////////////////////////////////////////

	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_DATA_ACCESO_SELECT]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
													8, -- @PP_K_DATA_SISTEMA,	
													@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	-- ///////////////////////////////////////////

	DECLARE @VP_LI_N_REGISTROS		INT		= 1000
	
	EXECUTE [dbo].[PG_SK_CONFIGURACION_LISTADO_MAX_ROWS_PESADO_GET]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE,
																			1, -- WIWI // @VP_L_APLICAR_MAX_ROWS,
																			@OU_MAXROWS = @VP_LI_N_REGISTROS		OUTPUT
	-- =========================================	
	
	DECLARE @VP_K_FOLIO		INT

	EXECUTE [dbo].[PG_RN_OBTENER_ID_X_REFERENCIA]	@PP_D_AUTORIZACION_FIRMA, 
													@OU_K_ELEMENTO = @VP_K_FOLIO	OUTPUT
	-- =========================================
	
	IF NOT (@VP_MENSAJE='')
		SET @VP_LI_N_REGISTROS = 0

	-- ///////////////////////////////////////////

	SELECT	TOP ( @VP_LI_N_REGISTROS )		
			AUTORIZACION_FIRMA.*, 
			F_APER.D_TIEMPO_FECHA AS F_APERTURA_DDMMMYYYY,
			F_CIER.D_TIEMPO_FECHA AS F_CIERRE_DDMMMYYYY,
			AFU.D_USUARIO AS D_USUARIO_CAMBIO, AFU.S_USUARIO AS S_USUARIO_CAMBIO,
			USUARIO.D_USUARIO, USUARIO.S_USUARIO
			-- ================================= 
			D_UNIDAD_OPERATIVA, D_TIPO_UO, D_ZONA_UO, D_RAZON_SOCIAL, 
			S_UNIDAD_OPERATIVA, S_TIPO_UO, S_ZONA_UO, S_RAZON_SOCIAL,
			-- ================================= 
			D_TIPO_AUTORIZACION, D_AUTORIZACION, D_ESTATUS_FIRMA,
			S_TIPO_AUTORIZACION, S_AUTORIZACION, S_ESTATUS_FIRMA			
			-- ================================= 
	FROM	AUTORIZACION_FIRMA
				LEFT JOIN USUARIO			ON AUTORIZACION_FIRMA.K_USUARIO_AUTORIZACION_DIRECTA=USUARIO.K_USUARIO
				LEFT JOIN ESTATUS_FIRMA		ON AUTORIZACION_FIRMA.K_ESTATUS_FIRMA=ESTATUS_FIRMA.K_ESTATUS_FIRMA
				LEFT JOIN AUTORIZACION		ON AUTORIZACION_FIRMA.K_AUTORIZACION=AUTORIZACION.K_AUTORIZACION
				LEFT JOIN USUARIO AS AFU	ON AUTORIZACION_FIRMA.K_USUARIO_CAMBIO=AFU.K_USUARIO
				LEFT JOIN TIEMPO_FECHA AS F_APER	ON AUTORIZACION_FIRMA.F_APERTURA=F_APER.F_TIEMPO_FECHA
				LEFT JOIN TIEMPO_FECHA AS F_CIER	ON AUTORIZACION_FIRMA.F_CIERRE=F_CIER.F_TIEMPO_FECHA,
			VI_UNIDAD_OPERATIVA_CATALOGOS, TIPO_AUTORIZACION
	WHERE	AUTORIZACION_FIRMA.K_UNIDAD_OPERATIVA=VI_UNIDAD_OPERATIVA_CATALOGOS.VI_K_UNIDAD_OPERATIVA
	AND		AUTORIZACION_FIRMA.L_BORRADO=0
	AND		AUTORIZACION.K_TIPO_AUTORIZACION=TIPO_AUTORIZACION.K_TIPO_AUTORIZACION
			-- ================================= 
	AND		( @PP_K_ZONA_UO=-1				OR	@PP_K_ZONA_UO=VI_K_ZONA_UO )
	AND		( @PP_K_RAZON_SOCIAL=-1			OR	@PP_K_RAZON_SOCIAL=VI_K_RAZON_SOCIAL )
	AND		( @PP_K_UNIDAD_OPERATIVA=-1		OR	@PP_K_UNIDAD_OPERATIVA=VI_K_UNIDAD_OPERATIVA )
			-- ==============================
	AND		(	
					AUTORIZACION_FIRMA.D_AUTORIZACION_FIRMA		LIKE '%'+@PP_D_AUTORIZACION_FIRMA+'%'
				OR	ESTATUS_FIRMA.D_ESTATUS_FIRMA				LIKE '%'+@PP_D_AUTORIZACION_FIRMA+'%'
				OR	USUARIO.D_USUARIO							LIKE '%'+@PP_D_AUTORIZACION_FIRMA+'%'
				OR	AUTORIZACION.D_AUTORIZACION					LIKE '%'+@PP_D_AUTORIZACION_FIRMA+'%'
				OR	AUTORIZACION_FIRMA.K_AUTORIZACION_FIRMA=@VP_K_FOLIO 
			)
			-- =============================
	AND		( @PP_K_TIPO_AUTORIZACION=-1			OR		AUTORIZACION.K_TIPO_AUTORIZACION=@PP_K_TIPO_AUTORIZACION )
	AND		( @PP_K_AUTORIZACION=-1					OR		AUTORIZACION.K_AUTORIZACION=@PP_K_AUTORIZACION )
	AND		( @PP_K_ESTATUS_FIRMA=-1				OR		AUTORIZACION_FIRMA.K_ESTATUS_FIRMA=@PP_K_ESTATUS_FIRMA )	
			-- =============================
	AND		( @PP_F_INICIO IS NULL					OR		@PP_F_INICIO<=AUTORIZACION_FIRMA.F_APERTURA )
	AND		( @PP_F_FIN	IS NULL						OR		AUTORIZACION_FIRMA.F_APERTURA<=@PP_F_FIN )
			-- ===========================	
	AND		( @PP_L_SOLO_AUTORIZACION_DIRECTA=0		OR		AUTORIZACION_FIRMA.L_AUTORIZACION_DIRECTA=1 )
			-- ===========================	
	ORDER BY AUTORIZACION_FIRMA.K_AUTORIZACION_FIRMA DESC

	-- //////////////////////////////////////////////////////////////
GO



/*
EXECUTE [dbo].[PG_SK_AUTORIZACION_FIRMA] 0,0,0,160 
*/

-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SEEK AUTORIZACION_FIRMA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_AUTORIZACION_FIRMA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_AUTORIZACION_FIRMA]
GO	

CREATE PROCEDURE [dbo].[PG_SK_AUTORIZACION_FIRMA]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_K_AUTORIZACION_FIRMA	INT
AS			

	DECLARE @VP_MENSAJE		VARCHAR(300)	= ''
	
	-- ///////////////////////////////////////////

	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_DATA_ACCESO_SELECT]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
													8, -- @PP_K_DATA_SISTEMA,	
													@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	-- ///////////////////////////////////////////

	DECLARE @VP_LI_N_REGISTROS	INT = 1000
	
	IF NOT (@VP_MENSAJE='')
		SET @VP_LI_N_REGISTROS = 0

	-- ///////////////////////////////////////////
	
	SELECT	TOP ( @VP_LI_N_REGISTROS )		
			AUTORIZACION_FIRMA.*, 
			D_ESTATUS_FIRMA,S_ESTATUS_FIRMA,
			D_AUTORIZACION,S_AUTORIZACION,
			F_APER.D_TIEMPO_FECHA AS F_APERTURA_DDMMMYYYY,
			F_CIER.D_TIEMPO_FECHA AS F_CIERRE_DDMMMYYYY,
			AFU.D_USUARIO AS D_USUARIO_CAMBIO, AFU.S_USUARIO AS S_USUARIO_CAMBIO,
			USUARIO.D_USUARIO, USUARIO.S_USUARIO
			-- ================================= 
			D_UNIDAD_OPERATIVA, 
			D_TIPO_UO, D_ZONA_UO, D_RAZON_SOCIAL, 
			-- ================================= 
			S_UNIDAD_OPERATIVA, 
			S_TIPO_UO, S_ZONA_UO, S_RAZON_SOCIAL
			-- ================================= 
	FROM	AUTORIZACION_FIRMA
				LEFT JOIN USUARIO			ON AUTORIZACION_FIRMA.K_USUARIO_AUTORIZACION_DIRECTA=USUARIO.K_USUARIO
				LEFT JOIN ESTATUS_FIRMA		ON AUTORIZACION_FIRMA.K_ESTATUS_FIRMA=ESTATUS_FIRMA.K_ESTATUS_FIRMA
				LEFT JOIN AUTORIZACION		ON  AUTORIZACION_FIRMA.K_AUTORIZACION=AUTORIZACION.K_AUTORIZACION
				LEFT JOIN USUARIO AS AFU	ON AUTORIZACION_FIRMA.K_USUARIO_CAMBIO=AFU.K_USUARIO
				LEFT JOIN TIEMPO_FECHA AS F_APER	ON AUTORIZACION_FIRMA.F_APERTURA=F_APER.F_TIEMPO_FECHA
				LEFT JOIN TIEMPO_FECHA AS F_CIER	ON AUTORIZACION_FIRMA.F_CIERRE=F_CIER.F_TIEMPO_FECHA,
			VI_UNIDAD_OPERATIVA_CATALOGOS
	WHERE	AUTORIZACION_FIRMA.K_UNIDAD_OPERATIVA=VI_UNIDAD_OPERATIVA_CATALOGOS.VI_K_UNIDAD_OPERATIVA
	AND		AUTORIZACION_FIRMA.L_BORRADO=0
	AND		AUTORIZACION_FIRMA.K_AUTORIZACION_FIRMA=@PP_K_AUTORIZACION_FIRMA 
	
		-- //////////////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE --->  LISTADO FLUJO_FIRMA_X_K_AUTORIZACION
-- //////////////////////////////////////////////////////////////

-- [PG_LI_FLUJO_FIRMA_X_K_AUTORIZACION] 0,0,0,	7 

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_FLUJO_FIRMA_X_K_AUTORIZACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_LI_FLUJO_FIRMA_X_K_AUTORIZACION]
GO	


CREATE PROCEDURE [dbo].[PG_LI_FLUJO_FIRMA_X_K_AUTORIZACION]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_K_AUTORIZACION_FIRMA	INT
	---- ===========================
AS			

	DECLARE @VP_MENSAJE		VARCHAR(300)	= ''
	
	-- ///////////////////////////////////////////

	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_DATA_ACCESO_SELECT]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
													8, -- @PP_K_DATA_SISTEMA,	
													@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	-- ///////////////////////////////////////////

	DECLARE @VP_LI_N_REGISTROS		INT		= 1000
	
		EXECUTE [dbo].[PG_SK_CONFIGURACION_LISTADO_MAX_ROWS_PESADO_GET]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE,
																			1, -- WIWI // @VP_L_APLICAR_MAX_ROWS,
																			@OU_MAXROWS = @VP_LI_N_REGISTROS		OUTPUT
	-- =========================================	
	IF NOT (@VP_MENSAJE='')
		SET @VP_LI_N_REGISTROS = 0

	-- ///////////////////////////////////////////

	SELECT	TOP ( @VP_LI_N_REGISTROS )		
			FLUJO_FIRMA.*, 
			D_AUTORIZACION_FIRMA, S_AUTORIZACION_FIRMA,
			D_MODO_AUTORIZACION,  S_MODO_AUTORIZACION,
			ESTATUS_FIRMA.D_ESTATUS_FIRMA, ESTATUS_FIRMA.S_ESTATUS_FIRMA,
			USUARIO.D_USUARIO AS D_USUARIO_CAMBIO, USUARIO.S_USUARIO AS S_USUARIO_CAMBIO,
			-- =========================================
			ROLA.D_ROL_AUTORIZACION AS ROLA_D_ROL_AUTORIZACION, ROLA.S_ROL_AUTORIZACION AS ROLA_S_ROL_AUTORIZACION, 
			ROLB.D_ROL_AUTORIZACION AS ROLB_D_ROL_AUTORIZACION, ROLB.S_ROL_AUTORIZACION AS ROLB_S_ROL_AUTORIZACION,
			ROLC.D_ROL_AUTORIZACION AS ROLC_D_ROL_AUTORIZACION,	ROLC.S_ROL_AUTORIZACION AS ROLC_S_ROL_AUTORIZACION,
			-- =========================================
			USUARIO_FIRMAA.D_USUARIO AS USUARIO_FIRMAA_D_USUARIO, USUARIO_FIRMAA.S_USUARIO AS USUARIO_FIRMAA_S_USUARIO,
			USUARIO_FIRMAB.D_USUARIO AS USUARIO_FIRMAB_D_USUARIO, USUARIO_FIRMAB.S_USUARIO AS USUARIO_FIRMAB_S_USUARIO,
			USUARIO_FIRMAC.D_USUARIO AS USUARIO_FIRMAC_D_USUARIO, USUARIO_FIRMAC.S_USUARIO AS USUARIO_FIRMAC_S_USUARIO,
			-- =========================================
			ESTATUS_FIRMAA.D_ESTATUS_FIRMA AS ESTATUS_FIRMAA_D_ESTATUS_FIRMA, ESTATUS_FIRMAA.S_ESTATUS_FIRMA AS ESTATUS_FIRMAA_S_ESTATUS_FIRMA,
			ESTATUS_FIRMAB.D_ESTATUS_FIRMA AS ESTATUS_FIRMAB_D_ESTATUS_FIRMA, ESTATUS_FIRMAB.S_ESTATUS_FIRMA AS ESTATUS_FIRMAB_S_ESTATUS_FIRMA,
			ESTATUS_FIRMAC.D_ESTATUS_FIRMA AS ESTATUS_FIRMAC_D_ESTATUS_FIRMA, ESTATUS_FIRMAC.S_ESTATUS_FIRMA AS ESTATUS_FIRMAC_S_ESTATUS_FIRMA
			-- =========================================
	FROM	FLUJO_FIRMA
			-- =========================================
			LEFT JOIN AUTORIZACION_FIRMA ON FLUJO_FIRMA.K_AUTORIZACION_FIRMA=AUTORIZACION_FIRMA.K_AUTORIZACION_FIRMA
			LEFT JOIN MODO_AUTORIZACION ON FLUJO_FIRMA.K_MODO_AUTORIZACION=MODO_AUTORIZACION.K_MODO_AUTORIZACION
			LEFT JOIN ESTATUS_FIRMA ON FLUJO_FIRMA.K_ESTATUS_FIRMA=ESTATUS_FIRMA.K_ESTATUS_FIRMA
			-- =========================================
			LEFT JOIN ROL_AUTORIZACION AS ROLA ON FLUJO_FIRMA.K_ROL_AUTORIZACION_A=ROLA.K_ROL_AUTORIZACION
			LEFT JOIN ROL_AUTORIZACION AS ROLB ON FLUJO_FIRMA.K_ROL_AUTORIZACION_B=ROLB.K_ROL_AUTORIZACION
			LEFT JOIN ROL_AUTORIZACION AS ROLC ON FLUJO_FIRMA.K_ROL_AUTORIZACION_C=ROLC.K_ROL_AUTORIZACION
			-- =========================================
			LEFT JOIN USUARIO AS USUARIO_FIRMAA ON FLUJO_FIRMA.K_USUARIO_FIRMA_A=USUARIO_FIRMAA.K_USUARIO
			LEFT JOIN USUARIO AS USUARIO_FIRMAB ON FLUJO_FIRMA.K_USUARIO_FIRMA_B=USUARIO_FIRMAB.K_USUARIO
			LEFT JOIN USUARIO AS USUARIO_FIRMAC ON FLUJO_FIRMA.K_USUARIO_FIRMA_C=USUARIO_FIRMAC.K_USUARIO
			-- =========================================
			LEFT JOIN ESTATUS_FIRMA AS ESTATUS_FIRMAA ON FLUJO_FIRMA.K_ESTATUS_FIRMA_A=ESTATUS_FIRMAA.K_ESTATUS_FIRMA
			LEFT JOIN ESTATUS_FIRMA AS ESTATUS_FIRMAB ON FLUJO_FIRMA.K_ESTATUS_FIRMA_B=ESTATUS_FIRMAB.K_ESTATUS_FIRMA
			LEFT JOIN ESTATUS_FIRMA AS ESTATUS_FIRMAC ON FLUJO_FIRMA.K_ESTATUS_FIRMA_C=ESTATUS_FIRMAC.K_ESTATUS_FIRMA

	LEFT JOIN USUARIO ON FLUJO_FIRMA.K_USUARIO_CAMBIO = USUARIO.K_USUARIO
	-- =========================================
	
	WHERE	FLUJO_FIRMA.L_BORRADO=0
	--		-- =========================================
	AND		( @PP_K_AUTORIZACION_FIRMA=-1		OR		FLUJO_FIRMA.K_AUTORIZACION_FIRMA=@PP_K_AUTORIZACION_FIRMA)
	
	ORDER BY FLUJO_FIRMA.K_FLUJO_FIRMA 

	-- //////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////////////////////////////////////////////////////
