-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			PLAN_GASTO GASTOS/PLANTA
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- ////////////////////////////////////////////////////////////// 
-- // Autor:			HECTOR A. GONZALEZ DE LA FUENTE
-- // Fecha creación:	08/OCT/2018
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0]
GO


-- //////////////////////////////////////////////////////////////





-- ///////////////////////////////////////////////////////////////
-- // 
-- ///////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_ESTIMADO_X_K_NIVEL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_ESTIMADO_X_K_NIVEL]
GO


CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_ESTIMADO_X_K_NIVEL]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ==============================
	@PP_K_PLAN_GASTO				INT,
	@PP_K_NIVEL_RUBRO_PRESUPUESTO	INT
AS
	-- ==============================================

	UPDATE	PARTIDA_PLAN_GASTO
	SET		MONTO_ESTIMADO     = (		SELECT	SUM(Q2PAR.MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			M00_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M00_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			M01_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M01_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			M02_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M02_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			M03_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M03_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			-- ======================
			M04_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M04_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			M05_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M05_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			M06_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M06_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			-- ======================
			M07_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M07_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			M08_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M08_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			M09_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M09_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			-- ======================
			M10_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M10_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			M11_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M11_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		),
			M12_MONTO_ESTIMADO = (		SELECT	SUM(Q2PAR.M12_MONTO_ESTIMADO) AS SUM_MES_MONTO_ESTIMADO 
										FROM	PARTIDA_PLAN_GASTO AS Q2PAR, RUBRO_PRESUPUESTO AS Q2RUB
										WHERE	Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PLAN_GASTO=Q1PAR.K_PLAN_GASTO		)
	FROM	PARTIDA_PLAN_GASTO AS Q1PAR, RUBRO_PRESUPUESTO AS Q2RUB
	WHERE	Q1PAR.K_PLAN_GASTO=@PP_K_PLAN_GASTO
	AND		Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
	AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	-- //////////////////////////////////////////////////////////////
GO




-- ///////////////////////////////////////////////////////////////
-- // 
-- ///////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_ESTIMADO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_ESTIMADO]
GO


CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_ESTIMADO]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ==============================
	@PP_K_PLAN_GASTO			INT
AS
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_ESTIMADO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PLAN_GASTO, 4
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_ESTIMADO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PLAN_GASTO, 3
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_ESTIMADO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PLAN_GASTO, 2
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_ESTIMADO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PLAN_GASTO, 1

	-- //////////////////////////////////////////////////////////////
GO



-- ///////////////////////////////////////////////////////////////
-- // 
-- ///////////////////////////////////////////////////////////////
/*

SELECT	D_RUBRO_PRESUPUESTO, O_RUBRO_PRESUPUESTO AS ORDEN, K_NIVEL_RUBRO_PRESUPUESTO AS NIVEL, 
		'///' AS C,
		PARTIDA_PLAN_GASTO.* 
FROM	PARTIDA_PLAN_GASTO, RUBRO_PRESUPUESTO 
WHERE	PARTIDA_PLAN_GASTO.K_RUBRO_PRESUPUESTO=RUBRO_PRESUPUESTO.K_RUBRO_PRESUPUESTO
AND		K_PLAN_GASTO=3001

*/

-- EXECUTE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION] 0,0,0, 3001


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION]
GO


CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ==============================
	@PP_K_PLAN_GASTO			INT
AS
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_ESTIMADO]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																	@PP_K_PLAN_GASTO
	-- ==============================================
/*
	EXECUTE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_PROCESO]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																	@PP_K_PLAN_GASTO
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PLAN_GASTO_AGREGACION_EJERCIDO]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																	@PP_K_PLAN_GASTO
*/
	-- //////////////////////////////////////////////////////////
GO





-- ////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////
