-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			PRESUPUESTO GASTOS/PLANTA
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- ////////////////////////////////////////////////////////////// 
-- // Autor:			HECTOR A. GONZALEZ DE LA FUENTE
-- // Fecha creación:	08/OCT/2018
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0]
GO


-- //////////////////////////////////////////////////////////////





-- ///////////////////////////////////////////////////////////////
-- //					
-- ///////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PRESUPUESTO_CALCULOS_MES]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_CALCULOS_MES]
GO


CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_CALCULOS_MES]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ========================================
	@PP_K_PRESUPUESTO				INT,
	@PP_K_RUBRO_PRESUPUESTO			INT
	-- ========================================
AS

	DECLARE @VP_MENSAJE			VARCHAR(300) = ''

	-- /////////////////////////////////////////////////////////////////////
	
	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_PARTIDA_PRESUPUESTO_UPDATE]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
															@PP_K_PRESUPUESTO, @PP_K_RUBRO_PRESUPUESTO,
															@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT

	-- ///////////////////////////////////////////////

	IF @VP_MENSAJE=''
		BEGIN
		
		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		MES_MONTO_EN_PROCESO = (  W01_MONTO_EN_PROCESO 
										+ W02_MONTO_EN_PROCESO 
										+ W03_MONTO_EN_PROCESO 
										+ W04_MONTO_EN_PROCESO 
										+ W05_MONTO_EN_PROCESO ) 				
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO

		-- ========================================

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		MES_MONTO_EJERCIDO = (    W01_MONTO_EJERCIDO
										+ W02_MONTO_EJERCIDO 
										+ W03_MONTO_EJERCIDO 
										+ W04_MONTO_EJERCIDO 
										+ W05_MONTO_EJERCIDO ) 				
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO

		-- ========================================

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		MES_MONTO_REMANENTE = (   W01_MONTO_REMANENTE
										+ W02_MONTO_REMANENTE 
										+ W03_MONTO_REMANENTE 
										+ W04_MONTO_REMANENTE 
										+ W05_MONTO_REMANENTE ) 				
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO

		-- ========================================

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		MES_PORCENTAJE_REMANENTE = 0
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		MES_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( MES_MONTO_REMANENTE / MES_MONTO_ESTIMADO ) )
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
		AND		MES_MONTO_ESTIMADO<>0

		-- =========================================================
		END

	-- /////////////////////////////////////////////////////////////////////

	IF @VP_MENSAJE <> ''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible <Calcular el Mes> de la Partida del Presupuesto: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#Pre.'+CONVERT(VARCHAR(10),@PP_K_PRESUPUESTO)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'
		
		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_PRESUPUESTO AS CLAVE

	-- /////////////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> UP PARTIDA PRESUPUESTO
-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PRESUPUESTO_CALCULOS_SEMANA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_CALCULOS_SEMANA]
GO

CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_CALCULOS_SEMANA]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ========================================
	@PP_K_PRESUPUESTO				INT,
	@PP_K_RUBRO_PRESUPUESTO			INT
	-- ========================================
AS

	DECLARE @VP_MENSAJE			VARCHAR(300) = ''

	-- /////////////////////////////////////////////////////////////////////
	
	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_PARTIDA_PRESUPUESTO_UPDATE]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
															@PP_K_PRESUPUESTO, @PP_K_RUBRO_PRESUPUESTO,
															@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT

	-- ///////////////////////////////////////////////

	IF @VP_MENSAJE=''
		BEGIN
		
		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		W01_MONTO_REMANENTE = ( W01_MONTO_ESTIMADO - W01_MONTO_EJERCIDO ) 
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO

		-- ========================================
		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		W02_MONTO_REMANENTE = ( W02_MONTO_ESTIMADO - W02_MONTO_EJERCIDO ) 
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO

		-- ========================================

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		W03_MONTO_REMANENTE = ( W03_MONTO_ESTIMADO - W03_MONTO_EJERCIDO ) 
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO

		-- ========================================

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		W04_MONTO_REMANENTE = ( W04_MONTO_ESTIMADO - W04_MONTO_EJERCIDO ) 
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO

		-- ========================================

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		W05_MONTO_REMANENTE = ( W05_MONTO_ESTIMADO - W05_MONTO_EJERCIDO ) 
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO

		-- ////////////////////////////////////////////////////////

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		W01_PORCENTAJE_REMANENTE = 0,
				W02_PORCENTAJE_REMANENTE = 0,
				W03_PORCENTAJE_REMANENTE = 0,
				W04_PORCENTAJE_REMANENTE = 0,
				W05_PORCENTAJE_REMANENTE = 0
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO

		-- ////////////////////////////////////////////////////////

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		W01_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W01_MONTO_REMANENTE / W01_MONTO_ESTIMADO ) )
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
		AND		W01_MONTO_ESTIMADO<>0
		
		-- ========================================

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		W02_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W02_MONTO_REMANENTE / W02_MONTO_ESTIMADO ) )
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
		AND		W02_MONTO_ESTIMADO<>0

		-- ========================================

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		W03_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W03_MONTO_REMANENTE / W03_MONTO_ESTIMADO ) )
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
		AND		W03_MONTO_ESTIMADO<>0

		-- ========================================

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		W04_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W04_MONTO_REMANENTE / W04_MONTO_ESTIMADO ) )
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
		AND		W04_MONTO_ESTIMADO<>0

		-- ========================================

		UPDATE	[PARTIDA_PRESUPUESTO]
		SET		W05_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W05_MONTO_REMANENTE / W05_MONTO_ESTIMADO ) )
		WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
		AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
		AND		W05_MONTO_ESTIMADO<>0
		
		END

	-- /////////////////////////////////////////////////////////////////////

	IF @VP_MENSAJE <> ''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible <Calcular las Semanas> de la Partida del Presupuesto: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#Pre.'+CONVERT(VARCHAR(10),@PP_K_PRESUPUESTO)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'
		
		END
	
	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_PRESUPUESTO AS CLAVE

	-- /////////////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> UP PARTIDA PRESUPUESTO
-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_REMANENTE]
GO


CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_REMANENTE]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ==============================
	@PP_K_PRESUPUESTO			INT
AS
	-- ==============================================

	UPDATE	PARTIDA_PRESUPUESTO
	SET		[MES_MONTO_REMANENTE] = (MES_MONTO_ESTIMADO-MES_MONTO_EN_PROCESO-MES_MONTO_EJERCIDO),
			[W01_MONTO_REMANENTE] = (W01_MONTO_ESTIMADO-W01_MONTO_EN_PROCESO-W01_MONTO_EJERCIDO),
			[W02_MONTO_REMANENTE] = (W02_MONTO_ESTIMADO-W02_MONTO_EN_PROCESO-W02_MONTO_EJERCIDO),
			[W03_MONTO_REMANENTE] = (W03_MONTO_ESTIMADO-W03_MONTO_EN_PROCESO-W03_MONTO_EJERCIDO),
			[W04_MONTO_REMANENTE] = (W04_MONTO_ESTIMADO-W04_MONTO_EN_PROCESO-W04_MONTO_EJERCIDO),
			[W05_MONTO_REMANENTE] = (W05_MONTO_ESTIMADO-W05_MONTO_EN_PROCESO-W05_MONTO_EJERCIDO)
	WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO	

	-- ==============================================
	
	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		MES_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( MES_MONTO_REMANENTE / MES_MONTO_ESTIMADO ) )
	WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO	
	AND		MES_MONTO_ESTIMADO<>0
	
	-- ========================================	
	
	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		W01_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W01_MONTO_REMANENTE / W01_MONTO_ESTIMADO ) )
	WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO	
	AND		W01_MONTO_ESTIMADO<>0
	
	-- ========================================

	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		W02_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W02_MONTO_REMANENTE / W02_MONTO_ESTIMADO ) )
	WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
	AND		W02_MONTO_ESTIMADO<>0

	-- ========================================

	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		W03_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W03_MONTO_REMANENTE / W03_MONTO_ESTIMADO ) )
	WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
	AND		W03_MONTO_ESTIMADO<>0

	-- ========================================

	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		W04_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W04_MONTO_REMANENTE / W04_MONTO_ESTIMADO ) )
	WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
	AND		W04_MONTO_ESTIMADO<>0

	-- ========================================

	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		W05_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W05_MONTO_REMANENTE / W05_MONTO_ESTIMADO ) )
	WHERE	K_PRESUPUESTO=@PP_K_PRESUPUESTO
	AND		W05_MONTO_ESTIMADO<>0

	-- //////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> UP PARTIDA PRESUPUESTO
-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PRESUPUESTO_CALCULO_REMANENTE]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_CALCULO_REMANENTE]
GO


CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_CALCULO_REMANENTE]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ==============================================	
	@PP_K_UNIDAD_OPERATIVA				INT,
	@PP_F_OPERACION						DATE,
	@PP_K_RUBRO_PRESUPUESTO				INT
	-- ==============================================
AS
	-- ==============================================

	DECLARE @VP_MES		AS INTEGER
	DECLARE @VP_SEMANA	AS INTEGER
	DECLARE @VP_YYYY	AS INTEGER

	SET	@VP_YYYY =		YEAR(@PP_F_OPERACION) 
	SET	@VP_MES =		MONTH(@PP_F_OPERACION) 

	SELECT	@VP_SEMANA =	N_SEMANA
							FROM	TIEMPO_FECHA
							WHERE	F_TIEMPO_FECHA=@PP_F_OPERACION	

	-- ==============================================	

	DECLARE @VP_K_PRESUPUESTO AS INTEGER	

	EXECUTE [dbo].[PG_RN_PRESUPUESTO_K_X_PARAMETROS]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
														@PP_K_UNIDAD_OPERATIVA,	@VP_YYYY,	@VP_MES,
														@OU_K_PRESUPUESTO=	@VP_K_PRESUPUESTO	OUTPUT		
	-- ==============================================
	
	UPDATE PARTIDA_PRESUPUESTO
	SET		MES_MONTO_REMANENTE = (MES_MONTO_ESTIMADO-MES_MONTO_EN_PROCESO-MES_MONTO_EJERCIDO),
			W01_MONTO_REMANENTE = (W01_MONTO_ESTIMADO-W01_MONTO_EN_PROCESO-W01_MONTO_EJERCIDO),
			W02_MONTO_REMANENTE = (W02_MONTO_ESTIMADO-W02_MONTO_EN_PROCESO-W02_MONTO_EJERCIDO),
			W03_MONTO_REMANENTE = (W03_MONTO_ESTIMADO-W03_MONTO_EN_PROCESO-W03_MONTO_EJERCIDO),
			W04_MONTO_REMANENTE = (W04_MONTO_ESTIMADO-W04_MONTO_EN_PROCESO-W04_MONTO_EJERCIDO),
			W05_MONTO_REMANENTE = (W05_MONTO_ESTIMADO-W05_MONTO_EN_PROCESO-W05_MONTO_EJERCIDO)
	WHERE	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
	AND		K_PRESUPUESTO=@VP_K_PRESUPUESTO
	
	-- ///////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> UP PARTIDA PRESUPUESTO
-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PRESUPUESTO_CALCULO_PORCENTAJE_REMANENTE]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_CALCULO_PORCENTAJE_REMANENTE]
GO

CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_CALCULO_PORCENTAJE_REMANENTE]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ==============================================	
	@PP_K_UNIDAD_OPERATIVA				INT,
	@PP_F_OPERACION						DATE,
	@PP_K_RUBRO_PRESUPUESTO				INT
AS
	-- ==============================================

	DECLARE @VP_MES AS INTEGER
	DECLARE @VP_YYYY AS INTEGER

	SET	@VP_YYYY=YEAR(@PP_F_OPERACION) 
	SET	@VP_MES=MONTH(@PP_F_OPERACION) 
	
	-- ==============================================	

	DECLARE @VP_K_PRESUPUESTO AS INTEGER	

	EXECUTE [dbo].[PG_RN_PRESUPUESTO_K_X_PARAMETROS]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
														@PP_K_UNIDAD_OPERATIVA,	@VP_YYYY,	@VP_MES,
														@OU_K_PRESUPUESTO=	@VP_K_PRESUPUESTO	OUTPUT		
	-- ==============================================
		
	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		MES_PORCENTAJE_REMANENTE = 0
	WHERE	K_PRESUPUESTO=@VP_K_PRESUPUESTO
	AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO

	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		MES_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( MES_MONTO_REMANENTE / MES_MONTO_ESTIMADO ) )
	WHERE	K_PRESUPUESTO=@VP_K_PRESUPUESTO
	AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
	AND		MES_MONTO_ESTIMADO<>0

	-- ==============================================
	
	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		W01_PORCENTAJE_REMANENTE = 0,
			W02_PORCENTAJE_REMANENTE = 0,
			W03_PORCENTAJE_REMANENTE = 0,
			W04_PORCENTAJE_REMANENTE = 0,
			W05_PORCENTAJE_REMANENTE = 0
	WHERE	K_PRESUPUESTO=@VP_K_PRESUPUESTO
	AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO

	-- ////////////////////////////////////////////////////////

	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		W01_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W01_MONTO_REMANENTE / W01_MONTO_ESTIMADO ) )
	WHERE	K_PRESUPUESTO=@VP_K_PRESUPUESTO
	AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
	AND		W01_MONTO_ESTIMADO<>0
	
	-- ========================================

	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		W02_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W02_MONTO_REMANENTE / W02_MONTO_ESTIMADO ) )
	WHERE	K_PRESUPUESTO=@VP_K_PRESUPUESTO
	AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
	AND		W02_MONTO_ESTIMADO<>0

	-- ========================================

	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		W03_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W03_MONTO_REMANENTE / W03_MONTO_ESTIMADO ) )
	WHERE	K_PRESUPUESTO=@VP_K_PRESUPUESTO
	AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
	AND		W03_MONTO_ESTIMADO<>0

	-- ========================================

	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		W04_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W04_MONTO_REMANENTE / W04_MONTO_ESTIMADO ) )
	WHERE	K_PRESUPUESTO=@VP_K_PRESUPUESTO
	AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
	AND		W04_MONTO_ESTIMADO<>0

	-- ========================================

	UPDATE	[PARTIDA_PRESUPUESTO]
	SET		W05_PORCENTAJE_REMANENTE = CONVERT( DECIMAL(19,4), ( W05_MONTO_REMANENTE / W05_MONTO_ESTIMADO ) )
	WHERE	K_PRESUPUESTO=@VP_K_PRESUPUESTO
	AND 	K_RUBRO_PRESUPUESTO=@PP_K_RUBRO_PRESUPUESTO
	AND		W05_MONTO_ESTIMADO<>0	

	-- ///////////////////////////////////////////
GO





-- ///////////////////////////////////////////////////////////////
-- // 
-- ///////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_ESTIMADO_X_K_NIVEL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_ESTIMADO_X_K_NIVEL]
GO

CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_ESTIMADO_X_K_NIVEL]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ==============================
	@PP_K_PRESUPUESTO				INT,
	@PP_K_NIVEL_RUBRO_PRESUPUESTO	INT
AS
	-- ==============================================
	
	SET NOCOUNT ON

	DECLARE	@VP_MES_MONTO_ESTIMADO AS DECIMAL(19,4) = 0
	DECLARE	@VP_W01_MONTO_ESTIMADO AS DECIMAL(19,4) = 0
	DECLARE	@VP_W02_MONTO_ESTIMADO AS DECIMAL(19,4)	= 0
	DECLARE	@VP_W03_MONTO_ESTIMADO AS DECIMAL(19,4)	= 0
	DECLARE	@VP_W04_MONTO_ESTIMADO AS DECIMAL(19,4)	= 0
	DECLARE	@VP_W05_MONTO_ESTIMADO AS DECIMAL(19,4)	= 0

	-- ==============================================										
	
	SELECT	@VP_MES_MONTO_ESTIMADO =	SUM(Q2PAR.MES_MONTO_ESTIMADO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_MES_MONTO_ESTIMADO IS NULL
		SET	@VP_MES_MONTO_ESTIMADO=0

	-- ==============================================										

	SELECT	@VP_W01_MONTO_ESTIMADO =	SUM(Q2PAR.W01_MONTO_ESTIMADO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_W01_MONTO_ESTIMADO IS NULL
		SET	@VP_W01_MONTO_ESTIMADO=0

	-- ==============================================
	
	SELECT	@VP_W02_MONTO_ESTIMADO =	SUM(Q2PAR.W02_MONTO_ESTIMADO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_W02_MONTO_ESTIMADO IS NULL
		SET	@VP_W02_MONTO_ESTIMADO=0

	-- ==============================================
	
	SELECT	@VP_W03_MONTO_ESTIMADO =	SUM(Q2PAR.W03_MONTO_ESTIMADO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_W03_MONTO_ESTIMADO IS NULL
		SET	@VP_W03_MONTO_ESTIMADO=0

	-- ==============================================

	SELECT	@VP_W04_MONTO_ESTIMADO =	SUM(Q2PAR.W04_MONTO_ESTIMADO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_W04_MONTO_ESTIMADO IS NULL
		SET	@VP_W04_MONTO_ESTIMADO=0

	-- ==============================================

	SELECT	@VP_W05_MONTO_ESTIMADO =	SUM(Q2PAR.W05_MONTO_ESTIMADO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO
	
	IF	@VP_W05_MONTO_ESTIMADO IS NULL
		SET	@VP_W05_MONTO_ESTIMADO=0
	
	-- ==============================================




	UPDATE	PARTIDA_PRESUPUESTO
	SET		MES_MONTO_ESTIMADO = @VP_MES_MONTO_ESTIMADO,
			W01_MONTO_ESTIMADO = @VP_W01_MONTO_ESTIMADO,
			W02_MONTO_ESTIMADO = @VP_W02_MONTO_ESTIMADO,
			W03_MONTO_ESTIMADO = @VP_W03_MONTO_ESTIMADO,
			W04_MONTO_ESTIMADO = @VP_W04_MONTO_ESTIMADO,
			W05_MONTO_ESTIMADO = @VP_W05_MONTO_ESTIMADO
	FROM	PARTIDA_PRESUPUESTO AS Q1PAR, RUBRO_PRESUPUESTO AS Q2RUB
	WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
	AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
	AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	SET NOCOUNT OFF
	-- //////////////////////////////////////////////////////////////
GO




-- ///////////////////////////////////////////////////////////////
-- // 
-- ///////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_EJERCIDO_X_K_NIVEL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_EJERCIDO_X_K_NIVEL]
GO

CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_EJERCIDO_X_K_NIVEL]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ==============================
	@PP_K_PRESUPUESTO				INT,
	@PP_K_NIVEL_RUBRO_PRESUPUESTO	INT
AS
	-- ==============================================

	SET NOCOUNT ON

	DECLARE	@VP_MES_MONTO_EJERCIDO AS DECIMAL(19,4) = 0
	DECLARE	@VP_W01_MONTO_EJERCIDO AS DECIMAL(19,4) = 0
	DECLARE	@VP_W02_MONTO_EJERCIDO AS DECIMAL(19,4)	= 0
	DECLARE	@VP_W03_MONTO_EJERCIDO AS DECIMAL(19,4)	= 0
	DECLARE	@VP_W04_MONTO_EJERCIDO AS DECIMAL(19,4)	= 0
	DECLARE	@VP_W05_MONTO_EJERCIDO AS DECIMAL(19,4)	= 0

	SELECT	@VP_MES_MONTO_EJERCIDO =	SUM(Q2PAR.MES_MONTO_EJERCIDO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_MES_MONTO_EJERCIDO IS NULL
		SET	@VP_MES_MONTO_EJERCIDO=0

	-- ==============================================										

	SELECT	@VP_W01_MONTO_EJERCIDO =	SUM(Q2PAR.W01_MONTO_EJERCIDO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_W01_MONTO_EJERCIDO IS NULL
		SET	@VP_W01_MONTO_EJERCIDO=0

	-- ==============================================
	
	SELECT	@VP_W02_MONTO_EJERCIDO =	SUM(Q2PAR.W02_MONTO_EJERCIDO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_W02_MONTO_EJERCIDO IS NULL
		SET	@VP_W02_MONTO_EJERCIDO=0

	-- ==============================================
	
	SELECT	@VP_W03_MONTO_EJERCIDO =	SUM(Q2PAR.W03_MONTO_EJERCIDO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_W03_MONTO_EJERCIDO IS NULL
		SET	@VP_W03_MONTO_EJERCIDO=0

	-- ==============================================

	SELECT	@VP_W04_MONTO_EJERCIDO =	SUM(Q2PAR.W04_MONTO_EJERCIDO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_W04_MONTO_EJERCIDO IS NULL
		SET	@VP_W04_MONTO_EJERCIDO=0

	-- ==============================================

	SELECT	@VP_W05_MONTO_EJERCIDO =	SUM(Q2PAR.W05_MONTO_EJERCIDO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO
	
	IF	@VP_W05_MONTO_EJERCIDO IS NULL
		SET	@VP_W05_MONTO_EJERCIDO=0
	
	-- ==============================================

	UPDATE	PARTIDA_PRESUPUESTO
	SET		MES_MONTO_EJERCIDO = @VP_MES_MONTO_EJERCIDO,
			W01_MONTO_EJERCIDO = @VP_W01_MONTO_EJERCIDO,
			W02_MONTO_EJERCIDO = @VP_W02_MONTO_EJERCIDO,
			W03_MONTO_EJERCIDO = @VP_W03_MONTO_EJERCIDO,
			W04_MONTO_EJERCIDO = @VP_W04_MONTO_EJERCIDO,
			W05_MONTO_EJERCIDO = @VP_W05_MONTO_EJERCIDO
	FROM	PARTIDA_PRESUPUESTO AS Q1PAR, RUBRO_PRESUPUESTO AS Q2RUB
	WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
	AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
	AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO


	SET NOCOUNT OFF
	-- //////////////////////////////////////////////////////////////
GO



-- ///////////////////////////////////////////////////////////////
-- // 
-- ///////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_PROCESO_X_K_NIVEL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_PROCESO_X_K_NIVEL]
GO

CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_PROCESO_X_K_NIVEL]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ==============================
	@PP_K_PRESUPUESTO				INT,
	@PP_K_NIVEL_RUBRO_PRESUPUESTO	INT
AS
	-- ==============================================

	SET NOCOUNT ON

	DECLARE	@VP_MES_MONTO_EN_PROCESO AS DECIMAL(19,4)
	DECLARE	@VP_W01_MONTO_EN_PROCESO AS DECIMAL(19,4)
	DECLARE	@VP_W02_MONTO_EN_PROCESO AS DECIMAL(19,4)
	DECLARE	@VP_W03_MONTO_EN_PROCESO AS DECIMAL(19,4)
	DECLARE	@VP_W04_MONTO_EN_PROCESO AS DECIMAL(19,4)
	DECLARE	@VP_W05_MONTO_EN_PROCESO AS DECIMAL(19,4)

	SELECT	@VP_MES_MONTO_EN_PROCESO =	SUM(Q2PAR.MES_MONTO_EN_PROCESO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_MES_MONTO_EN_PROCESO IS NULL
		SET	@VP_MES_MONTO_EN_PROCESO=0

	-- ==============================================										

	SELECT	@VP_W01_MONTO_EN_PROCESO =	SUM(Q2PAR.W01_MONTO_EN_PROCESO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_W01_MONTO_EN_PROCESO IS NULL
		SET	@VP_W01_MONTO_EN_PROCESO=0

	-- ==============================================
	
	SELECT	@VP_W02_MONTO_EN_PROCESO =	SUM(Q2PAR.W02_MONTO_EN_PROCESO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_W02_MONTO_EN_PROCESO IS NULL
		SET	@VP_W02_MONTO_EN_PROCESO=0

	-- ==============================================
	
	SELECT	@VP_W03_MONTO_EN_PROCESO =	SUM(Q2PAR.W03_MONTO_EN_PROCESO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_W03_MONTO_EN_PROCESO IS NULL
		SET	@VP_W03_MONTO_EN_PROCESO=0

	-- ==============================================

	SELECT	@VP_W04_MONTO_EN_PROCESO =	SUM(Q2PAR.W04_MONTO_EN_PROCESO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO

	IF	@VP_W04_MONTO_EN_PROCESO IS NULL
		SET	@VP_W04_MONTO_EN_PROCESO=0

	-- ==============================================

	SELECT	@VP_W05_MONTO_EN_PROCESO =	SUM(Q2PAR.W05_MONTO_EN_PROCESO)  
										FROM	PARTIDA_PRESUPUESTO AS	Q1PAR,
												PARTIDA_PRESUPUESTO AS	Q2PAR, 
												RUBRO_PRESUPUESTO AS	Q2RUB
										WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
										AND		Q2PAR.K_PRESUPUESTO=Q1PAR.K_PRESUPUESTO
										AND		Q2RUB.K_RUBRO_PADRE=Q1PAR.K_RUBRO_PRESUPUESTO
										AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
										AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO
	
	IF	@VP_W05_MONTO_EN_PROCESO IS NULL
		SET	@VP_W05_MONTO_EN_PROCESO=0
	
	-- ==============================================
	
	UPDATE	PARTIDA_PRESUPUESTO
	SET		MES_MONTO_EN_PROCESO = @VP_MES_MONTO_EN_PROCESO,
			W01_MONTO_EN_PROCESO = @VP_W01_MONTO_EN_PROCESO,
			W02_MONTO_EN_PROCESO = @VP_W02_MONTO_EN_PROCESO,
			W03_MONTO_EN_PROCESO = @VP_W03_MONTO_EN_PROCESO,
			W04_MONTO_EN_PROCESO = @VP_W04_MONTO_EN_PROCESO,
			W05_MONTO_EN_PROCESO = @VP_W05_MONTO_EN_PROCESO
	FROM	PARTIDA_PRESUPUESTO AS Q1PAR, 
			RUBRO_PRESUPUESTO AS Q2RUB
	WHERE	Q1PAR.K_RUBRO_PRESUPUESTO=Q2RUB.K_RUBRO_PRESUPUESTO
	AND		Q1PAR.K_PRESUPUESTO=@PP_K_PRESUPUESTO
	AND 	Q2RUB.K_NIVEL_RUBRO_PRESUPUESTO=@PP_K_NIVEL_RUBRO_PRESUPUESTO


	SET NOCOUNT OFF
	-- //////////////////////////////////////////////////////////////
GO





-- ///////////////////////////////////////////////////////////////
-- // 
-- ///////////////////////////////////////////////////////////////
-- EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_EJERCIDO] 0,0,0,  12345

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_EJERCIDO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_EJERCIDO]
GO


CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_EJERCIDO]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ==============================
	@PP_K_PRESUPUESTO			INT
AS
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_EJERCIDO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PRESUPUESTO, 4
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_EJERCIDO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PRESUPUESTO, 3
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_EJERCIDO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PRESUPUESTO, 2
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_EJERCIDO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PRESUPUESTO, 1

	-- //////////////////////////////////////////////////////////////
GO



-- ///////////////////////////////////////////////////////////////
-- // 
-- ///////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_PROCESO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_PROCESO]
GO


CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_PROCESO]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ==============================
	@PP_K_PRESUPUESTO			INT
AS
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_PROCESO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PRESUPUESTO, 4
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_PROCESO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PRESUPUESTO, 3
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_PROCESO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PRESUPUESTO, 2
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_PROCESO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PRESUPUESTO, 1

	-- //////////////////////////////////////////////////////////////
GO


-- ///////////////////////////////////////////////////////////////
-- // 
-- ///////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_ESTIMADO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_ESTIMADO]
GO


CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_ESTIMADO]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ==============================
	@PP_K_PRESUPUESTO			INT
AS
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_ESTIMADO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PRESUPUESTO, 4
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_ESTIMADO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PRESUPUESTO, 3
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_ESTIMADO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PRESUPUESTO, 2
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_ESTIMADO_X_K_NIVEL]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																				@PP_K_PRESUPUESTO, 1

	-- //////////////////////////////////////////////////////////////
GO



-- ///////////////////////////////////////////////////////////////
-- // 
-- ///////////////////////////////////////////////////////////////
/*

SELECT	D_RUBRO_PRESUPUESTO, O_RUBRO_PRESUPUESTO AS ORDEN, K_NIVEL_RUBRO_PRESUPUESTO AS NIVEL, 
		'///' AS C,
		PARTIDA_PRESUPUESTO.* 
FROM	PARTIDA_PRESUPUESTO, RUBRO_PRESUPUESTO 
WHERE	PARTIDA_PRESUPUESTO.K_RUBRO_PRESUPUESTO=RUBRO_PRESUPUESTO.K_RUBRO_PRESUPUESTO
AND		K_PRESUPUESTO=3001

*/

-- EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION] 0,0,0, 3001

-- EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION] 0,0,0,  12345



IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION]
GO


CREATE PROCEDURE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ==============================
	@PP_K_PRESUPUESTO			INT
AS
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_ESTIMADO]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																	@PP_K_PRESUPUESTO
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_PROCESO]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																	@PP_K_PRESUPUESTO
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION_EJERCIDO]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																	@PP_K_PRESUPUESTO
	-- ==============================================

	EXECUTE [dbo].[PG_UP_PRESUPUESTO_L_RECALCULAR_RESET_0]			@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																	@PP_K_PRESUPUESTO

	-- //////////////////////////////////////////////////////////
GO









-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> 
-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_PR_PRESUPUESTO_SUMARIZAR]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_PR_PRESUPUESTO_SUMARIZAR]
GO


CREATE PROCEDURE [dbo].[PG_PR_PRESUPUESTO_SUMARIZAR]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT
	-- ===========================
AS
	
	DECLARE @VP_MENSAJE		VARCHAR(300)
	
	SET		@VP_MENSAJE		= ''

	-- /////////////////////////////////////////////////////////////////////


	IF @VP_MENSAJE=''
		BEGIN
	
		DECLARE CU_PRESUPUESTO
		CURSOR	LOCAL FOR
				SELECT	K_PRESUPUESTO
				FROM	PRESUPUESTO
				WHERE	L_RECALCULAR=1
				
		-- ========================================

		DECLARE @VP_CU_K_PRESUPUESTO			INT
			
		-- ========================================

		OPEN CU_PRESUPUESTO

		FETCH NEXT FROM CU_PRESUPUESTO INTO @VP_CU_K_PRESUPUESTO
		
		WHILE @@FETCH_STATUS = 0
			BEGIN		
			-- =========================================
			
			EXECUTE [dbo].[PG_UP_PARTIDA_PRESUPUESTO_AGREGACION]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																	@VP_CU_K_PRESUPUESTO	
			-- ========================================
	
		    FETCH NEXT FROM CU_PRESUPUESTO INTO @VP_CU_K_PRESUPUESTO
			
			END

		-- ========================================

		CLOSE		CU_PRESUPUESTO
		DEALLOCATE	CU_PRESUPUESTO
			
		-- ========================================
		END

	-- /////////////////////////////////////////////////////////////////////
	
		
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Recalcular] la [Presupuesto/Totales]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
--		SET		@VP_MENSAJE = @VP_MENSAJE + '[#PR.'+CONVERT(VARCHAR(10),@PP_K_PRESUPUESTO)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'
		
		END
	
--	SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_PRESUPUESTO AS CLAVE
	
	SELECT	@VP_MENSAJE AS MENSAJE, 0 AS CLAVE
	
	-- ////////////////////////////////////////////////////////////////////
GO


-- ////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////
