-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			PLAN PLAN_PRESUPUESTO / GASTOS-PLANTA
-- // OPERACION:		LIBERACION / TABLAS
-- ////////////////////////////////////////////////////////////// 
-- // Autor:			HECTOR A. GONZALEZ DE LA FUENTE
-- // Fecha creación:	15/NOV/2018
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0]
GO



-- //////////////////////////////////////////////////////////////




-- //////////////////////////////////////////////////////////////
-- // DROPs
-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PARTIDA_PLAN_PRESUPUESTO]') AND type in (N'U'))
	DROP TABLE [dbo].[PARTIDA_PLAN_PRESUPUESTO] 
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CALCULO_PARTIDA_PRESUPUESTO]') AND type in (N'U'))
	DROP TABLE [dbo].[CALCULO_PARTIDA_PRESUPUESTO] 
GO





-- ///////////////////////////////////////////////////////////////
-- // CALCULO_PARTIDA_PRESUPUESTO 						
-- ///////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[CALCULO_PARTIDA_PRESUPUESTO] (
	[K_CALCULO_PARTIDA_PRESUPUESTO]		[INT] 			NOT NULL,
	[D_CALCULO_PARTIDA_PRESUPUESTO]		[VARCHAR] (100) NOT NULL,
	[S_CALCULO_PARTIDA_PRESUPUESTO]		[VARCHAR] (10) 	NOT NULL,
	[O_CALCULO_PARTIDA_PRESUPUESTO]		[INT] 			NOT NULL,
	[C_CALCULO_PARTIDA_PRESUPUESTO]		[VARCHAR] (255) NOT NULL,
	[L_CALCULO_PARTIDA_PRESUPUESTO]		[INT] 			NOT NULL
) ON [PRIMARY]
GO

-- //////////////////////////////////////////////////////

ALTER TABLE [dbo].[CALCULO_PARTIDA_PRESUPUESTO]
	ADD CONSTRAINT [PK_CALCULO_PARTIDA_PRESUPUESTO]
		PRIMARY KEY CLUSTERED ([K_CALCULO_PARTIDA_PRESUPUESTO])
GO


CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_CALCULO_PARTIDA_PRESUPUESTO_01_DESCRIPCION] 
	   ON [dbo].[CALCULO_PARTIDA_PRESUPUESTO] ( [D_CALCULO_PARTIDA_PRESUPUESTO] )
GO

-- //////////////////////////////////////////////////////






IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_CALCULO_PARTIDA_PRESUPUESTO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_CALCULO_PARTIDA_PRESUPUESTO]
GO



CREATE PROCEDURE [dbo].[PG_CI_CALCULO_PARTIDA_PRESUPUESTO]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	-- =========================
	@PP_K_CALCULO_PARTIDA_PRESUPUESTO		INT,
	@PP_D_CALCULO_PARTIDA_PRESUPUESTO		VARCHAR(100),
	@PP_S_CALCULO_PARTIDA_PRESUPUESTO		VARCHAR(10),
	@PP_O_CALCULO_PARTIDA_PRESUPUESTO		INT,
	@PP_C_CALCULO_PARTIDA_PRESUPUESTO		VARCHAR(255),
	@PP_L_CALCULO_PARTIDA_PRESUPUESTO		INT
AS
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_CALCULO_PARTIDA_PRESUPUESTO
							FROM	CALCULO_PARTIDA_PRESUPUESTO
							WHERE	K_CALCULO_PARTIDA_PRESUPUESTO=@PP_K_CALCULO_PARTIDA_PRESUPUESTO

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO CALCULO_PARTIDA_PRESUPUESTO
			(	K_CALCULO_PARTIDA_PRESUPUESTO,			D_CALCULO_PARTIDA_PRESUPUESTO, 
				S_CALCULO_PARTIDA_PRESUPUESTO,			O_CALCULO_PARTIDA_PRESUPUESTO,
				C_CALCULO_PARTIDA_PRESUPUESTO,
				L_CALCULO_PARTIDA_PRESUPUESTO			)		
		VALUES	
			(	@PP_K_CALCULO_PARTIDA_PRESUPUESTO,		@PP_D_CALCULO_PARTIDA_PRESUPUESTO,	
				@PP_S_CALCULO_PARTIDA_PRESUPUESTO,		@PP_O_CALCULO_PARTIDA_PRESUPUESTO,
				@PP_C_CALCULO_PARTIDA_PRESUPUESTO,
				@PP_L_CALCULO_PARTIDA_PRESUPUESTO		)
	ELSE
		UPDATE	CALCULO_PARTIDA_PRESUPUESTO
		SET		D_CALCULO_PARTIDA_PRESUPUESTO	= @PP_D_CALCULO_PARTIDA_PRESUPUESTO,	
				S_CALCULO_PARTIDA_PRESUPUESTO	= @PP_S_CALCULO_PARTIDA_PRESUPUESTO,			
				O_CALCULO_PARTIDA_PRESUPUESTO	= @PP_O_CALCULO_PARTIDA_PRESUPUESTO,
				C_CALCULO_PARTIDA_PRESUPUESTO	= @PP_C_CALCULO_PARTIDA_PRESUPUESTO,
				L_CALCULO_PARTIDA_PRESUPUESTO	= @PP_L_CALCULO_PARTIDA_PRESUPUESTO	
		WHERE	K_CALCULO_PARTIDA_PRESUPUESTO=@PP_K_CALCULO_PARTIDA_PRESUPUESTO

	-- ==============================================
GO





-- ///////////////////////////////////////////////////////////////
-- // 
-- ///////////////////////////////////////////////////////////////


EXECUTE [dbo].[PG_CI_CALCULO_PARTIDA_PRESUPUESTO]	0, 0, 0, '',				'', 10, '', 1
EXECUTE [dbo].[PG_CI_CALCULO_PARTIDA_PRESUPUESTO]	0, 0, 1, 'X MES',			'X.MES', 10, '', 1
EXECUTE [dbo].[PG_CI_CALCULO_PARTIDA_PRESUPUESTO]	0, 0, 2, 'X SEMANA',		'X.SEM', 20, '', 1
GO






-- ///////////////////////////////////////////////////////////////
-- // PARTIDA_PLAN_PRESUPUESTO 						
-- ///////////////////////////////////////////////////////////////


CREATE TABLE [dbo].[PARTIDA_PLAN_PRESUPUESTO] (
	[K_PLAN_PRESUPUESTO]			[INT] NOT NULL,
	[K_RUBRO_PRESUPUESTO]			[INT] NOT NULL,	
	[K_CALCULO_PARTIDA_PRESUPUESTO]	[INT] NOT NULL,
	[K_PROGRAMACION_PARTIDA]		[INT] NOT NULL,
	-- ===========================================		
	[MONTO_BASE]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	-- ===========================================		
	[M01_PREVIO]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M02_PREVIO]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M03_PREVIO]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M04_PREVIO]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M05_PREVIO]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M06_PREVIO]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	-- ===========================================	
	[M01_REVISADO]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M02_REVISADO]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M03_REVISADO]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M04_REVISADO]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M05_REVISADO]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M06_REVISADO]			DECIMAL(19,4) NOT NULL DEFAULT 0,
	-- ===========================================	
	[M01_AUTORIZADO]		DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M02_AUTORIZADO]		DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M03_AUTORIZADO]		DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M04_AUTORIZADO]		DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M05_AUTORIZADO]		DECIMAL(19,4) NOT NULL DEFAULT 0,
	[M06_AUTORIZADO]		DECIMAL(19,4) NOT NULL DEFAULT 0
	-- ===========================================	
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////



ALTER TABLE [dbo].[PARTIDA_PLAN_PRESUPUESTO]
	ADD CONSTRAINT [PK_PARTIDA_PLAN_PRESUPUESTO]
		PRIMARY KEY CLUSTERED (	[K_PLAN_PRESUPUESTO], [K_RUBRO_PRESUPUESTO]  )
GO



ALTER TABLE [dbo].[PARTIDA_PLAN_PRESUPUESTO] ADD 
	CONSTRAINT [FK_PARTIDA_PLAN_PRESUPUESTO_01] 
		FOREIGN KEY ([K_PLAN_PRESUPUESTO]) 
		REFERENCES [dbo].[PLAN_PRESUPUESTO] ( [K_PLAN_PRESUPUESTO] ),
	CONSTRAINT [FK_PARTIDA_PLAN_PRESUPUESTO_02] 
		FOREIGN KEY ([K_RUBRO_PRESUPUESTO]) 
		REFERENCES [dbo].[RUBRO_PRESUPUESTO] ( [K_RUBRO_PRESUPUESTO] )
GO




-- //////////////////////////////////////////////////////


ALTER TABLE [dbo].[PARTIDA_PLAN_PRESUPUESTO] 
	ADD		[K_USUARIO_ALTA]	[INT]		NOT NULL,
			[F_ALTA]			[DATETIME]	NOT NULL,
			[K_USUARIO_CAMBIO]	[INT]		NOT NULL,
			[F_CAMBIO]			[DATETIME]	NOT NULL,
			[L_BORRADO]			[INT]		NOT NULL,
			[K_USUARIO_BAJA]	[INT]		NULL,
			[F_BAJA]			[DATETIME]	NULL;
GO


ALTER TABLE [dbo].[PARTIDA_PLAN_PRESUPUESTO] ADD 
	CONSTRAINT [FK_PARTIDA_PLAN_PRESUPUESTO_USUARIO_ALTA]  
		FOREIGN KEY ([K_USUARIO_ALTA]) 
		REFERENCES [dbo].[USUARIO] ([K_USUARIO]),
	CONSTRAINT [FK_PARTIDA_PLAN_PRESUPUESTO_USUARIO_CAMBIO]  
		FOREIGN KEY ([K_USUARIO_CAMBIO]) 
		REFERENCES [dbo].[USUARIO] ([K_USUARIO]),
	CONSTRAINT [FK_PARTIDA_PLAN_PRESUPUESTO_USUARIO_BAJA]  
		FOREIGN KEY ([K_USUARIO_BAJA]) 
		REFERENCES [dbo].[USUARIO] ([K_USUARIO])
GO




-- ////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////
