-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			FLUJO DIARIO
-- // OPERACION:		LIBERACION / TABLAS
-- //////////////////////////////////////////////////////////////
-- // Autor:			HECTOR A. GONZALEZ DE LA FUENTE
-- // Fecha creación:	25/OCT/2018
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0]
GO

-- //////////////////////////////////////////////////////////////



-- //////////////////////////////////////////////////////////////
-- // DROPs
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOVIMIENTO_FLUJO_DIARIO]') AND type in (N'U'))
	DROP TABLE [dbo].[MOVIMIENTO_FLUJO_DIARIO] 
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ESTATUS_MOVIMIENTO_FLUJO_DIARIO]') AND type in (N'U'))
	DROP TABLE [dbo].[ESTATUS_MOVIMIENTO_FLUJO_DIARIO]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TIPO_MOVIMIENTO_FLUJO_DIARIO]') AND type in (N'U'))
	DROP TABLE [dbo].[TIPO_MOVIMIENTO_FLUJO_DIARIO]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLASE_MOVIMIENTO_FLUJO_DIARIO]') AND type in (N'U'))
	DROP TABLE [dbo].[CLASE_MOVIMIENTO_FLUJO_DIARIO]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RUBRO_FLUJO]') AND type in (N'U'))
	DROP TABLE [dbo].[RUBRO_FLUJO]
GO





-- //////////////////////////////////////////////////////////////
-- // RUBRO_FLUJO
-- //////////////////////////////////////////////////////////////


CREATE TABLE [dbo].[RUBRO_FLUJO] (
	[K_RUBRO_FLUJO]	[INT] NOT NULL,
	[D_RUBRO_FLUJO]	[VARCHAR] (100) NOT NULL,
	[S_RUBRO_FLUJO]	[VARCHAR] (10) NOT NULL,
	[O_RUBRO_FLUJO]	[INT] NOT NULL,
	[C_RUBRO_FLUJO]	[VARCHAR] (255) NOT NULL,
	[L_RUBRO_FLUJO]	[INT] NOT NULL
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[RUBRO_FLUJO]
	ADD CONSTRAINT [PK_RUBRO_FLUJO]
		PRIMARY KEY CLUSTERED ([K_RUBRO_FLUJO])
GO


CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_RUBRO_FLUJO_01_DESCRIPCION] 
	   ON [dbo].[RUBRO_FLUJO] ( [D_RUBRO_FLUJO] )
GO


ALTER TABLE [dbo].[RUBRO_FLUJO] ADD 
	CONSTRAINT [FK_RUBRO_FLUJO_01] 
		FOREIGN KEY ( [L_RUBRO_FLUJO] ) 
		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] )
GO


-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_RUBRO_FLUJO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_RUBRO_FLUJO]
GO


CREATE PROCEDURE [dbo].[PG_CI_RUBRO_FLUJO]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	-- ========================================
	@PP_K_RUBRO_FLUJO		INT,
	@PP_D_RUBRO_FLUJO		VARCHAR(100),
	@PP_S_RUBRO_FLUJO		VARCHAR(10),
	@PP_O_RUBRO_FLUJO		INT,
	@PP_C_RUBRO_FLUJO		VARCHAR(255),
	@PP_L_RUBRO_FLUJO		INT
AS
	
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_RUBRO_FLUJO
							FROM	RUBRO_FLUJO
							WHERE	K_RUBRO_FLUJO=@PP_K_RUBRO_FLUJO

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO RUBRO_FLUJO	
			(	K_RUBRO_FLUJO,				D_RUBRO_FLUJO, 
				S_RUBRO_FLUJO,				O_RUBRO_FLUJO,
				C_RUBRO_FLUJO,
				L_RUBRO_FLUJO				)		
		VALUES	
			(	@PP_K_RUBRO_FLUJO,			@PP_D_RUBRO_FLUJO,	
				@PP_S_RUBRO_FLUJO,			@PP_O_RUBRO_FLUJO,
				@PP_C_RUBRO_FLUJO,
				@PP_L_RUBRO_FLUJO			)
	ELSE
		UPDATE	RUBRO_FLUJO
		SET		D_RUBRO_FLUJO	= @PP_D_RUBRO_FLUJO,	
				S_RUBRO_FLUJO	= @PP_S_RUBRO_FLUJO,			
				O_RUBRO_FLUJO	= @PP_O_RUBRO_FLUJO,
				C_RUBRO_FLUJO	= @PP_C_RUBRO_FLUJO,
				L_RUBRO_FLUJO	= @PP_L_RUBRO_FLUJO	
		WHERE	K_RUBRO_FLUJO=@PP_K_RUBRO_FLUJO

	-- =========================================================
GO

-- //////////////////////////////////////////////////////////////

-- SELECT * FROM RUBRO_FLUJO


-- ===============================================
SET NOCOUNT ON
-- ===============================================

EXECUTE [dbo].[PG_CI_RUBRO_FLUJO] 0, 0, 010, 'SALDO INICIAL',		'SINI', 1, '', 1
EXECUTE [dbo].[PG_CI_RUBRO_FLUJO] 0, 0, 020, 'INGRESO',				'INGR', 2, '', 1
EXECUTE [dbo].[PG_CI_RUBRO_FLUJO] 0, 0, 030, 'GAS',					'GAS',  3, '', 1
EXECUTE [dbo].[PG_CI_RUBRO_FLUJO] 0, 0, 040, 'FLETE',				'FLET', 4, '', 1
EXECUTE [dbo].[PG_CI_RUBRO_FLUJO] 0, 0, 050, 'OBLIGACIONES',		'OBLI', 5, '', 1
EXECUTE [dbo].[PG_CI_RUBRO_FLUJO] 0, 0, 060, 'NOMINA',				'NOMI', 5, '', 1
EXECUTE [dbo].[PG_CI_RUBRO_FLUJO] 0, 0, 070, 'CXP',					'CXP',  6, '', 1
EXECUTE [dbo].[PG_CI_RUBRO_FLUJO] 0, 0, 080, 'TRASPASOS',			'TRAS', 7, '', 1
EXECUTE [dbo].[PG_CI_RUBRO_FLUJO] 0, 0, 090, 'GASTO CORPORATIVO',	'GACO', 8, '', 1
EXECUTE [dbo].[PG_CI_RUBRO_FLUJO] 0, 0, 100, 'SALDO FINAL',			'SFIN', 9, '', 1
GO
-- ===============================================
SET NOCOUNT OFF
-- ===============================================







-- ///////////////////////////////////////////////////////////////
-- //					CLASE_MOVIMIENTO_FLUJO_DIARIO
-- ///////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[CLASE_MOVIMIENTO_FLUJO_DIARIO] (
	[K_CLASE_MOVIMIENTO_FLUJO_DIARIO]				[INT] NOT NULL,
	[D_CLASE_MOVIMIENTO_FLUJO_DIARIO]				[VARCHAR] (100) NOT NULL,
	[S_CLASE_MOVIMIENTO_FLUJO_DIARIO]				[VARCHAR] (10) NOT NULL,
	[O_CLASE_MOVIMIENTO_FLUJO_DIARIO]				[INT] NOT NULL,
	[C_CLASE_MOVIMIENTO_FLUJO_DIARIO]				[VARCHAR] (255) NOT NULL,
	[L_CLASE_MOVIMIENTO_FLUJO_DIARIO]				[INT] NOT NULL
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[CLASE_MOVIMIENTO_FLUJO_DIARIO]
	ADD CONSTRAINT [PK_CLASE_MOVIMIENTO_FLUJO_DIARIO]
		PRIMARY KEY CLUSTERED ([K_CLASE_MOVIMIENTO_FLUJO_DIARIO])
GO


CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_CLASE_MOVIMIENTO_FLUJO_DIARIO_01_DESCRIPCION] 
	   ON [dbo].[CLASE_MOVIMIENTO_FLUJO_DIARIO] ( [D_CLASE_MOVIMIENTO_FLUJO_DIARIO] )
GO


ALTER TABLE [dbo].[CLASE_MOVIMIENTO_FLUJO_DIARIO] ADD 
	CONSTRAINT [FK_CLASE_MOVIMIENTO_FLUJO_DIARIO_01] 
		FOREIGN KEY ( [L_CLASE_MOVIMIENTO_FLUJO_DIARIO] ) 
		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] )
GO


-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_CLASE_MOVIMIENTO_FLUJO_DIARIO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_CLASE_MOVIMIENTO_FLUJO_DIARIO]
GO


CREATE PROCEDURE [dbo].[PG_CI_CLASE_MOVIMIENTO_FLUJO_DIARIO]
	@PP_L_DEBUG				INT,
	@PP_K_SISTEMA_EXE		INT,
	-- ========================================
	@PP_K_CLASE_MOVIMIENTO_FLUJO_DIARIO		INT,
	@PP_D_CLASE_MOVIMIENTO_FLUJO_DIARIO		VARCHAR(100),
	@PP_S_CLASE_MOVIMIENTO_FLUJO_DIARIO		VARCHAR(10),
	@PP_O_CLASE_MOVIMIENTO_FLUJO_DIARIO		INT,
	@PP_C_CLASE_MOVIMIENTO_FLUJO_DIARIO		VARCHAR(255),
	@PP_L_CLASE_MOVIMIENTO_FLUJO_DIARIO		INT
AS
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_CLASE_MOVIMIENTO_FLUJO_DIARIO
							FROM	CLASE_MOVIMIENTO_FLUJO_DIARIO
							WHERE	K_CLASE_MOVIMIENTO_FLUJO_DIARIO=@PP_K_CLASE_MOVIMIENTO_FLUJO_DIARIO

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO CLASE_MOVIMIENTO_FLUJO_DIARIO
		(	K_CLASE_MOVIMIENTO_FLUJO_DIARIO,			D_CLASE_MOVIMIENTO_FLUJO_DIARIO, 
			S_CLASE_MOVIMIENTO_FLUJO_DIARIO,			O_CLASE_MOVIMIENTO_FLUJO_DIARIO,
			C_CLASE_MOVIMIENTO_FLUJO_DIARIO,
			L_CLASE_MOVIMIENTO_FLUJO_DIARIO			)		
		VALUES	
		(	@PP_K_CLASE_MOVIMIENTO_FLUJO_DIARIO,		@PP_D_CLASE_MOVIMIENTO_FLUJO_DIARIO,	
			@PP_S_CLASE_MOVIMIENTO_FLUJO_DIARIO,		@PP_O_CLASE_MOVIMIENTO_FLUJO_DIARIO,
			@PP_C_CLASE_MOVIMIENTO_FLUJO_DIARIO,
			@PP_L_CLASE_MOVIMIENTO_FLUJO_DIARIO		)
	ELSE
		UPDATE	CLASE_MOVIMIENTO_FLUJO_DIARIO
		SET		D_CLASE_MOVIMIENTO_FLUJO_DIARIO	= @PP_D_CLASE_MOVIMIENTO_FLUJO_DIARIO,	
				S_CLASE_MOVIMIENTO_FLUJO_DIARIO	= @PP_S_CLASE_MOVIMIENTO_FLUJO_DIARIO,			
				O_CLASE_MOVIMIENTO_FLUJO_DIARIO	= @PP_O_CLASE_MOVIMIENTO_FLUJO_DIARIO,
				C_CLASE_MOVIMIENTO_FLUJO_DIARIO	= @PP_C_CLASE_MOVIMIENTO_FLUJO_DIARIO,
				L_CLASE_MOVIMIENTO_FLUJO_DIARIO	= @PP_L_CLASE_MOVIMIENTO_FLUJO_DIARIO	
		WHERE	K_CLASE_MOVIMIENTO_FLUJO_DIARIO=@PP_K_CLASE_MOVIMIENTO_FLUJO_DIARIO

	-- =========================================================
GO




EXECUTE [dbo].[PG_CI_CLASE_MOVIMIENTO_FLUJO_DIARIO] 0, 0,   1, 'INGRESO',	'ING', 10, '', 1
EXECUTE [dbo].[PG_CI_CLASE_MOVIMIENTO_FLUJO_DIARIO] 0, 0,   0, 'NEUTRO',	'NEU', 20, '', 1
EXECUTE [dbo].[PG_CI_CLASE_MOVIMIENTO_FLUJO_DIARIO] 0, 0,  -1, 'EGRESO',	'EGR', 30, '', 1
GO





-- ///////////////////////////////////////////////////////////////
-- //					TIPO_MOVIMIENTO_FLUJO_DIARIO
-- ///////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[TIPO_MOVIMIENTO_FLUJO_DIARIO] (
	[K_TIPO_MOVIMIENTO_FLUJO_DIARIO]			[INT] NOT NULL,
	[D_TIPO_MOVIMIENTO_FLUJO_DIARIO]			[VARCHAR] (100) NOT NULL,
	[S_TIPO_MOVIMIENTO_FLUJO_DIARIO]			[VARCHAR] (10) NOT NULL,
	[O_TIPO_MOVIMIENTO_FLUJO_DIARIO]			[INT] NOT NULL,
	[C_TIPO_MOVIMIENTO_FLUJO_DIARIO]			[VARCHAR] (255) NOT NULL,
	[L_TIPO_MOVIMIENTO_FLUJO_DIARIO]			[INT] NOT NULL,
	[K_CLASE_MOVIMIENTO_FLUJO_DIARIO]			[INT] NOT NULL
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[TIPO_MOVIMIENTO_FLUJO_DIARIO]
	ADD CONSTRAINT [PK_TIPO_MOVIMIENTO_FLUJO_DIARIO]
		PRIMARY KEY CLUSTERED ([K_TIPO_MOVIMIENTO_FLUJO_DIARIO])
GO


CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_TIPO_MOVIMIENTO_FLUJO_DIARIO_01_DESCRIPCION] 
	   ON [dbo].[TIPO_MOVIMIENTO_FLUJO_DIARIO] ( [D_TIPO_MOVIMIENTO_FLUJO_DIARIO] )
GO


ALTER TABLE [dbo].[TIPO_MOVIMIENTO_FLUJO_DIARIO] ADD 
	CONSTRAINT [FK_TIPO_MOVIMIENTO_FLUJO_DIARIO_01] 
		FOREIGN KEY ( [L_TIPO_MOVIMIENTO_FLUJO_DIARIO] ) 
		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] ),
	CONSTRAINT [FK_TIPO_MOVIMIENTO_FLUJO_DIARIO_02] 
		FOREIGN KEY ( [K_CLASE_MOVIMIENTO_FLUJO_DIARIO] ) 
		REFERENCES [dbo].[CLASE_MOVIMIENTO_FLUJO_DIARIO] ( [K_CLASE_MOVIMIENTO_FLUJO_DIARIO] )
GO



-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_TIPO_MOVIMIENTO_FLUJO_DIARIO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_TIPO_MOVIMIENTO_FLUJO_DIARIO]
GO


CREATE PROCEDURE [dbo].[PG_CI_TIPO_MOVIMIENTO_FLUJO_DIARIO]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	-- ========================================
	@PP_K_TIPO_MOVIMIENTO_FLUJO_DIARIO			INT,
	@PP_D_TIPO_MOVIMIENTO_FLUJO_DIARIO			VARCHAR(100),
	@PP_S_TIPO_MOVIMIENTO_FLUJO_DIARIO			VARCHAR(10),
	@PP_O_TIPO_MOVIMIENTO_FLUJO_DIARIO			INT,
	@PP_C_TIPO_MOVIMIENTO_FLUJO_DIARIO			VARCHAR(255),
	@PP_L_TIPO_MOVIMIENTO_FLUJO_DIARIO			INT,
	@PP_K_CLASE_MOVIMIENTO_FLUJO_DIARIO			INT		
AS
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_TIPO_MOVIMIENTO_FLUJO_DIARIO
							FROM	TIPO_MOVIMIENTO_FLUJO_DIARIO
							WHERE	K_TIPO_MOVIMIENTO_FLUJO_DIARIO=@PP_K_TIPO_MOVIMIENTO_FLUJO_DIARIO

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO TIPO_MOVIMIENTO_FLUJO_DIARIO
			(	K_TIPO_MOVIMIENTO_FLUJO_DIARIO,				D_TIPO_MOVIMIENTO_FLUJO_DIARIO, 
				S_TIPO_MOVIMIENTO_FLUJO_DIARIO,				O_TIPO_MOVIMIENTO_FLUJO_DIARIO,
				C_TIPO_MOVIMIENTO_FLUJO_DIARIO,
				L_TIPO_MOVIMIENTO_FLUJO_DIARIO,
				K_CLASE_MOVIMIENTO_FLUJO_DIARIO				)
		VALUES	
			(	@PP_K_TIPO_MOVIMIENTO_FLUJO_DIARIO,			@PP_D_TIPO_MOVIMIENTO_FLUJO_DIARIO,	
				@PP_S_TIPO_MOVIMIENTO_FLUJO_DIARIO,			@PP_O_TIPO_MOVIMIENTO_FLUJO_DIARIO,
				@PP_C_TIPO_MOVIMIENTO_FLUJO_DIARIO,
				@PP_L_TIPO_MOVIMIENTO_FLUJO_DIARIO,
				@PP_K_CLASE_MOVIMIENTO_FLUJO_DIARIO			)
	ELSE
		UPDATE	TIPO_MOVIMIENTO_FLUJO_DIARIO
		SET		D_TIPO_MOVIMIENTO_FLUJO_DIARIO	= @PP_D_TIPO_MOVIMIENTO_FLUJO_DIARIO,	
				S_TIPO_MOVIMIENTO_FLUJO_DIARIO	= @PP_S_TIPO_MOVIMIENTO_FLUJO_DIARIO,			
				O_TIPO_MOVIMIENTO_FLUJO_DIARIO	= @PP_O_TIPO_MOVIMIENTO_FLUJO_DIARIO,
				C_TIPO_MOVIMIENTO_FLUJO_DIARIO	= @PP_C_TIPO_MOVIMIENTO_FLUJO_DIARIO,
				L_TIPO_MOVIMIENTO_FLUJO_DIARIO	= @PP_L_TIPO_MOVIMIENTO_FLUJO_DIARIO,
				K_CLASE_MOVIMIENTO_FLUJO_DIARIO	= @PP_K_CLASE_MOVIMIENTO_FLUJO_DIARIO	
		WHERE	K_TIPO_MOVIMIENTO_FLUJO_DIARIO=@PP_K_TIPO_MOVIMIENTO_FLUJO_DIARIO

	-- =========================================================
GO

-- //////////////////////////////////////////////////////////////


-- ===============================================
SET NOCOUNT ON
-- =============================================== 


EXECUTE [dbo].[PG_CI_TIPO_MOVIMIENTO_FLUJO_DIARIO] 0, 0,  0, 'TITULO',			'TIT', 0, '', 1,   0
EXECUTE [dbo].[PG_CI_TIPO_MOVIMIENTO_FLUJO_DIARIO] 0, 0,  1, 'INGRESO',			'ING', 1, '', 1,   1
EXECUTE [dbo].[PG_CI_TIPO_MOVIMIENTO_FLUJO_DIARIO] 0, 0,  2, 'EGRESO',			'EGR', 2, '', 1,  -1
EXECUTE [dbo].[PG_CI_TIPO_MOVIMIENTO_FLUJO_DIARIO] 0, 0,  3, 'SUBTOTAL',		'SUB', 3, '', 1,   0
EXECUTE [dbo].[PG_CI_TIPO_MOVIMIENTO_FLUJO_DIARIO] 0, 0,  4, 'SALDO FINAL',		'FIN', 4, '', 1,   0
EXECUTE [dbo].[PG_CI_TIPO_MOVIMIENTO_FLUJO_DIARIO] 0, 0,  5, 'SALDO INICIAL',	'INI', 5, '', 1,   0
GO

-- ===============================================
SET NOCOUNT OFF
-- =============================================== 



-- ///////////////////////////////////////////////////////////////
-- //				ESTATUS_MOVIMIENTO_FLUJO_DIARIO				
-- ///////////////////////////////////////////////////////////////
			

CREATE TABLE [dbo].[ESTATUS_MOVIMIENTO_FLUJO_DIARIO] (
	[K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]				[INT] NOT NULL,
	[D_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]				[VARCHAR] (100) NOT NULL,
	[S_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]				[VARCHAR] (10) NOT NULL,
	[O_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]				[INT] NOT NULL,
	[C_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]				[VARCHAR] (255) NOT NULL,
	[L_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]				[INT] NOT NULL
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[ESTATUS_MOVIMIENTO_FLUJO_DIARIO]
	ADD CONSTRAINT [PK_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]
		PRIMARY KEY CLUSTERED ([K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO])
GO


CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_ESTATUS_MOVIMIENTO_FLUJO_DIARIO_01_DESCRIPCION] 
	   ON [dbo].[ESTATUS_MOVIMIENTO_FLUJO_DIARIO] ( [D_ESTATUS_MOVIMIENTO_FLUJO_DIARIO] )
GO


ALTER TABLE [dbo].[ESTATUS_MOVIMIENTO_FLUJO_DIARIO] ADD 
	CONSTRAINT [FK_ESTATUS_MOVIMIENTO_FLUJO_DIARIO_01] 
		FOREIGN KEY ( [L_ESTATUS_MOVIMIENTO_FLUJO_DIARIO] ) 
		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] )
GO


-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]
GO


CREATE PROCEDURE [dbo].[PG_CI_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	-- ========================================
	@PP_K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO		INT,
	@PP_D_ESTATUS_MOVIMIENTO_FLUJO_DIARIO		VARCHAR(100),
	@PP_S_ESTATUS_MOVIMIENTO_FLUJO_DIARIO		VARCHAR(10),
	@PP_O_ESTATUS_MOVIMIENTO_FLUJO_DIARIO		INT,
	@PP_C_ESTATUS_MOVIMIENTO_FLUJO_DIARIO		VARCHAR(255),
	@PP_L_ESTATUS_MOVIMIENTO_FLUJO_DIARIO		INT
AS
	
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO
							FROM	ESTATUS_MOVIMIENTO_FLUJO_DIARIO
							WHERE	K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO=@PP_K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO ESTATUS_MOVIMIENTO_FLUJO_DIARIO	
			(	K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,				D_ESTATUS_MOVIMIENTO_FLUJO_DIARIO, 
				S_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,				O_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,
				C_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,
				L_ESTATUS_MOVIMIENTO_FLUJO_DIARIO				)		
		VALUES	
			(	@PP_K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,			@PP_D_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,	
				@PP_S_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,			@PP_O_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,
				@PP_C_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,
				@PP_L_ESTATUS_MOVIMIENTO_FLUJO_DIARIO			)
	ELSE
		UPDATE	ESTATUS_MOVIMIENTO_FLUJO_DIARIO
		SET		D_ESTATUS_MOVIMIENTO_FLUJO_DIARIO	= @PP_D_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,	
				S_ESTATUS_MOVIMIENTO_FLUJO_DIARIO	= @PP_S_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,			
				O_ESTATUS_MOVIMIENTO_FLUJO_DIARIO	= @PP_O_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,
				C_ESTATUS_MOVIMIENTO_FLUJO_DIARIO	= @PP_C_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,
				L_ESTATUS_MOVIMIENTO_FLUJO_DIARIO	= @PP_L_ESTATUS_MOVIMIENTO_FLUJO_DIARIO	
		WHERE	K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO=@PP_K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO

	-- =========================================================
GO

-- //////////////////////////////////////////////////////////////




-- ===============================================
SET NOCOUNT ON
-- ===============================================


EXECUTE [dbo].[PG_CI_ESTATUS_MOVIMIENTO_FLUJO_DIARIO] 0, 0, 1, 'REPORTADO',				'RPRTD', 1, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_MOVIMIENTO_FLUJO_DIARIO] 0, 0, 2, 'PAGO POR APLICAR',		'XAPLC', 1, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_MOVIMIENTO_FLUJO_DIARIO] 0, 0, 3, 'APLICADO A COBRANZA',	'APLCD', 1, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_MOVIMIENTO_FLUJO_DIARIO] 0, 0, 4, 'CANCELADO',				'CANCL', 1, '', 1
GO


-- ===============================================
SET NOCOUNT OFF
-- ===============================================




-- ///////////////////////////////////////////////////////////////
-- // MOVIMIENTO_FLUJO_DIARIO					
-- ///////////////////////////////////////////////////////////////
	

CREATE TABLE [dbo].[MOVIMIENTO_FLUJO_DIARIO] (
	-- =============================== CONTROL
	[K_MOVIMIENTO_FLUJO_DIARIO]			[INT] NOT NULL,
	[O_MOVIMIENTO_FLUJO_DIARIO]			[INT] NOT NULL			DEFAULT 999,
	[F_MOVIMIENTO_FLUJO_DIARIO]			[DATE] NOT NULL,
	[K_TIPO_MOVIMIENTO_FLUJO_DIARIO]	[INT] NOT NULL,
	[K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]	[INT] NOT NULL,
	-- =============================== 
	[K_RUBRO_FLUJO]						[INT] NOT NULL,
	[K_RAZON_SOCIAL]					[INT] NOT NULL			DEFAULT 0,
	[K_UNIDAD_OPERATIVA]				[INT] NOT NULL			DEFAULT 0,
	[K_CUENTA_BANCO]					[INT] NOT NULL			DEFAULT 0,
	-- =============================== 
	[BENEFICIARIO]						VARCHAR(100) NOT NULL	DEFAULT '',
	[REFERENCIA_1]						VARCHAR(500) NOT NULL	DEFAULT '',
	[REFERENCIA_2]						VARCHAR(500) NOT NULL	DEFAULT '',
	[MONTO]								DECIMAL(19,4) NOT NULL	DEFAULT 0,
	[CARGO]								DECIMAL(19,4) NOT NULL	DEFAULT 0,
	[ABONO]								DECIMAL(19,4) NOT NULL	DEFAULT 0,
	[SALDO_FINAL]						DECIMAL(19,4) NOT NULL	DEFAULT 0,
	-- =============================== 
	[F_DOCUMENTO]						[DATE] NOT NULL,
	[K_FACTURA_CXP]						[INT] NULL,
	[K_TRASPASO]						[INT] NULL,
	[K_INSTRUCCION]						[INT] NULL,
	-- =============================== 
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////


ALTER TABLE [dbo].[MOVIMIENTO_FLUJO_DIARIO]
	ADD CONSTRAINT [PK_MOVIMIENTO_FLUJO_DIARIO]
		PRIMARY KEY CLUSTERED ([K_MOVIMIENTO_FLUJO_DIARIO])
GO
 

-- //////////////////////////////////////////////////////



ALTER TABLE [dbo].[MOVIMIENTO_FLUJO_DIARIO] ADD 
	CONSTRAINT [FK_MOVIMIENTO_FLUJO_DIARIO_01_RZS] 
		FOREIGN KEY ([K_RAZON_SOCIAL]) 
		REFERENCES [dbo].[RAZON_SOCIAL] ([K_RAZON_SOCIAL]),
	CONSTRAINT [FK_MOVIMIENTO_FLUJO_DIARIO_01_UNO] 
		FOREIGN KEY ([K_UNIDAD_OPERATIVA]) 
		REFERENCES [dbo].[UNIDAD_OPERATIVA] ([K_UNIDAD_OPERATIVA])
GO
	



ALTER TABLE [dbo].[MOVIMIENTO_FLUJO_DIARIO] ADD 
	CONSTRAINT [FK_MOVIMIENTO_FLUJO_DIARIO_02] 
		FOREIGN KEY ([K_TIPO_MOVIMIENTO_FLUJO_DIARIO]) 
		REFERENCES [dbo].[TIPO_MOVIMIENTO_FLUJO_DIARIO] ([K_TIPO_MOVIMIENTO_FLUJO_DIARIO]),
	CONSTRAINT [FK_MOVIMIENTO_FLUJO_DIARIO_03] 
		FOREIGN KEY ([K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]) 
		REFERENCES [dbo].[ESTATUS_MOVIMIENTO_FLUJO_DIARIO] ([K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO]),
	CONSTRAINT [FK_MOVIMIENTO_FLUJO_DIARIO_04] 
		FOREIGN KEY ([K_RUBRO_FLUJO]) 
		REFERENCES [dbo].[RUBRO_FLUJO] ([K_RUBRO_FLUJO])
GO




-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[MOVIMIENTO_FLUJO_DIARIO] 
	ADD		[K_USUARIO_ALTA]				[INT] NOT NULL,
			[F_ALTA]						[DATETIME] NOT NULL,
			[K_USUARIO_CAMBIO]				[INT] NOT NULL,
			[F_CAMBIO]						[DATETIME] NOT NULL,
			[L_BORRADO]						[INT] NOT NULL,
			[K_USUARIO_BAJA]				[INT] NULL,
			[F_BAJA]						[DATETIME] NULL;
GO


ALTER TABLE [dbo].[MOVIMIENTO_FLUJO_DIARIO] ADD 
	CONSTRAINT [FK_MOVIMIENTO_FLUJO_DIARIO_USUARIO_ALTA]  
		FOREIGN KEY ([K_USUARIO_ALTA]) 
		REFERENCES [dbo].[USUARIO] ([K_USUARIO]),
	CONSTRAINT [FK_MOVIMIENTO_FLUJO_DIARIO_USUARIO_CAMBIO]  
		FOREIGN KEY ([K_USUARIO_CAMBIO]) 
		REFERENCES [dbo].[USUARIO] ([K_USUARIO]),
	CONSTRAINT [FK_MOVIMIENTO_FLUJO_DIARIO_USUARIO_BAJA]  
		FOREIGN KEY ([K_USUARIO_BAJA]) 
		REFERENCES [dbo].[USUARIO] ([K_USUARIO])
GO


-- //////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_MOVIMIENTO_FLUJO_DIARIO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_MOVIMIENTO_FLUJO_DIARIO]
GO


CREATE PROCEDURE [dbo].[PG_CI_MOVIMIENTO_FLUJO_DIARIO]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_MOVIMIENTO_FLUJO_DIARIO				INT,
	@PP_D_MOVIMIENTO_FLUJO_DIARIO				VARCHAR(100),
	@PP_K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO		INT,
	@PP_K_RUBRO_FLUJO							INT
AS

	INSERT INTO MOVIMIENTO_FLUJO_DIARIO
		(	K_MOVIMIENTO_FLUJO_DIARIO,				
			K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,		
			K_RUBRO_FLUJO			)
	VALUES	
		(	@PP_K_MOVIMIENTO_FLUJO_DIARIO,			
			@PP_K_ESTATUS_MOVIMIENTO_FLUJO_DIARIO,
			@PP_K_RUBRO_FLUJO		)
	
	-- ==============================================
GO



-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
