-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			
-- // OPERACION:		LIBERACION / TABLAS
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0]
GO

-- //////////////////////////////////////////////////////////////



-- //////////////////////////////////////////////////////////////
-- // DROPs
-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PARAMETRO_SUCURSAL]') AND type in (N'U'))
	DROP TABLE [dbo].[PARAMETRO_SUCURSAL] 
GO


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ESTATUS_PARAMETRO_SUCURSAL]') AND type in (N'U'))
	DROP TABLE [dbo].[ESTATUS_PARAMETRO_SUCURSAL]
GO





-- //////////////////////////////////////////////////////////////
-- // ESTATUS_PARAMETRO_SUCURSAL
-- //////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[ESTATUS_PARAMETRO_SUCURSAL] (
	[K_ESTATUS_PARAMETRO_SUCURSAL]	[INT] NOT NULL,
	[D_ESTATUS_PARAMETRO_SUCURSAL]	[VARCHAR] (100) NOT NULL,
	[S_ESTATUS_PARAMETRO_SUCURSAL]	[VARCHAR] (10) NOT NULL,
	[O_ESTATUS_PARAMETRO_SUCURSAL]	[INT] NOT NULL,
	[C_ESTATUS_PARAMETRO_SUCURSAL]	[VARCHAR] (255) NOT NULL,
	[L_ESTATUS_PARAMETRO_SUCURSAL]	[INT] NOT NULL
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[ESTATUS_PARAMETRO_SUCURSAL]
	ADD CONSTRAINT [PK_ESTATUS_PARAMETRO_SUCURSAL]
		PRIMARY KEY CLUSTERED ([K_ESTATUS_PARAMETRO_SUCURSAL])
GO


CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_ESTATUS_PARAMETRO_SUCURSAL_01_DESCRIPCION] 
	   ON [dbo].[ESTATUS_PARAMETRO_SUCURSAL] ( [D_ESTATUS_PARAMETRO_SUCURSAL] )
GO


-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[ESTATUS_PARAMETRO_SUCURSAL] ADD 
	CONSTRAINT [FK_ESTATUS_PARAMETRO_SUCURSAL_01] 
		FOREIGN KEY ( [L_ESTATUS_PARAMETRO_SUCURSAL] ) 
		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] )
GO


-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_ESTATUS_PARAMETRO_SUCURSAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_ESTATUS_PARAMETRO_SUCURSAL]
GO


CREATE PROCEDURE [dbo].[PG_CI_ESTATUS_PARAMETRO_SUCURSAL]
	@PP_L_DEBUG				INT,
	@PP_K_SISTEMA_EXE		INT,
	-- ========================================
	@PP_K_ESTATUS_PARAMETRO_SUCURSAL		INT,
	@PP_D_ESTATUS_PARAMETRO_SUCURSAL		VARCHAR(100),
	@PP_S_ESTATUS_PARAMETRO_SUCURSAL		VARCHAR(10),
	@PP_O_ESTATUS_PARAMETRO_SUCURSAL		INT,
	@PP_C_ESTATUS_PARAMETRO_SUCURSAL		VARCHAR(255),
	@PP_L_ESTATUS_PARAMETRO_SUCURSAL		INT
AS
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_ESTATUS_PARAMETRO_SUCURSAL
							FROM	ESTATUS_PARAMETRO_SUCURSAL
							WHERE	K_ESTATUS_PARAMETRO_SUCURSAL=@PP_K_ESTATUS_PARAMETRO_SUCURSAL

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO ESTATUS_PARAMETRO_SUCURSAL
			(	K_ESTATUS_PARAMETRO_SUCURSAL,			D_ESTATUS_PARAMETRO_SUCURSAL, 
				S_ESTATUS_PARAMETRO_SUCURSAL,			O_ESTATUS_PARAMETRO_SUCURSAL,
				C_ESTATUS_PARAMETRO_SUCURSAL,
				L_ESTATUS_PARAMETRO_SUCURSAL			)		
		VALUES	
			(	@PP_K_ESTATUS_PARAMETRO_SUCURSAL,		@PP_D_ESTATUS_PARAMETRO_SUCURSAL,	
				@PP_S_ESTATUS_PARAMETRO_SUCURSAL,		@PP_O_ESTATUS_PARAMETRO_SUCURSAL,
				@PP_C_ESTATUS_PARAMETRO_SUCURSAL,
				@PP_L_ESTATUS_PARAMETRO_SUCURSAL		)
	ELSE
		UPDATE	ESTATUS_PARAMETRO_SUCURSAL
		SET		D_ESTATUS_PARAMETRO_SUCURSAL	= @PP_D_ESTATUS_PARAMETRO_SUCURSAL,	
				S_ESTATUS_PARAMETRO_SUCURSAL	= @PP_S_ESTATUS_PARAMETRO_SUCURSAL,			
				O_ESTATUS_PARAMETRO_SUCURSAL	= @PP_O_ESTATUS_PARAMETRO_SUCURSAL,
				C_ESTATUS_PARAMETRO_SUCURSAL	= @PP_C_ESTATUS_PARAMETRO_SUCURSAL,
				L_ESTATUS_PARAMETRO_SUCURSAL	= @PP_L_ESTATUS_PARAMETRO_SUCURSAL	
		WHERE	K_ESTATUS_PARAMETRO_SUCURSAL=@PP_K_ESTATUS_PARAMETRO_SUCURSAL

	-- =========================================================
GO

-- //////////////////////////////////////////////////////////////





-- ===============================================
SET NOCOUNT ON
-- ===============================================

EXECUTE [dbo].[PG_CI_ESTATUS_PARAMETRO_SUCURSAL] 0, 0,  1, 'PREVIO',		'PREV', 1, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_PARAMETRO_SUCURSAL] 0, 0,  2, 'ACTIVO',		'ACTV', 1, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_PARAMETRO_SUCURSAL] 0, 0,  3, 'HISTORICO',		'HIST', 1, '', 1
GO

-- ===============================================
SET NOCOUNT OFF
-- ===============================================





-- ///////////////////////////////////////////////////////////////
-- //				PARAMETRO_SUCURSAL 						
-- ///////////////////////////////////////////////////////////////


CREATE TABLE [dbo].[PARAMETRO_SUCURSAL] (
	[K_PARAMETRO_SUCURSAL]						[INT] NOT NULL,
    [O_PARAMETRO_SUCURSAL]						[INT] NOT NULL,
    [D_PARAMETRO_SUCURSAL]						[VARCHAR] (200) NOT NULL,
	-- ===========================
	[K_UNIDAD_OPERATIVA]		            [INT] NOT NULL,
	[K_ESTATUS_PARAMETRO_SUCURSAL]			[INT] NOT NULL,
--	[K_MM]						            [INT] NOT NULL,
    -- ===================================				  
	[P2016_DTO_DESCUENTO_X_KG]				DECIMAL(19,4) DEFAULT 0,
	[DESCUENTO_CONTADO]						DECIMAL(19,4) DEFAULT 0,
	[DESCUENTO_CREDITO]						DECIMAL(19,4) DEFAULT 0,
	[P2023_PCN]								DECIMAL(19,4) DEFAULT 0,
	-- ===================================
	[VENTA_PORCENTAJE_CONTADO]				DECIMAL(19,4) DEFAULT 0,	-- [P1003_VENTA_KG_CONTADO]		
	[VENTA_PORCENTAJE_CREDITO]				DECIMAL(19,4) DEFAULT 0,	-- [P1004_VENTA_KG_CREDITO]
	[P1012_CARTERA_CYC_INICIAL]				DECIMAL(19,4) DEFAULT 0,
	[P1013_CARTERA_CYC_FINAL]				DECIMAL(19,4) DEFAULT 0,
	[COBRANZA_HOLGURA]						DECIMAL(19,4) DEFAULT 0,
	-- ===================================				  
	[PERFIL_VENTA_CONTADO_1_LUNES]			DECIMAL(19,4) DEFAULT 0,
	[PERFIL_VENTA_CONTADO_2_MARTES]			DECIMAL(19,4) DEFAULT 0,
	[PERFIL_VENTA_CONTADO_3_MIERCOLES]		DECIMAL(19,4) DEFAULT 0,
	[PERFIL_VENTA_CONTADO_4_JUEVES]			DECIMAL(19,4) DEFAULT 0,
	[PERFIL_VENTA_CONTADO_5_VIERNES]		DECIMAL(19,4) DEFAULT 0,
	[PERFIL_VENTA_CONTADO_6_SABADO]			DECIMAL(19,4) DEFAULT 0,
	[PERFIL_VENTA_CONTADO_7_DOMINGO]		DECIMAL(19,4) DEFAULT 0,
	-- ===================================					  
	[PERFIL_VENTA_CREDITO_1_LUNES]			DECIMAL(19,4) DEFAULT 0,
	[PERFIL_VENTA_CREDITO_2_MARTES]			DECIMAL(19,4) DEFAULT 0,
	[PERFIL_VENTA_CREDITO_3_MIERCOLES]		DECIMAL(19,4) DEFAULT 0,
	[PERFIL_VENTA_CREDITO_4_JUEVES]			DECIMAL(19,4) DEFAULT 0,
	[PERFIL_VENTA_CREDITO_5_VIERNES]		DECIMAL(19,4) DEFAULT 0,
	[PERFIL_VENTA_CREDITO_6_SABADO]			DECIMAL(19,4) DEFAULT 0,
	[PERFIL_VENTA_CREDITO_7_DOMINGO]		DECIMAL(19,4) DEFAULT 0,
	-- ===================================					  
	[PERFIL_COBRANZA_1_LUNES]				DECIMAL(19,4) DEFAULT 0,
	[PERFIL_COBRANZA_2_MARTES]				DECIMAL(19,4) DEFAULT 0,
	[PERFIL_COBRANZA_3_MIERCOLES]			DECIMAL(19,4) DEFAULT 0,
	[PERFIL_COBRANZA_4_JUEVES]				DECIMAL(19,4) DEFAULT 0,
	[PERFIL_COBRANZA_5_VIERNES]				DECIMAL(19,4) DEFAULT 0,
	[PERFIL_COBRANZA_6_SABADO]				DECIMAL(19,4) DEFAULT 0,
	[PERFIL_COBRANZA_7_DOMINGO]				DECIMAL(19,4) DEFAULT 0
) ON [PRIMARY]
GO

-- //////////////////////////////////////////////////////

ALTER TABLE [dbo].[PARAMETRO_SUCURSAL]
	ADD CONSTRAINT [PARAMETRO_SUCURSAL_00]
		PRIMARY KEY CLUSTERED ( [K_PARAMETRO_SUCURSAL] )
GO




-- //////////////////////////////////////////////////////

ALTER TABLE [dbo].[PARAMETRO_SUCURSAL] ADD 
	CONSTRAINT [FK_PARAMETRO_SUCURSAL_01] 
		FOREIGN KEY ([K_UNIDAD_OPERATIVA]) 
		REFERENCES [dbo].[UNIDAD_OPERATIVA] ([K_UNIDAD_OPERATIVA]),
    CONSTRAINT [FK_PARAMETRO_SUCURSAL_02] 
		FOREIGN KEY ([K_ESTATUS_PARAMETRO_SUCURSAL]) 
		REFERENCES [dbo].[ESTATUS_PARAMETRO_SUCURSAL] ([K_ESTATUS_PARAMETRO_SUCURSAL])
GO



-- //////////////////////////////////////////////////////



ALTER TABLE [dbo].[PARAMETRO_SUCURSAL] 
	ADD		[K_USUARIO_ALTA]	[INT]		NOT NULL,
			[F_ALTA]			[DATETIME]	NOT NULL,
			[K_USUARIO_CAMBIO]	[INT]		NOT NULL,
			[F_CAMBIO]			[DATETIME]	NOT NULL,
			[L_BORRADO]			[INT]		NOT NULL,
			[K_USUARIO_BAJA]	[INT]		NULL,
			[F_BAJA]			[DATETIME]	NULL;
GO


ALTER TABLE [dbo].[PARAMETRO_SUCURSAL] ADD 
	CONSTRAINT [FK_PARAMETRO_SUCURSAL_USUARIO_ALTA]  
		FOREIGN KEY ([K_USUARIO_ALTA]) 
		REFERENCES [dbo].[USUARIO] ([K_USUARIO]),
	CONSTRAINT [FK_PARAMETRO_SUCURSAL_USUARIO_CAMBIO]  
		FOREIGN KEY ([K_USUARIO_CAMBIO]) 
		REFERENCES [dbo].[USUARIO] ([K_USUARIO]),
	CONSTRAINT [FK_PARAMETRO_SUCURSAL_USUARIO_BAJA]  
		FOREIGN KEY ([K_USUARIO_BAJA]) 
		REFERENCES [dbo].[USUARIO] ([K_USUARIO])
GO





-- ////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////
