-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			
-- // OPERACION:		LIBERACION // STORED PROCEDURE
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0] 
GO

-- //////////////////////////////////////////////////////////////




-- //////////////////////////////////////////////////////////////

--//////////////////////////////////////////////////////////////


-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////
--											PARAMETRO_SUCURSAL			
-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- ////////////////////////////////////////////////////////////////////////////////////////////////////////////


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LI_PARAMETRO_SUCURSAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE	[dbo].[PG_LI_PARAMETRO_SUCURSAL]
GO


CREATE PROCEDURE [dbo].[PG_LI_PARAMETRO_SUCURSAL]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================		
	@PP_D_PARAMETRO_SUCURSAL			VARCHAR(200),
	@PP_K_ZONA_UO						INT,
	@PP_K_UNIDAD_OPERATIVA				INT,
	@PP_K_ESTATUS_PARAMETRO_SUCURSAL	INT
	
	-- ===========================
AS

	DECLARE @VP_MENSAJE		VARCHAR(300)
	
	DECLARE @VP_L_APLICAR_MAX_ROWS	INT=1

	SET		@VP_MENSAJE		= ''
	
	-- ///////////////////////////////////////////

	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_DATA_ACCESO_SELECT]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
													1, -- @PP_K_DATA_SISTEMA,	
													@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	-- ///////////////////////////////////////////

	IF @VP_MENSAJE=''
		BEGIN
	
		DECLARE @VP_INT_NUMERO_REGISTROS	INT
	
		EXECUTE [dbo].[PG_SK_CONFIGURACION_LISTADO_MAX_ROWS_PESADO_GET]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE,
																			@VP_L_APLICAR_MAX_ROWS,		
																			@OU_MAXROWS = @VP_INT_NUMERO_REGISTROS		OUTPUT
		-- =========================================		

		DECLARE @VP_K_FOLIO		INT

		EXECUTE [dbo].[PG_RN_OBTENER_ID_X_REFERENCIA]	@PP_D_PARAMETRO_SUCURSAL, 
														@OU_K_ELEMENTO = @VP_K_FOLIO	OUTPUT
		-- =========================================
		IF @VP_MENSAJE<>''
			SET @VP_INT_NUMERO_REGISTROS=0

		SELECT	TOP (@VP_INT_NUMERO_REGISTROS)
				PARAMETRO_SUCURSAL.*, 
				PARAMETRO_SUCURSAL.COBRANZA_HOLGURA*100 COBRANZA_HOLGURA_0_100,
				PARAMETRO_SUCURSAL.VENTA_PORCENTAJE_CONTADO*100 VENTA_PORCENTAJE_CONTADO_0_100,
				PARAMETRO_SUCURSAL.VENTA_PORCENTAJE_CREDITO*100 VENTA_PORCENTAJE_CREDITO_0_100,
				PARAMETRO_SUCURSAL.DESCUENTO_CREDITO*100 DESCUENTO_CREDITO_0_100,
				PARAMETRO_SUCURSAL.DESCUENTO_CONTADO*100 DESCUENTO_CONTADO_0_100,
				D_UNIDAD_OPERATIVA,				S_UNIDAD_OPERATIVA,
				D_ZONA_UO,						S_ZONA_UO,
				D_ESTATUS_PARAMETRO_SUCURSAL,	S_ESTATUS_PARAMETRO_SUCURSAL,
				USUARIO.D_USUARIO AS 'D_USUARIO_CAMBIO'
		FROM	PARAMETRO_SUCURSAL, VI_UNIDAD_OPERATIVA_CATALOGOS,
				ESTATUS_PARAMETRO_SUCURSAL,USUARIO
		WHERE	PARAMETRO_SUCURSAL.K_USUARIO_CAMBIO=USUARIO.K_USUARIO 
		AND		PARAMETRO_SUCURSAL.K_UNIDAD_OPERATIVA=VI_UNIDAD_OPERATIVA_CATALOGOS.VI_K_UNIDAD_OPERATIVA 
		AND		PARAMETRO_SUCURSAL.K_ESTATUS_PARAMETRO_SUCURSAL=ESTATUS_PARAMETRO_SUCURSAL.K_ESTATUS_PARAMETRO_SUCURSAL 
		AND		PARAMETRO_SUCURSAL.L_BORRADO=0
		AND		(	D_UNIDAD_OPERATIVA	LIKE '%'+@PP_D_PARAMETRO_SUCURSAL+'%' 
					OR	K_PARAMETRO_SUCURSAL=@VP_K_FOLIO	)	
		AND		(	@PP_K_UNIDAD_OPERATIVA=-1 
					OR  PARAMETRO_SUCURSAL.K_UNIDAD_OPERATIVA = @PP_K_UNIDAD_OPERATIVA)	
		AND		(	@PP_K_ZONA_UO=-1 
					OR  VI_UNIDAD_OPERATIVA_CATALOGOS.VI_K_ZONA_UO = @PP_K_ZONA_UO)			
		AND		(	@PP_K_ESTATUS_PARAMETRO_SUCURSAL=-1 
					OR  PARAMETRO_SUCURSAL.K_ESTATUS_PARAMETRO_SUCURSAL = @PP_K_ESTATUS_PARAMETRO_SUCURSAL)		
		ORDER BY O_PARAMETRO_SUCURSAL

				
		END	

	-- ////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_SK_PARAMETRO_SUCURSAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_SK_PARAMETRO_SUCURSAL]
GO


CREATE PROCEDURE [dbo].[PG_SK_PARAMETRO_SUCURSAL]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_K_PARAMETRO_SUCURSAL	INT
AS

	DECLARE @VP_MENSAJE		VARCHAR(300)
	
	SET		@VP_MENSAJE		= ''
	
	-- ///////////////////////////////////////////

	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_DATA_ACCESO_SEEK]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
													1, -- @PP_K_DATA_SISTEMA,	
													@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	-- ///////////////////////////////////////////

	IF @VP_MENSAJE=''
		BEGIN
	
		SELECT	PARAMETRO_SUCURSAL.*,
				PARAMETRO_SUCURSAL.COBRANZA_HOLGURA*100 COBRANZA_HOLGURA_0_100,
				PARAMETRO_SUCURSAL.VENTA_PORCENTAJE_CONTADO*100 VENTA_PORCENTAJE_CONTADO_0_100,
				PARAMETRO_SUCURSAL.VENTA_PORCENTAJE_CREDITO*100 VENTA_PORCENTAJE_CREDITO_0_100,
				PARAMETRO_SUCURSAL.DESCUENTO_CREDITO*100 DESCUENTO_CREDITO_0_100,
				PARAMETRO_SUCURSAL.DESCUENTO_CONTADO*100 DESCUENTO_CONTADO_0_100
		FROM	PARAMETRO_SUCURSAL
		WHERE	PARAMETRO_SUCURSAL.L_BORRADO=0
		AND		PARAMETRO_SUCURSAL.K_PARAMETRO_SUCURSAL=@PP_K_PARAMETRO_SUCURSAL
		
		END
	-- ////////////////////////////////////////////////
GO


	
-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> INSERT
-- //////////////////////////////////////////////////////////////P

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_IN_PARAMETRO_SUCURSAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_IN_PARAMETRO_SUCURSAL]
GO


CREATE PROCEDURE [dbo].[PG_IN_PARAMETRO_SUCURSAL]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,
	-- ===========================	
	@PP_D_PARAMETRO_SUCURSAL			VARCHAR(300),
	-- ===========================	
    @PP_K_UNIDAD_OPERATIVA				INT,
	@PP_K_ESTATUS_PARAMETRO_SUCURSAL	INT,
	-- ===========================	
	@PP_P2016_DTO_DESCUENTO_X_KG			DECIMAL(19, 4),
	@PP_DESCUENTO_CONTADO_0_100				DECIMAL(19, 4),
	@PP_DESCUENTO_CREDITO_0_100				DECIMAL(19, 4),
	@PP_P2023_PCN							DECIMAL(19, 4),
	@PP_VENTA_PORCENTAJE_CONTADO_0_100		DECIMAL(19, 4),
	@PP_VENTA_PORCENTAJE_CREDITO_0_100		DECIMAL(19, 4),
	@PP_P1012_CARTERA_CYC_INICIAL			DECIMAL(19, 4),
	@PP_P1013_CARTERA_CYC_FINAL				DECIMAL(19, 4),
	@PP_COBRANZA_HOLGURA_0_100				DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_1_LUNES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_2_MARTES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_3_MIERCOLES	DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_4_JUEVES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_5_VIERNES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_6_SABADO		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_7_DOMINGO		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_1_LUNES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_2_MARTES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_3_MIERCOLES	DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_4_JUEVES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_5_VIERNES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_6_SABADO		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_7_DOMINGO		DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_1_LUNES				DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_2_MARTES			DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_3_MIERCOLES			DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_4_JUEVES			DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_5_VIERNES			DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_6_SABADO			DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_7_DOMINGO			DECIMAL(19, 4)	
AS			

	DECLARE @VP_MENSAJE		VARCHAR(300)
	
	SET		@VP_MENSAJE		= ''
	
	-- /////////////////////////////////////////////////////////////////////
	DECLARE @VP_K_PARAMETRO_SUCURSAL	INT = 0

	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_PARAMETRO_SUCURSAL_INSERT]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
															@VP_K_PARAMETRO_SUCURSAL, 
															@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	
	-- /////////////////////////////////////////////////////////////////////
	IF @VP_MENSAJE=''
		BEGIN
	
		EXECUTE [dbo].[PG_SK_CATALOGO_K_MAX_GET]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE,
													'PARAMETRO_SUCURSAL', 
													@OU_K_TABLA_DISPONIBLE = @VP_K_PARAMETRO_SUCURSAL		OUTPUT
		-- //////////////////////////////////////////////////////////////			

		DECLARE @VP_COBRANZA_HOLGURA AS DECIMAL(19,4)
		SELECT @VP_COBRANZA_HOLGURA=@PP_COBRANZA_HOLGURA_0_100/100

		-- //////////////////////////////////////////////////////////////

		DECLARE @VP_VENTA_PORCENTAJE_CONTADO AS DECIMAL(19,4)
		SELECT @VP_VENTA_PORCENTAJE_CONTADO=@PP_VENTA_PORCENTAJE_CONTADO_0_100/100

		-- //////////////////////////////////////////////////////////////

		DECLARE @VP_VENTA_PORCENTAJE_CREDITO AS DECIMAL(19,4)
		SELECT @VP_VENTA_PORCENTAJE_CREDITO=@PP_VENTA_PORCENTAJE_CREDITO_0_100/100

		-- //////////////////////////////////////////////////////////////		
		
		DECLARE @VP_DESCUENTO_CONTADO AS DECIMAL(19,4)
		SELECT @VP_DESCUENTO_CONTADO=@PP_DESCUENTO_CONTADO_0_100/100

		-- //////////////////////////////////////////////////////////////			
		
		DECLARE @VP_DESCUENTO_CREDITO AS DECIMAL(19,4)
		SELECT @VP_DESCUENTO_CREDITO=@PP_DESCUENTO_CREDITO_0_100/100

		-- //////////////////////////////////////////////////////////////		

		INSERT INTO PARAMETRO_SUCURSAL
			(	[K_PARAMETRO_SUCURSAL],[O_PARAMETRO_SUCURSAL],
                [D_PARAMETRO_SUCURSAL],[K_UNIDAD_OPERATIVA],
				[K_ESTATUS_PARAMETRO_SUCURSAL],
				[P2016_DTO_DESCUENTO_X_KG],
				[DESCUENTO_CONTADO],[DESCUENTO_CREDITO],[P2023_PCN],
				[VENTA_PORCENTAJE_CONTADO],[VENTA_PORCENTAJE_CREDITO],
				[P1012_CARTERA_CYC_INICIAL],[P1013_CARTERA_CYC_FINAL],
				[COBRANZA_HOLGURA],[PERFIL_VENTA_CONTADO_1_LUNES],
				[PERFIL_VENTA_CONTADO_2_MARTES],[PERFIL_VENTA_CONTADO_3_MIERCOLES],
				[PERFIL_VENTA_CONTADO_4_JUEVES],[PERFIL_VENTA_CONTADO_5_VIERNES],
				[PERFIL_VENTA_CONTADO_6_SABADO],[PERFIL_VENTA_CONTADO_7_DOMINGO],
				[PERFIL_VENTA_CREDITO_1_LUNES],[PERFIL_VENTA_CREDITO_2_MARTES],
				[PERFIL_VENTA_CREDITO_3_MIERCOLES],[PERFIL_VENTA_CREDITO_4_JUEVES],
				[PERFIL_VENTA_CREDITO_5_VIERNES],[PERFIL_VENTA_CREDITO_6_SABADO],
				[PERFIL_VENTA_CREDITO_7_DOMINGO],[PERFIL_COBRANZA_1_LUNES],
				[PERFIL_COBRANZA_2_MARTES],[PERFIL_COBRANZA_3_MIERCOLES],
				[PERFIL_COBRANZA_4_JUEVES],[PERFIL_COBRANZA_5_VIERNES],
				[PERFIL_COBRANZA_6_SABADO],[PERFIL_COBRANZA_7_DOMINGO],
				-- ===========================
				[K_USUARIO_ALTA],[F_ALTA],[K_USUARIO_CAMBIO],[F_CAMBIO],
				[L_BORRADO],[K_USUARIO_BAJA],[F_BAJA]  )
		VALUES	
			(	
				@VP_K_PARAMETRO_SUCURSAL,10,
				@PP_D_PARAMETRO_SUCURSAL,@PP_K_UNIDAD_OPERATIVA,
				@PP_K_ESTATUS_PARAMETRO_SUCURSAL,
				@PP_P2016_DTO_DESCUENTO_X_KG,
				@VP_DESCUENTO_CONTADO,@VP_DESCUENTO_CREDITO,@PP_P2023_PCN,
				@VP_VENTA_PORCENTAJE_CONTADO,@VP_VENTA_PORCENTAJE_CREDITO,
				@PP_P1012_CARTERA_CYC_INICIAL,@PP_P1013_CARTERA_CYC_FINAL,
				@VP_COBRANZA_HOLGURA,@PP_PERFIL_VENTA_CONTADO_1_LUNES,
				@PP_PERFIL_VENTA_CONTADO_2_MARTES,@PP_PERFIL_VENTA_CONTADO_3_MIERCOLES,
				@PP_PERFIL_VENTA_CONTADO_4_JUEVES,@PP_PERFIL_VENTA_CONTADO_5_VIERNES,
				@PP_PERFIL_VENTA_CONTADO_6_SABADO,@PP_PERFIL_VENTA_CONTADO_7_DOMINGO,
				@PP_PERFIL_VENTA_CREDITO_1_LUNES,@PP_PERFIL_VENTA_CREDITO_2_MARTES,
				@PP_PERFIL_VENTA_CREDITO_3_MIERCOLES,@PP_PERFIL_VENTA_CREDITO_4_JUEVES,
				@PP_PERFIL_VENTA_CREDITO_5_VIERNES,@PP_PERFIL_VENTA_CREDITO_6_SABADO,
				@PP_PERFIL_VENTA_CREDITO_7_DOMINGO,@PP_PERFIL_COBRANZA_1_LUNES,
				@PP_PERFIL_COBRANZA_2_MARTES,@PP_PERFIL_COBRANZA_3_MIERCOLES,
				@PP_PERFIL_COBRANZA_4_JUEVES,@PP_PERFIL_COBRANZA_5_VIERNES,
				@PP_PERFIL_COBRANZA_6_SABADO,@PP_PERFIL_COBRANZA_7_DOMINGO,
				-- ===========================
				@PP_K_USUARIO_ACCION, GETDATE(), @PP_K_USUARIO_ACCION, GETDATE(),
				0, NULL, NULL )
		END
	-- /////////////////////////////////////////////////////////////////////
			
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Crear] el [PARAMETRO_SUCURSAL]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#Em.'+CONVERT(VARCHAR(10),@VP_K_PARAMETRO_SUCURSAL)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'

		END
	ELSE
		SELECT	@VP_MENSAJE AS MENSAJE, @VP_K_PARAMETRO_SUCURSAL AS CLAVE
		
	-- /////////////////////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> ACTUALIZAR / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_UP_PARAMETRO_SUCURSAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_UP_PARAMETRO_SUCURSAL]
GO

CREATE PROCEDURE [dbo].[PG_UP_PARAMETRO_SUCURSAL]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_PARAMETRO_SUCURSAL				INT,
	@PP_D_PARAMETRO_SUCURSAL				VARCHAR(200),
	-- ===========================	
	@PP_K_UNIDAD_OPERATIVA					INT,
	@PP_K_ESTATUS_PARAMETRO_SUCURSAL		INT,
	-- ===========================	
	@PP_P2016_DTO_DESCUENTO_X_KG			DECIMAL(19, 4),
	@PP_DESCUENTO_CONTADO_0_100				DECIMAL(19, 4),
	@PP_DESCUENTO_CREDITO_0_100				DECIMAL(19, 4),
	@PP_P2023_PCN							DECIMAL(19, 4),
	@PP_VENTA_PORCENTAJE_CONTADO_0_100		DECIMAL(19, 4),
	@PP_VENTA_PORCENTAJE_CREDITO_0_100		DECIMAL(19, 4),
	@PP_P1012_CARTERA_CYC_INICIAL			DECIMAL(19, 4),
	@PP_P1013_CARTERA_CYC_FINAL				DECIMAL(19, 4),
	@PP_COBRANZA_HOLGURA_0_100				DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_1_LUNES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_2_MARTES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_3_MIERCOLES	DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_4_JUEVES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_5_VIERNES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_6_SABADO		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CONTADO_7_DOMINGO		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_1_LUNES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_2_MARTES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_3_MIERCOLES	DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_4_JUEVES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_5_VIERNES		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_6_SABADO		DECIMAL(19, 4),
	@PP_PERFIL_VENTA_CREDITO_7_DOMINGO		DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_1_LUNES				DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_2_MARTES			DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_3_MIERCOLES			DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_4_JUEVES			DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_5_VIERNES			DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_6_SABADO			DECIMAL(19, 4),
	@PP_PERFIL_COBRANZA_7_DOMINGO			DECIMAL(19, 4)
AS			

	DECLARE @VP_MENSAJE		VARCHAR(300)
		
	SET		@VP_MENSAJE		= ''

	-- /////////////////////////////////////////////////////////////////////

	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_PARAMETRO_SUCURSAL_UPDATE]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
															@PP_K_PARAMETRO_SUCURSAL, 
															@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT

	-- /////////////////////////////////////////////////////////////////////

	DECLARE @VP_COBRANZA_HOLGURA AS DECIMAL(19,4)
	SELECT @VP_COBRANZA_HOLGURA=@PP_COBRANZA_HOLGURA_0_100/100

	-- /////////////////////////////////////////////////////////////////////

	DECLARE @VP_VENTA_PORCENTAJE_CONTADO AS DECIMAL(19,4)
	SELECT @VP_VENTA_PORCENTAJE_CONTADO=@PP_VENTA_PORCENTAJE_CONTADO_0_100/100

	-- //////////////////////////////////////////////////////////////

	DECLARE @VP_VENTA_PORCENTAJE_CREDITO AS DECIMAL(19,4)
	SELECT @VP_VENTA_PORCENTAJE_CREDITO=@PP_VENTA_PORCENTAJE_CREDITO_0_100/100

	-- //////////////////////////////////////////////////////////////			

	DECLARE @VP_DESCUENTO_CONTADO AS DECIMAL(19,4)
	SELECT @VP_DESCUENTO_CONTADO=@PP_DESCUENTO_CONTADO_0_100/100

	-- //////////////////////////////////////////////////////////////			
		
	DECLARE @VP_DESCUENTO_CREDITO AS DECIMAL(19,4)
	SELECT @VP_DESCUENTO_CREDITO=@PP_DESCUENTO_CREDITO_0_100/100

	-- //////////////////////////////////////////////////////////////		

	IF @VP_MENSAJE=''
		BEGIN
		UPDATE	PARAMETRO_SUCURSAL
		SET
				[K_UNIDAD_OPERATIVA]				=	@PP_K_UNIDAD_OPERATIVA,
				[K_ESTATUS_PARAMETRO_SUCURSAL]		=	@PP_K_ESTATUS_PARAMETRO_SUCURSAL,
				-- ===========================	
                [O_PARAMETRO_SUCURSAL]				=   10,
                [D_PARAMETRO_SUCURSAL]				=   @PP_D_PARAMETRO_SUCURSAL,
                [P2016_DTO_DESCUENTO_X_KG]			=	@PP_P2016_DTO_DESCUENTO_X_KG,		
				[DESCUENTO_CONTADO]					=	@VP_DESCUENTO_CONTADO,				
				[DESCUENTO_CREDITO]					=	@VP_DESCUENTO_CREDITO,				
				[P2023_PCN]							=	@PP_P2023_PCN,						
				[VENTA_PORCENTAJE_CONTADO]			=	@VP_VENTA_PORCENTAJE_CONTADO,			
				[VENTA_PORCENTAJE_CREDITO]			=	@VP_VENTA_PORCENTAJE_CREDITO,			
				[P1012_CARTERA_CYC_INICIAL]			=	@PP_P1012_CARTERA_CYC_INICIAL,		
				[P1013_CARTERA_CYC_FINAL]			=	@PP_P1013_CARTERA_CYC_FINAL,		
				[COBRANZA_HOLGURA]					=	@VP_COBRANZA_HOLGURA,				
				[PERFIL_VENTA_CONTADO_1_LUNES]		=	@PP_PERFIL_VENTA_CONTADO_1_LUNES,	
				[PERFIL_VENTA_CONTADO_2_MARTES]		=	@PP_PERFIL_VENTA_CONTADO_2_MARTES,	
				[PERFIL_VENTA_CONTADO_3_MIERCOLES]	=	@PP_PERFIL_VENTA_CONTADO_3_MIERCOLES,
				[PERFIL_VENTA_CONTADO_4_JUEVES]		=	@PP_PERFIL_VENTA_CONTADO_4_JUEVES,	
				[PERFIL_VENTA_CONTADO_5_VIERNES]	=	@PP_PERFIL_VENTA_CONTADO_5_VIERNES,	
				[PERFIL_VENTA_CONTADO_6_SABADO]		=	@PP_PERFIL_VENTA_CONTADO_6_SABADO,	
				[PERFIL_VENTA_CONTADO_7_DOMINGO]	=	@PP_PERFIL_VENTA_CONTADO_7_DOMINGO,	
				[PERFIL_VENTA_CREDITO_1_LUNES]		=	@PP_PERFIL_VENTA_CREDITO_1_LUNES,	
				[PERFIL_VENTA_CREDITO_2_MARTES]		=	@PP_PERFIL_VENTA_CREDITO_2_MARTES,	
				[PERFIL_VENTA_CREDITO_3_MIERCOLES]	=	@PP_PERFIL_VENTA_CREDITO_3_MIERCOLES,
				[PERFIL_VENTA_CREDITO_4_JUEVES]		=	@PP_PERFIL_VENTA_CREDITO_4_JUEVES,	
				[PERFIL_VENTA_CREDITO_5_VIERNES]	=	@PP_PERFIL_VENTA_CREDITO_5_VIERNES,	
				[PERFIL_VENTA_CREDITO_6_SABADO]		=	@PP_PERFIL_VENTA_CREDITO_6_SABADO,	
				[PERFIL_VENTA_CREDITO_7_DOMINGO]	=	@PP_PERFIL_VENTA_CREDITO_7_DOMINGO,	
				[PERFIL_COBRANZA_1_LUNES]			=	@PP_PERFIL_COBRANZA_1_LUNES,		
				[PERFIL_COBRANZA_2_MARTES]			=	@PP_PERFIL_COBRANZA_2_MARTES,		
				[PERFIL_COBRANZA_3_MIERCOLES]		=	@PP_PERFIL_COBRANZA_3_MIERCOLES,		
				[PERFIL_COBRANZA_4_JUEVES]			=	@PP_PERFIL_COBRANZA_4_JUEVES,		
				[PERFIL_COBRANZA_5_VIERNES]			=	@PP_PERFIL_COBRANZA_5_VIERNES,		
				[PERFIL_COBRANZA_6_SABADO]			=	@PP_PERFIL_COBRANZA_6_SABADO,		
				[PERFIL_COBRANZA_7_DOMINGO]			=	@PP_PERFIL_COBRANZA_7_DOMINGO,
                -- ===========================

				-- ====================
				[F_CAMBIO]			=	GETDATE(), 
				[K_USUARIO_CAMBIO]	=	@PP_K_USUARIO_ACCION
		WHERE	PARAMETRO_SUCURSAL.K_PARAMETRO_SUCURSAL=@PP_K_PARAMETRO_SUCURSAL
		END

	-- /////////////////////////////////////////////////////////////////////
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Actualizar] el [PARAMETRO_SUCURSAL]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#Em.'+CONVERT(VARCHAR(10),@PP_K_PARAMETRO_SUCURSAL)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'

		SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_PARAMETRO_SUCURSAL AS CLAVE
		
		END
	ELSE
		SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_PARAMETRO_SUCURSAL AS CLAVE

	-- //////////////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> DELETE / FICHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_DL_PARAMETRO_SUCURSAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_DL_PARAMETRO_SUCURSAL]
GO


CREATE PROCEDURE [dbo].[PG_DL_PARAMETRO_SUCURSAL]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_K_PARAMETRO_SUCURSAL		INT

AS

	DECLARE @VP_MENSAJE		VARCHAR(300)
	
	SET		@VP_MENSAJE		= ''

	--/////////////////////////////////////////////////////////////

	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_PARAMETRO_SUCURSAL_DELETE]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
																@PP_K_PARAMETRO_SUCURSAL, 
																@OU_RESULTADO_VALIDACION = @VP_MENSAJE	OUTPUT

	--////////////////////////////////////////////////////////////

	IF @VP_MENSAJE=''
		BEGIN
		
	--	DELETE
	--	FROM	DOCUMENTO_D0M4
	--	WHERE	DOCUMENTO_D0M4.K_DOCUMENTO_D0M4=@PP_K_DOCUMENTO_D0M4

		UPDATE	PARAMETRO_SUCURSAL
		SET		
				[L_BORRADO]		 =	1,
				-- ====================
				[F_BAJA]		 	=	GETDATE(), 
				[K_USUARIO_BAJA] 	=	@PP_K_USUARIO_ACCION
		WHERE	K_PARAMETRO_SUCURSAL	=	@PP_K_PARAMETRO_SUCURSAL
	
		END

	-- /////////////////////////////////////////////////////////////////////
	
	IF @VP_MENSAJE<>''
		BEGIN
		
		SET		@VP_MENSAJE = 'No es posible [Borrar] la [PARAMETRO_SUCURSAL]: ' + @VP_MENSAJE 
		SET		@VP_MENSAJE = @VP_MENSAJE + ' ( '
		SET		@VP_MENSAJE = @VP_MENSAJE + '[#Em.'+CONVERT(VARCHAR(10),@PP_K_PARAMETRO_SUCURSAL)+']'
		SET		@VP_MENSAJE = @VP_MENSAJE + ' )'

		SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_PARAMETRO_SUCURSAL AS CLAVE
		
		END
	ELSE
		SELECT	@VP_MENSAJE AS MENSAJE, @PP_K_PARAMETRO_SUCURSAL AS CLAVE

	-- /////////////////////////////////////////////////////////////////////
GO

-- //////////////////////////////////////////////////////////////

-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> COMBO PERFILES
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_LD_PARAMETRO_SUCURSAL]') AND type in (N'P', N'PC'))
	DROP PROCEDURE	[dbo].[PG_LD_PARAMETRO_SUCURSAL]
GO


CREATE PROCEDURE [dbo].[PG_LD_PARAMETRO_SUCURSAL]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================	
	@PP_K_UNIDAD_OPERATIVA			INT	
	-- ===========================
AS

	DECLARE @VP_MENSAJE		VARCHAR(300)
	
	DECLARE @VP_L_APLICAR_MAX_ROWS	INT=1

	SET		@VP_MENSAJE		= ''
	
	-- ///////////////////////////////////////////

	IF @VP_MENSAJE=''
		EXECUTE [dbo].[PG_RN_DATA_ACCESO_SELECT]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
													1, -- @PP_K_DATA_SISTEMA,	
													@OU_RESULTADO_VALIDACION = @VP_MENSAJE		OUTPUT
	-- ///////////////////////////////////////////

	IF @VP_MENSAJE=''
		BEGIN
	
		DECLARE @VP_INT_NUMERO_REGISTROS	INT
	
		EXECUTE [dbo].[PG_SK_CONFIGURACION_LISTADO_MAX_ROWS_PESADO_GET]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE,
																			@VP_L_APLICAR_MAX_ROWS,		
																			@OU_MAXROWS = @VP_INT_NUMERO_REGISTROS		OUTPUT
		-- =========================================		

		SELECT	TOP (@VP_INT_NUMERO_REGISTROS)
				PARAMETRO_SUCURSAL.K_PARAMETRO_SUCURSAL 'K_COMBOBOX', 
				UNIDAD_OPERATIVA.D_UNIDAD_OPERATIVA							
				+' '
				+PARAMETRO_SUCURSAL.D_PARAMETRO_SUCURSAL 'D_COMBOBOX'
		FROM	PARAMETRO_SUCURSAL,UNIDAD_OPERATIVA,USUARIO
		WHERE	PARAMETRO_SUCURSAL.K_USUARIO_CAMBIO=USUARIO.K_USUARIO 
		AND		PARAMETRO_SUCURSAL.K_UNIDAD_OPERATIVA=UNIDAD_OPERATIVA.K_UNIDAD_OPERATIVA 		
		AND		PARAMETRO_SUCURSAL.L_BORRADO=0
		AND		PARAMETRO_SUCURSAL.K_UNIDAD_OPERATIVA=@PP_K_UNIDAD_OPERATIVA
		ORDER BY O_PARAMETRO_SUCURSAL


				
		END
	ELSE
		BEGIN	-- RESTO ES PARA QUE GENERA LA ENTREGA DE LOS ENCABEZADOS / SIN REGISTROS

	SELECT	TOP (@VP_INT_NUMERO_REGISTROS)
				PARAMETRO_SUCURSAL.K_PARAMETRO_SUCURSAL 'K_COMBOBOX', 
				UNIDAD_OPERATIVA.D_UNIDAD_OPERATIVA					
				+' '
				+PARAMETRO_SUCURSAL.D_PARAMETRO_SUCURSAL 'D_COMBOBOX'
				FROM	PARAMETRO_SUCURSAL,UNIDAD_OPERATIVA,USUARIO
				WHERE	PARAMETRO_SUCURSAL.K_USUARIO_CAMBIO=USUARIO.K_USUARIO 
				AND		PARAMETRO_SUCURSAL.K_UNIDAD_OPERATIVA=UNIDAD_OPERATIVA.K_UNIDAD_OPERATIVA 		
				AND		PARAMETRO_SUCURSAL.L_BORRADO=0

				AND		PARAMETRO_SUCURSAL.K_PARAMETRO_SUCURSAL<0

		END

	-- ////////////////////////////////////////////////
GO





-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////



