-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			LIBRO_INGRESOS
-- // OPERACION:		CARGA INICIAL / QA
-- //////////////////////////////////////////////////////////////
-- // Autor:			HECTOR A. GONZALEZ DE LA FUENTE
-- // Fecha creación:	11/OCT/2018
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0] 
GO


-- //////////////////////////////////////////////////////////////
-- SELECT * FROM LIBRO_INGRESOS

-- SELECT * FROM ACTA_INGRESOS



-- //////////////////////////////////////////////////////
-- // SP // CARGA INICIAL
-- //////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_LIBRO_INGRESOS]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_LIBRO_INGRESOS]
GO


CREATE PROCEDURE [dbo].[PG_CI_LIBRO_INGRESOS]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_K_TIPO_LIBRO_INGRESOS		INT,	
	@PP_F_OPERACION					DATE,
	@PP_K_UNIDAD_OPERATIVA			INT,
	@PP_FACTOR						DECIMAL(19,4), 
	@PP_VENTA_DIARIA				DECIMAL(19,4),		
	@PP_PORCENTAJE					DECIMAL(19,4)
AS			

	DECLARE @VP_K_LIBRO_INGRESOS				INT = 0
	
	EXECUTE [dbo].[PG_SK_CATALOGO_K_MAX_GET]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE,
												'LIBRO_INGRESOS', 
												@OU_K_TABLA_DISPONIBLE = @VP_K_LIBRO_INGRESOS			OUTPUT	
	-- ==================================

	DECLARE @PP_K_ESTATUS_LIBRO_INGRESOS	INT = 1
	DECLARE @PP_K_CONCEPTO_LIBRO_INGRESOS	INT = 2
	DECLARE @PP_L_CAPTURA_MANUAL			INT = 0 
	DECLARE @PP_C_LIBRO_INGRESOS			[VARCHAR] (255) = ''

	-- ==============================================

	DECLARE @VP_FACTOR_ALEATORIO				DECIMAL(19,8) 

--	SET		@VP_FACTOR_ALEATORIO = 			 ( (RAND(convert(varbinary, newid())) * ((K_PLAN_GASTO+CONVERT(INT,(K_RUBRO_PRESUPUESTO/10))) % @VP_AMPLITUD))/100 ) - 0.10 )

	SET		@VP_FACTOR_ALEATORIO = 			 (RAND(convert(varbinary, newid())))  

	SET		@VP_FACTOR_ALEATORIO = 			 @VP_FACTOR_ALEATORIO/5
	
	SET		@VP_FACTOR_ALEATORIO = 			 @VP_FACTOR_ALEATORIO + 0.75
	
	SET		@VP_FACTOR_ALEATORIO = 			 @VP_FACTOR_ALEATORIO * @PP_PORCENTAJE

--	PRINT	@PP_PORCENTAJE

	DECLARE @PP_MONTO						DECIMAL(19,4) 

	SET @PP_MONTO = ( @PP_FACTOR * @PP_VENTA_DIARIA * @VP_FACTOR_ALEATORIO )

	-- ==============================================

	DECLARE @VP_K_CLASE_LIBRO_INGRESOS		INT = 0

	SELECT	@VP_K_CLASE_LIBRO_INGRESOS =	K_CLASE_LIBRO_INGRESOS 
											FROM	TIPO_LIBRO_INGRESOS 
											WHERE	K_TIPO_LIBRO_INGRESOS=@PP_K_TIPO_LIBRO_INGRESOS

	DECLARE @VP_MONTO_APLICAR	DECIMAL(19,4)

	SET		@VP_MONTO_APLICAR = ( @PP_MONTO*@VP_K_CLASE_LIBRO_INGRESOS )
			
	-- ==============================================

	INSERT INTO LIBRO_INGRESOS
		(	[K_LIBRO_INGRESOS],
			[K_TIPO_LIBRO_INGRESOS], [K_ESTATUS_LIBRO_INGRESOS],
			[K_CONCEPTO_LIBRO_INGRESOS], [L_CAPTURA_MANUAL], 
			-- ============================================
			[F_OPERACION], 
			[K_UNIDAD_OPERATIVA], [C_LIBRO_INGRESOS],
			[MONTO], [MONTO_APLICAR],			
			-- ============================================
			[K_USUARIO_ALTA], [F_ALTA], 
			[K_USUARIO_CAMBIO], [F_CAMBIO],
			[L_BORRADO], [K_USUARIO_BAJA], [F_BAJA]  )
	VALUES	
		(	@VP_K_LIBRO_INGRESOS,
			@PP_K_TIPO_LIBRO_INGRESOS, @PP_K_ESTATUS_LIBRO_INGRESOS,
			@PP_K_CONCEPTO_LIBRO_INGRESOS, @PP_L_CAPTURA_MANUAL,
			-- ============================================
			@PP_F_OPERACION, 
			@PP_K_UNIDAD_OPERATIVA, @PP_C_LIBRO_INGRESOS,
			CONVERT(DECIMAL(19,2),@PP_MONTO), CONVERT(DECIMAL(19,2),@VP_MONTO_APLICAR), 		
			-- ============================================
			@PP_K_USUARIO_ACCION, GETDATE(), 
			@PP_K_USUARIO_ACCION, GETDATE(),
			0, NULL, NULL )

	-- ==============================================
	
	EXECUTE [dbo].[PG_UP_ACTA_INGRESOS]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
											@PP_K_TIPO_LIBRO_INGRESOS, @PP_K_ESTATUS_LIBRO_INGRESOS, @PP_K_CONCEPTO_LIBRO_INGRESOS,
											@PP_L_CAPTURA_MANUAL, @PP_K_UNIDAD_OPERATIVA, @PP_C_LIBRO_INGRESOS,
											@PP_MONTO, @PP_F_OPERACION		

	-- ==============================================
GO


-- //////////////////////////////////////////////////////
-- // SP // CARGA INICIAL
-- //////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO]
GO


CREATE PROCEDURE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_USUARIO_ACCION			INT,
	-- ===========================
	@PP_F_INICIO					DATE,
	@PP_F_FIN						DATE,
	@PP_K_UNIDAD_OPERATIVA			INT
AS		
	-- ==============================================

	PRINT '-- ///////////////////////////////////////// @PP_K_UNIDAD_OPERATIVA = '+CONVERT(VARCHAR(100),@PP_K_UNIDAD_OPERATIVA)

	-- ==============================================

	DECLARE @VP_VENTA_DIARIA	DECIMAL(19,4) = 800000 
	
	DECLARE @VP_FACTOR			DECIMAL(19,4) 

	SELECT	@VP_FACTOR =		FACTOR			
								FROM	QA_DATA_UNIDAD_OPERATIVA
								WHERE	@PP_K_UNIDAD_OPERATIVA=@PP_K_UNIDAD_OPERATIVA

	-- ==============================================
	
	DECLARE @VP_K_TIPO_LIBRO_INGRESOS	INT

	DECLARE CU_TIEMPO_FECHA	
		CURSOR	LOCAL FOR
				SELECT	F_TIEMPO_FECHA
				FROM	TIEMPO_FECHA
				WHERE	( @PP_F_INICIO<=F_TIEMPO_FECHA	AND	 F_TIEMPO_FECHA<=@PP_F_FIN  )
					
		-- ========================================

		DECLARE @VP_CU_F_TIEMPO_FECHA		DATE
			
		-- ========================================

		OPEN CU_TIEMPO_FECHA

		FETCH NEXT FROM CU_TIEMPO_FECHA INTO @VP_CU_F_TIEMPO_FECHA
		
		WHILE @@FETCH_STATUS = 0
			BEGIN		
			-- =========================================
			-- K_TIPO_LIBRO_INGRESOS	D_TIPO_LIBRO_INGRESOS
			-- 101	VENTA CONTADO
			SET @VP_K_TIPO_LIBRO_INGRESOS = 101
		
			EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
													@VP_K_TIPO_LIBRO_INGRESOS, @VP_CU_F_TIEMPO_FECHA, @PP_K_UNIDAD_OPERATIVA,
													@VP_FACTOR, @VP_VENTA_DIARIA, 0.70
			-- 102	VENTA CREDITO
			SET @VP_K_TIPO_LIBRO_INGRESOS = 102

			EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
													@VP_K_TIPO_LIBRO_INGRESOS, @VP_CU_F_TIEMPO_FECHA, @PP_K_UNIDAD_OPERATIVA,
													@VP_FACTOR, @VP_VENTA_DIARIA, 0.30

			-- 103	COBRANZA
			SET @VP_K_TIPO_LIBRO_INGRESOS = 103

			EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
													@VP_K_TIPO_LIBRO_INGRESOS, @VP_CU_F_TIEMPO_FECHA, @PP_K_UNIDAD_OPERATIVA,
													@VP_FACTOR, @VP_VENTA_DIARIA, 0.25

			-- 104	VENTA VALE/GAS
			SET @VP_K_TIPO_LIBRO_INGRESOS = 104

			EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
													@VP_K_TIPO_LIBRO_INGRESOS, @VP_CU_F_TIEMPO_FECHA, @PP_K_UNIDAD_OPERATIVA,
													@VP_FACTOR, @VP_VENTA_DIARIA, 0.15

			-- 105	VENTA ANTICIPADA
			SET @VP_K_TIPO_LIBRO_INGRESOS = 105

			EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
													@VP_K_TIPO_LIBRO_INGRESOS, @VP_CU_F_TIEMPO_FECHA, @PP_K_UNIDAD_OPERATIVA,
													@VP_FACTOR, @VP_VENTA_DIARIA, 0.10

			-- 201	AJUSTE ERROR / VENTA CONTADO
			SET @VP_K_TIPO_LIBRO_INGRESOS = 201

			EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
													@VP_K_TIPO_LIBRO_INGRESOS, @VP_CU_F_TIEMPO_FECHA, @PP_K_UNIDAD_OPERATIVA,
													@VP_FACTOR, @VP_VENTA_DIARIA, 0.15

			-- 202	AJUSTE ERROR / VENTA CREDITO
			SET @VP_K_TIPO_LIBRO_INGRESOS = 202

			EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
													@VP_K_TIPO_LIBRO_INGRESOS, @VP_CU_F_TIEMPO_FECHA, @PP_K_UNIDAD_OPERATIVA,
													@VP_FACTOR, @VP_VENTA_DIARIA, 0.15

			-- 203	AJUSTE ERROR / COBRANZA
			SET @VP_K_TIPO_LIBRO_INGRESOS = 203

			EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
													@VP_K_TIPO_LIBRO_INGRESOS, @VP_CU_F_TIEMPO_FECHA, @PP_K_UNIDAD_OPERATIVA,
													@VP_FACTOR, @VP_VENTA_DIARIA, 0.07

			-- 204	AJUSTE ERROR / VENTA VALE/GAS
			SET @VP_K_TIPO_LIBRO_INGRESOS = 204

			EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
													@VP_K_TIPO_LIBRO_INGRESOS, @VP_CU_F_TIEMPO_FECHA, @PP_K_UNIDAD_OPERATIVA,
													@VP_FACTOR, @VP_VENTA_DIARIA, 0.05

			-- 205	AJUSTE ERROR / VENTA ANTICIPADA
			SET @VP_K_TIPO_LIBRO_INGRESOS = 205

			EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,
													@VP_K_TIPO_LIBRO_INGRESOS, @VP_CU_F_TIEMPO_FECHA, @PP_K_UNIDAD_OPERATIVA,
													@VP_FACTOR, @VP_VENTA_DIARIA, 0.03
			
			

			-- ========================================

		    FETCH NEXT FROM CU_TIEMPO_FECHA INTO @VP_CU_F_TIEMPO_FECHA
			
			END

		-- ========================================

		CLOSE		CU_TIEMPO_FECHA
		DEALLOCATE	CU_TIEMPO_FECHA

		-- /////////////////////////////////////////////////////////////////////

	-- ==============================================
GO



-- //////////////////////////////////////////////////////
-- // SP // CARGA INICIAL
-- //////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LIBRO_INGRESOS]') AND type in (N'U'))
	DELETE	FROM [dbo].[LIBRO_INGRESOS] 
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ACTA_INGRESOS]') AND type in (N'U'))
	DELETE	FROM [dbo].[ACTA_INGRESOS] 
GO

-- //////////////////////////////////////////////////////

-- ===============================================
SET NOCOUNT ON
-- ===============================================
-- SELECT * FROM LIBRO_INGRESOS


DECLARE @VP_F_INICIO	DATE = '2018-11-01' 
DECLARE @VP_F_FIN		DATE = '2018-11-30'


-- ================== LIBRO_INGRESOS

EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 75	-- GUADALAJARA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 77	-- TESISTAN
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 68	-- AGUASCALIENTES
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 51	-- LA LAJA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 54	-- OCOTLAN
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 53	-- TEPATITLAN
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 52	-- TLAJOMULCO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 55	-- YAHUALICA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 30	-- ZAPOPAN
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 70	-- MAMEME GAS
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 80	-- GUANAJUATO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 57	-- AUTLAN
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 56	-- CD. GUZMAN
GO


/*
-- =========================================================
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 35	-- ENSENADA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 34	-- MEXICALI
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 69	-- SAN QUINTIN
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 33	-- TIJUANA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 18	-- GAS CHAPULTEPEC
GO

-- =========================================================
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 20	-- GAS Y SERVICIO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 21	-- GASOMATICO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 23	-- MEXICANA DE GAS
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 13	-- UNIGAS MATRIZ
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 24	-- UNIGAS TLAHUAC
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 26	-- TEHUACAN
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 31	-- HIDROGAS ACAPULCO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 32	-- MORELOS
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 81	-- GTM-TEPEJI-CDMX
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 28	-- QUERETARO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 27	-- SAN LUIS POTOSI
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 19	-- GAS TOMZA DE PUEBLA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 25	-- UNIGAS TOLUCA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 29	-- GAS URIBE
GO

-- =========================================================

EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 11	-- ASCENSION
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 16	-- BENITO JUAREZ
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 8	-- FLORES MAGON
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 84	-- MATRIZ
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 5	-- PALOMAS
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 6	-- PUEBLO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 3	-- BIOGAS
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 1	-- GUADALUPE
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 14	-- BUENAVENTURA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 15	-- CAMARGO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 83	-- CUAUHTEMOC
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 9	-- DELICIAS
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 7	-- HIDRO I
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 17	-- HIDRO II
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 4	-- LAS SIERRA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 2	-- PARRAL
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 12	-- OJINAGA
GO

-- =========================================================


--EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 0	-- Sin Asignar

--EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 72	-- HIDALGO

-- =========================================================

EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 38	-- AGUAPRIETA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 44	-- CABORCA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 39	-- CANANEA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 50	-- FUNDICION
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 46	-- GUAYMAS
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 36	-- HERMOSILLO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 40	-- NACO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 41	-- NACOZARI
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 48	-- NAVOJOA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 42	-- NOGALES
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 47	-- OBREGON
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 45	-- PUERTO PEÑASCO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 49	-- SAN LUIS RIO COLORADO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 43	-- SANTA ANA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 37	-- URES
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 76	-- CULIACAN
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 73	-- MOCHIS
GO

-- =========================================================

EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 71	-- PLAYA DEL CARMEN
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 59	-- CANCUN
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 61	-- CHETUMAL
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 60	-- COZUMEL
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 64	-- CAMPECHE
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 65	-- CD. DEL CARMEN
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 82	-- KM80
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 62	-- MERIDA
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 67	-- PROGRESO
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 63	-- TICUL
EXECUTE [dbo].[PG_CI_LIBRO_INGRESOS_X_RANGO] 0,0,0, @VP_F_INICIO, @VP_F_FIN, 66	-- MINATITLAN
GO

*/

-- ===============================================
SET NOCOUNT OFF
-- ===============================================







-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
