-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			TRASPASO
-- // OPERACION:		LIBERACION / TABLAS
-- //////////////////////////////////////////////////////////////
-- // Autor:			DANIEL PORTILLO	ROMERO
-- // Fecha creación:	19/SEP/2018
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0]
GO

-- //////////////////////////////////////////////////////////////
-- SELECT * FROM TRASPASO



-- //////////////////////////////////////////////////////////////
-- // DROPs
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRASPASO]') AND type in (N'U'))
	DROP TABLE [dbo].[TRASPASO] 
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CONCEPTO_TRASPASO]') AND type in (N'U'))
	DROP TABLE [dbo].[CONCEPTO_TRASPASO]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ESTATUS_TRASPASO]') AND type in (N'U'))
	DROP TABLE [dbo].[ESTATUS_TRASPASO]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TIPO_TRASPASO]') AND type in (N'U'))
	DROP TABLE [dbo].[TIPO_TRASPASO]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLASE_TRASPASO]') AND type in (N'U'))
	DROP TABLE [dbo].[CLASE_TRASPASO]
GO





-- ///////////////////////////////////////////////////////////////
-- //						CLASE_TRASPASO						
-- ///////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[CLASE_TRASPASO] (
	[K_CLASE_TRASPASO]			INT NOT NULL,
	[D_CLASE_TRASPASO]			VARCHAR (100) NOT NULL,
	[S_CLASE_TRASPASO]			VARCHAR (10) NOT NULL,
	[O_CLASE_TRASPASO]			INT NOT NULL,
	[C_CLASE_TRASPASO]			VARCHAR (255) NOT NULL,
	[L_CLASE_TRASPASO]			INT NOT NULL
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[CLASE_TRASPASO]
	ADD CONSTRAINT [PK_CLASE_TRASPASO]
		PRIMARY KEY CLUSTERED ([K_CLASE_TRASPASO])
GO


CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_CLASE_TRASPASO_01_DESCRIPCION] 
	   ON [dbo].[CLASE_TRASPASO] ( [D_CLASE_TRASPASO] )
GO


ALTER TABLE [dbo].[CLASE_TRASPASO] ADD 
	CONSTRAINT [FK_CLASE_TRASPASO_01] 
		FOREIGN KEY ( [L_CLASE_TRASPASO] ) 
		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] )
GO


-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_CLASE_TRASPASO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_CLASE_TRASPASO]
GO


CREATE PROCEDURE [dbo].[PG_CI_CLASE_TRASPASO]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	-- ========================================
	@PP_K_CLASE_TRASPASO			INT,
	@PP_D_CLASE_TRASPASO			VARCHAR(100),
	@PP_S_CLASE_TRASPASO			VARCHAR(10),
	@PP_O_CLASE_TRASPASO			INT,
	@PP_C_CLASE_TRASPASO			VARCHAR(255),
	@PP_L_CLASE_TRASPASO			INT
AS
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_CLASE_TRASPASO
							FROM	CLASE_TRASPASO
							WHERE	K_CLASE_TRASPASO=@PP_K_CLASE_TRASPASO

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO CLASE_TRASPASO
			(	K_CLASE_TRASPASO,			D_CLASE_TRASPASO, 
				S_CLASE_TRASPASO,			O_CLASE_TRASPASO,
				C_CLASE_TRASPASO,
				L_CLASE_TRASPASO			)		
		VALUES	
			(	@PP_K_CLASE_TRASPASO,		@PP_D_CLASE_TRASPASO,	
				@PP_S_CLASE_TRASPASO,		@PP_O_CLASE_TRASPASO,
				@PP_C_CLASE_TRASPASO,
				@PP_L_CLASE_TRASPASO		)
	ELSE
		UPDATE	CLASE_TRASPASO
		SET		D_CLASE_TRASPASO	= @PP_D_CLASE_TRASPASO,	
				S_CLASE_TRASPASO	= @PP_S_CLASE_TRASPASO,			
				O_CLASE_TRASPASO	= @PP_O_CLASE_TRASPASO,
				C_CLASE_TRASPASO	= @PP_C_CLASE_TRASPASO,
				L_CLASE_TRASPASO	= @PP_L_CLASE_TRASPASO	
		WHERE	K_CLASE_TRASPASO=@PP_K_CLASE_TRASPASO

	-- =========================================================
GO


EXECUTE [dbo].[PG_CI_CLASE_TRASPASO] 0, 0, -1, 'CARGO',  'CRGO', 1, '', 1
EXECUTE [dbo].[PG_CI_CLASE_TRASPASO] 0, 0,  0, 'NEUTRO', 'NEUT', 1, '', 1
EXECUTE [dbo].[PG_CI_CLASE_TRASPASO] 0, 0,  1, 'ABONO',  'ABNO', 1, '', 1
GO




-- ///////////////////////////////////////////////////////////////
-- //					TIPO_TRASPASO						
-- ///////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[TIPO_TRASPASO] (
	[K_TIPO_TRASPASO]			INT NOT NULL,
	[D_TIPO_TRASPASO]			VARCHAR (100) NOT NULL,
	[S_TIPO_TRASPASO]			VARCHAR (10) NOT NULL,
	[O_TIPO_TRASPASO]			INT NOT NULL,
	[C_TIPO_TRASPASO]			VARCHAR (255) NOT NULL,
	[L_TIPO_TRASPASO]			INT NOT NULL,
	[K_CLASE_TRASPASO]			INT NOT NULL
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[TIPO_TRASPASO]
	ADD CONSTRAINT [PK_TIPO_TRASPASO]
		PRIMARY KEY CLUSTERED ([K_TIPO_TRASPASO])
GO


CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_TIPO_TRASPASO_01_DESCRIPCION] 
	   ON [dbo].[TIPO_TRASPASO] ( [D_TIPO_TRASPASO] )
GO


ALTER TABLE [dbo].[TIPO_TRASPASO] ADD 
	CONSTRAINT [FK_TIPO_TRASPASO_01] 
		FOREIGN KEY ( [L_TIPO_TRASPASO] ) 
		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] ),
	CONSTRAINT [FK_TIPO_TRASPASO_02] 
		FOREIGN KEY ( [K_CLASE_TRASPASO] ) 
		REFERENCES [dbo].[CLASE_TRASPASO] ( [K_CLASE_TRASPASO] )
GO



-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_TIPO_TRASPASO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_TIPO_TRASPASO]
GO


CREATE PROCEDURE [dbo].[PG_CI_TIPO_TRASPASO]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	-- ========================================
	@PP_K_TIPO_TRASPASO					INT,
	@PP_D_TIPO_TRASPASO					VARCHAR(100),
	@PP_S_TIPO_TRASPASO					VARCHAR(10),
	@PP_O_TIPO_TRASPASO					INT,
	@PP_C_TIPO_TRASPASO					VARCHAR(255),
	@PP_L_TIPO_TRASPASO					INT,
	@PP_K_CLASE_TRASPASO				INT		
AS
	-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_TIPO_TRASPASO
							FROM	TIPO_TRASPASO
							WHERE	K_TIPO_TRASPASO=@PP_K_TIPO_TRASPASO

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO TIPO_TRASPASO
			(	K_TIPO_TRASPASO,				D_TIPO_TRASPASO, 
				S_TIPO_TRASPASO,				O_TIPO_TRASPASO,
				C_TIPO_TRASPASO,
				L_TIPO_TRASPASO,
				K_CLASE_TRASPASO				)
		VALUES	
			(	@PP_K_TIPO_TRASPASO,			@PP_D_TIPO_TRASPASO,	
				@PP_S_TIPO_TRASPASO,			@PP_O_TIPO_TRASPASO,
				@PP_C_TIPO_TRASPASO,
				@PP_L_TIPO_TRASPASO,
				@PP_K_CLASE_TRASPASO			)
	ELSE
		UPDATE	TIPO_TRASPASO
		SET		D_TIPO_TRASPASO	= @PP_D_TIPO_TRASPASO,	
				S_TIPO_TRASPASO	= @PP_S_TIPO_TRASPASO,			
				O_TIPO_TRASPASO	= @PP_O_TIPO_TRASPASO,
				C_TIPO_TRASPASO	= @PP_C_TIPO_TRASPASO,
				L_TIPO_TRASPASO	= @PP_L_TIPO_TRASPASO	
		WHERE	K_TIPO_TRASPASO=@PP_K_TIPO_TRASPASO

	-- =========================================================
GO



EXECUTE [dbo].[PG_CI_TIPO_TRASPASO] 0, 0,  1, 'TRASPASO PROGRAMADO',	'PROGR',  100, '', 1,  1
EXECUTE [dbo].[PG_CI_TIPO_TRASPASO] 0, 0,  2, 'TRASPASO EXTESION',		'EXTEN',  100, '', 1,  1
EXECUTE [dbo].[PG_CI_TIPO_TRASPASO] 0, 0,  3, 'TRASPASO NO PROGRAMADO',	'NOPRO',  200, '', 1,  1

GO




-- ///////////////////////////////////////////////////////////////
-- //					ESTATUS_TRASPASO					
-- ///////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[ESTATUS_TRASPASO] (
	[K_ESTATUS_TRASPASO]			INT NOT NULL,
	[D_ESTATUS_TRASPASO]			VARCHAR (100) NOT NULL,
	[S_ESTATUS_TRASPASO]			VARCHAR (10) NOT NULL,
	[O_ESTATUS_TRASPASO]			INT NOT NULL,
	[C_ESTATUS_TRASPASO]			VARCHAR (255) NOT NULL,
	[L_ESTATUS_TRASPASO]			INT NOT NULL
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[ESTATUS_TRASPASO]
	ADD CONSTRAINT [PK_ESTATUS_TRASPASO]
		PRIMARY KEY CLUSTERED ([K_ESTATUS_TRASPASO])
GO


CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_ESTATUS_TRASPASO_01_DESCRIPCION] 
	   ON [dbo].[ESTATUS_TRASPASO] ( [D_ESTATUS_TRASPASO] )
GO


ALTER TABLE [dbo].[ESTATUS_TRASPASO] ADD 
	CONSTRAINT [FK_ESTATUS_TRASPASO_01] 
		FOREIGN KEY ( [L_ESTATUS_TRASPASO] ) 
		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] )
GO


-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_ESTATUS_TRASPASO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_ESTATUS_TRASPASO]
GO


CREATE PROCEDURE [dbo].[PG_CI_ESTATUS_TRASPASO]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	-- ========================================
	@PP_K_ESTATUS_TRASPASO				INT,
	@PP_D_ESTATUS_TRASPASO				VARCHAR(100),
	@PP_S_ESTATUS_TRASPASO				VARCHAR(10),
	@PP_O_ESTATUS_TRASPASO				INT,
	@PP_C_ESTATUS_TRASPASO				VARCHAR(255),
	@PP_L_ESTATUS_TRASPASO				INT
AS
-- ===============================

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_ESTATUS_TRASPASO
							FROM	ESTATUS_TRASPASO
							WHERE	K_ESTATUS_TRASPASO=@PP_K_ESTATUS_TRASPASO

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO ESTATUS_TRASPASO	
			(	K_ESTATUS_TRASPASO,				D_ESTATUS_TRASPASO, 
				S_ESTATUS_TRASPASO,				O_ESTATUS_TRASPASO,
				C_ESTATUS_TRASPASO,
				L_ESTATUS_TRASPASO				)		
		VALUES	
			(	@PP_K_ESTATUS_TRASPASO,			@PP_D_ESTATUS_TRASPASO,	
				@PP_S_ESTATUS_TRASPASO,			@PP_O_ESTATUS_TRASPASO,
				@PP_C_ESTATUS_TRASPASO,
				@PP_L_ESTATUS_TRASPASO			)
	ELSE
		UPDATE	ESTATUS_TRASPASO
		SET		D_ESTATUS_TRASPASO	= @PP_D_ESTATUS_TRASPASO,	
				S_ESTATUS_TRASPASO	= @PP_S_ESTATUS_TRASPASO,			
				O_ESTATUS_TRASPASO	= @PP_O_ESTATUS_TRASPASO,
				C_ESTATUS_TRASPASO	= @PP_C_ESTATUS_TRASPASO,
				L_ESTATUS_TRASPASO	= @PP_L_ESTATUS_TRASPASO	
		WHERE	K_ESTATUS_TRASPASO=@PP_K_ESTATUS_TRASPASO

	-- =========================================================
GO


EXECUTE [dbo].[PG_CI_ESTATUS_TRASPASO] 0, 0, 1, 'BASE',			'BASE',	1, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_TRASPASO] 0, 0, 2, 'PROGRAMADO',	'PROG',	1, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_TRASPASO] 0, 0, 3, 'AUTORIZADO',	'AUTR',	1, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_TRASPASO] 0, 0, 4, 'EJECUTADO',	'EJEC',	1, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_TRASPASO] 0, 0, 5, 'CONCILIADO',	'CONC',	1, '', 1
EXECUTE [dbo].[PG_CI_ESTATUS_TRASPASO] 0, 0, 6, 'CANCELADO',	'CANC',	1, '', 1


GO




-- ///////////////////////////////////////////////////////////////
-- //					CONCEPTO_TRASPASO					
-- ///////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[CONCEPTO_TRASPASO] (
	[K_CONCEPTO_TRASPASO]			INT NOT NULL,
	[D_CONCEPTO_TRASPASO]			VARCHAR (100) NOT NULL,
	[S_CONCEPTO_TRASPASO]			VARCHAR (10) NOT NULL,
	[O_CONCEPTO_TRASPASO]			INT NOT NULL,
	[C_CONCEPTO_TRASPASO]			VARCHAR (255) NOT NULL,
	[L_CONCEPTO_TRASPASO]			INT NOT NULL
) ON [PRIMARY]
GO


-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[CONCEPTO_TRASPASO]
	ADD CONSTRAINT [PK_CONCEPTO_TRASPASO]
		PRIMARY KEY CLUSTERED ([K_CONCEPTO_TRASPASO])
GO


CREATE UNIQUE NONCLUSTERED 
	INDEX [UN_CONCEPTO_TRASPASO_01_DESCRIPCION] 
	   ON [dbo].[CONCEPTO_TRASPASO] ( [D_CONCEPTO_TRASPASO] )
GO


ALTER TABLE [dbo].[CONCEPTO_TRASPASO] ADD 
	CONSTRAINT [FK_CONCEPTO_TRASPASO_01] 
		FOREIGN KEY ( [L_CONCEPTO_TRASPASO] ) 
		REFERENCES [dbo].[ESTATUS_ACTIVO] ( [K_ESTATUS_ACTIVO] )
GO


-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_CONCEPTO_TRASPASO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_CONCEPTO_TRASPASO]
GO


CREATE PROCEDURE [dbo].[PG_CI_CONCEPTO_TRASPASO]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	-- ========================================
	@PP_K_CONCEPTO_TRASPASO				INT,
	@PP_D_CONCEPTO_TRASPASO				VARCHAR(100),
	@PP_S_CONCEPTO_TRASPASO				VARCHAR(10),
	@PP_O_CONCEPTO_TRASPASO				INT,
	@PP_C_CONCEPTO_TRASPASO				VARCHAR(255),
	@PP_L_CONCEPTO_TRASPASO				INT
AS

	DECLARE @VP_K_EXISTE	INT

	SELECT	@VP_K_EXISTE =	K_CONCEPTO_TRASPASO
							FROM	CONCEPTO_TRASPASO
							WHERE	K_CONCEPTO_TRASPASO=@PP_K_CONCEPTO_TRASPASO

	-- ===============================

	IF @VP_K_EXISTE IS NULL
		INSERT INTO CONCEPTO_TRASPASO
			(	K_CONCEPTO_TRASPASO,			D_CONCEPTO_TRASPASO, 
				S_CONCEPTO_TRASPASO,			O_CONCEPTO_TRASPASO,
				C_CONCEPTO_TRASPASO,
				L_CONCEPTO_TRASPASO			)		
		VALUES	
			(	@PP_K_CONCEPTO_TRASPASO,		@PP_D_CONCEPTO_TRASPASO,	
				@PP_S_CONCEPTO_TRASPASO,		@PP_O_CONCEPTO_TRASPASO,
				@PP_C_CONCEPTO_TRASPASO,
				@PP_L_CONCEPTO_TRASPASO		)
	ELSE
		UPDATE	CONCEPTO_TRASPASO
		SET		D_CONCEPTO_TRASPASO	= @PP_D_CONCEPTO_TRASPASO,	
				S_CONCEPTO_TRASPASO	= @PP_S_CONCEPTO_TRASPASO,			
				O_CONCEPTO_TRASPASO	= @PP_O_CONCEPTO_TRASPASO,
				C_CONCEPTO_TRASPASO	= @PP_C_CONCEPTO_TRASPASO,
				L_CONCEPTO_TRASPASO	= @PP_L_CONCEPTO_TRASPASO	
		WHERE	K_CONCEPTO_TRASPASO=@PP_K_CONCEPTO_TRASPASO

	-- =========================================================
GO


EXECUTE [dbo].[PG_CI_CONCEPTO_TRASPASO] 0, 0, 0, 'NO DETERMINADO',		'NODET', 1, '', 1
EXECUTE [dbo].[PG_CI_CONCEPTO_TRASPASO] 0, 0, 1, 'TRA1',				'VTACO', 2, '', 1
EXECUTE [dbo].[PG_CI_CONCEPTO_TRASPASO] 0, 0, 2, 'TRA2',				'COBRA', 3, '', 1
EXECUTE [dbo].[PG_CI_CONCEPTO_TRASPASO] 0, 0, 3, 'TRA3',				'MIXTO', 4, '', 1
GO




-- ///////////////////////////////////////////////////////////////
-- //						TRASPASO							
-- ///////////////////////////////////////////////////////////////

CREATE TABLE [dbo].[TRASPASO] (
	-- =============================== CONTROL
	[K_TRASPASO]						INT NOT NULL,
	[D_TRASPASO]						VARCHAR (255) NOT NULL,
	[K_TIPO_TRASPASO]					INT NOT NULL,
	[K_ESTATUS_TRASPASO]				INT NOT NULL,
	[K_CONCEPTO_TRASPASO]				INT NOT NULL,
	[K_RUBRO_PRESUPUESTO]				INT NOT NULL,					-- HGF/20180919 // SE CAMPO NUEVO
	[L_CAPTURA_MANUAL]					INT NOT NULL,
	-- =============================== SEGUN PDF
	[F_OPERACION]						DATE NOT NULL,	
	[K_UNIDAD_OPERATIVA]				INT NOT NULL,
	[C_TRASPASO]						VARCHAR (255) NOT NULL,
	[MONTO_AUTORIZADO]					DECIMAL(19,4) NOT NULL,			-- HGF/20180919 // SE RENOMBRO EL CAMPO 
	[MONTO_APLICAR]						DECIMAL(19,4) NOT NULL			-- HGF/20180919 // SE RENOMBRO EL CAMPO 
) ON [PRIMARY]
GO

-- //////////////////////////////////////////////////////

ALTER TABLE [dbo].[TRASPASO]
	ADD CONSTRAINT [PK_TRASPASO]
		PRIMARY KEY CLUSTERED ([K_TRASPASO])
GO

-- PENDIENTE
-- ALTER TABLE [dbo].[TRASPASO] ADD 
-- 	CONSTRAINT [FK_TRASPASO_01] 
-- 		FOREIGN KEY ([K_CUENTA_BANCO])
-- 		REFERENCES [dbo].[CUENTA_BANCO] ([K_CUENTA_BANCO])
-- GO
/*
ALTER TABLE [dbo].[TRASPASO] ADD 
	CONSTRAINT [FK_TRASPASO_02] 
		FOREIGN KEY ([K_TIPO_PRESUPUESTO])
		REFERENCES [dbo].[TIPO_PRESUPUESTO] ([K_TIPO_PRESUPUESTO])
GO
*/

ALTER TABLE [dbo].[TRASPASO] ADD 
	CONSTRAINT [FK_TRASPASO_03] 
		FOREIGN KEY ([K_ESTATUS_TRASPASO]) 
		REFERENCES [dbo].[ESTATUS_TRASPASO] ([K_ESTATUS_TRASPASO]),
/*	CONSTRAINT [FK_TRASPASO_04] 
		FOREIGN KEY ([K_TIPO_TRASPASO]) 
		REFERENCES [dbo].[TIPO_TRASPASO] ([K_TIPO_TRASPASO]),	*/
	CONSTRAINT [FK_TRASPASO_05] 
		FOREIGN KEY ([K_CONCEPTO_TRASPASO]) 
		REFERENCES [dbo].[CONCEPTO_TRASPASO] ([K_CONCEPTO_TRASPASO]),
	CONSTRAINT [FK_TRASPASO_06] 
		FOREIGN KEY ([K_UNIDAD_OPERATIVA]) 
		REFERENCES [dbo].[UNIDAD_OPERATIVA] ([K_UNIDAD_OPERATIVA])
GO




-- //////////////////////////////////////////////////////////////


ALTER TABLE [dbo].[TRASPASO] 
	ADD		[K_USUARIO_ALTA]				[INT] NOT NULL,
			[F_ALTA]						[DATETIME] NOT NULL,
			[K_USUARIO_CAMBIO]				[INT] NOT NULL,
			[F_CAMBIO]						[DATETIME] NOT NULL,
			[L_BORRADO]						[INT] NOT NULL,
			[K_USUARIO_BAJA]				[INT] NULL,
			[F_BAJA]						[DATETIME] NULL;
GO


ALTER TABLE [dbo].[TRASPASO] ADD 
	CONSTRAINT [FK_TRASPASO_USUARIO_ALTA]  
		FOREIGN KEY ([K_USUARIO_ALTA]) 
		REFERENCES [dbo].[USUARIO] ([K_USUARIO]),
	CONSTRAINT [FK_TRASPASO_USUARIO_CAMBIO]  
		FOREIGN KEY ([K_USUARIO_CAMBIO]) 
		REFERENCES [dbo].[USUARIO] ([K_USUARIO]),
	CONSTRAINT [FK_TRASPASO_USUARIO_BAJA]  
		FOREIGN KEY ([K_USUARIO_BAJA]) 
		REFERENCES [dbo].[USUARIO] ([K_USUARIO])
GO


-- //////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_TRASPASO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_TRASPASO]
GO


CREATE PROCEDURE [dbo].[PG_CI_TRASPASO]
	@PP_L_DEBUG						INT,
	@PP_K_SISTEMA_EXE				INT,
	@PP_K_TRASPASO					INT,
	@PP_D_TRASPASO					VARCHAR(100),
	@PP_K_ESTATUS_TRASPASO			INT,
	@PP_K_TIPO_TRASPASO				INT
AS

	INSERT INTO TRASPASO
		(	K_TRASPASO,				
			K_ESTATUS_TRASPASO,		
			K_TIPO_TRASPASO			)
	VALUES	
		(	@PP_K_TRASPASO,			
			@PP_K_ESTATUS_TRASPASO,
			@PP_K_TIPO_TRASPASO		)
	
	-- ==============================================
GO



-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
-- //////////////////////////////////////////////////////////////
