-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			SOLICITUD DE SERVICIOS 
-- // OPERACION:		LIBERACION / SP PARA REPORTES
-- // AUTOR:			LAURA BARRAZA
-- // FECHA:			2018-09-13
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0]
GO

-- //////////////////////////////////////////////////////////////







-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> NOTA_AUTORIZACION
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_RP_004A_NOTA_AUTORIZACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_RP_004A_NOTA_AUTORIZACION]
GO


CREATE PROCEDURE [dbo].[PG_RP_004A_NOTA_AUTORIZACION]
	@PP_L_DEBUG					[INT],
	@PP_K_SISTEMA_EXE			[INT],
	@PP_K_USUARIO_ACCION		[INT],
	-- ===========================		
	@PP_K_TABLA_AMORTIZACION	[INT],
	-- ===========================		
	@OU_RESULTADO				[VARCHAR] (1000)		OUTPUT
AS

	DECLARE @VP_RESULTADO	VARCHAR(1000)
	
	SET		@VP_RESULTADO	= ''
		
	-- /////////////////////////////////////////////////////

			
	SET @VP_RESULTADO = 'Así mismo, autorizamos a Jorge Alfredo Villareal Palomo quien se identifica con credencial '
	SET @VP_RESULTADO = @VP_RESULTADO+ 'de elector No. 1936019957132, '
	SET @VP_RESULTADO = @VP_RESULTADO+ 'a Ricardo Juventino Nuñez Villalobos credencial de elector No. 276101986247, '
	SET @VP_RESULTADO = @VP_RESULTADO+ 'a Isais Murillo Ivan Eduardo credencial de elector No. 1940083421023 para que '
	SET @VP_RESULTADO = @VP_RESULTADO+ 'tramite la operacion solicitada y le sea entregado el docuemnto que se genere'
		
	-- /////////////////////////////////////////////////////
	
	SET @OU_RESULTADO = @VP_RESULTADO

	-- /////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> AUTORIZADOR IZQUIERDA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_RP_004B_AUTORIZADOR_IZQUIERDA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_RP_004B_AUTORIZADOR_IZQUIERDA]
GO


CREATE PROCEDURE [dbo].[PG_RP_004B_AUTORIZADOR_IZQUIERDA]
	@PP_L_DEBUG					[INT],
	@PP_K_SISTEMA_EXE			[INT],
	@PP_K_USUARIO_ACCION		[INT],
	-- ===========================		
	@PP_K_TABLA_AMORTIZACION	[INT],
	-- ===========================		
	@OU_RESULTADO				[VARCHAR] (300)		OUTPUT
AS

	DECLARE @VP_RESULTADO	VARCHAR(300)
	
	SET		@VP_RESULTADO	= ''
		
	-- /////////////////////////////////////////////////////

			
	SET @VP_RESULTADO='CP. FEDERICO ROBLES NETTEL '
		
	-- /////////////////////////////////////////////////////
	
	SET @OU_RESULTADO = @VP_RESULTADO

	-- /////////////////////////////////////////////////////
GO



-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> AUTORIZADOR DERECHA
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_RP_004C_AUTORIZADOR_DERECHA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_RP_004C_AUTORIZADOR_DERECHA]
GO


CREATE PROCEDURE [dbo].[PG_RP_004C_AUTORIZADOR_DERECHA]
	@PP_L_DEBUG					[INT],
	@PP_K_SISTEMA_EXE			[INT],
	@PP_K_USUARIO_ACCION		[INT],
	-- ===========================		
	@PP_K_TABLA_AMORTIZACION	[INT],
	-- ===========================		
	@OU_RESULTADO				[VARCHAR] (300)		OUTPUT
AS

	DECLARE @VP_RESULTADO	VARCHAR(300)
	
	SET		@VP_RESULTADO	= ''
		
	-- /////////////////////////////////////////////////////

			
	SET @VP_RESULTADO='LCPF. OCTAVIO GONZALEZ RAMIREZ '
		
	-- /////////////////////////////////////////////////////
	
	SET @OU_RESULTADO = @VP_RESULTADO

	-- /////////////////////////////////////////////////////
GO


-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> NOMBRE DEL EJECUTIVO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_RP_004D_EJECUTIVO_CUENTA]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_RP_004D_EJECUTIVO_CUENTA]
GO


CREATE PROCEDURE [dbo].[PG_RP_004D_EJECUTIVO_CUENTA]
	@PP_L_DEBUG					[INT],
	@PP_K_SISTEMA_EXE			[INT],
	@PP_K_USUARIO_ACCION		[INT],
	-- ===========================		
	@PP_K_TABLA_AMORTIZACION	[INT],
	-- ===========================		
	@OU_RESULTADO				[VARCHAR] (300)		OUTPUT
AS

	DECLARE @VP_RESULTADO	VARCHAR(300)
	
	SET		@VP_RESULTADO	= ''
		
	-- /////////////////////////////////////////////////////

	SELECT @VP_RESULTADO=EJECUTIVO	FROM TABLA_AMORTIZACION
									INNER JOIN CREDITO_BANCARIO ON TABLA_AMORTIZACION.K_CREDITO_BANCARIO=CREDITO_BANCARIO.K_CREDITO_BANCARIO
									INNER JOIN CUENTA_BANCO ON CREDITO_BANCARIO.K_CUENTA_BANCO_PAGO=CUENTA_BANCO.K_CUENTA_BANCO
	
	IF @VP_RESULTADO IS NULL
		SET @VP_RESULTADO='NOMBRE DEL EJECUTIVO'
		
	-- /////////////////////////////////////////////////////
	
	SET @OU_RESULTADO = @VP_RESULTADO

	-- /////////////////////////////////////////////////////
GO




-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> BANCO DEL CREDITO
-- //////////////////////////////////////////////////////////////

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_RP_004E_BANCO_TABLA_AMORTIZACION]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_RP_004E_BANCO_TABLA_AMORTIZACION]
GO


CREATE PROCEDURE [dbo].[PG_RP_004E_BANCO_TABLA_AMORTIZACION]
	@PP_L_DEBUG					[INT],
	@PP_K_SISTEMA_EXE			[INT],
	@PP_K_USUARIO_ACCION		[INT],
	-- ===========================		
	@PP_K_TABLA_AMORTIZACION	[INT],
	-- ===========================		
	@OU_RESULTADO				[VARCHAR] (300)		OUTPUT
AS

	DECLARE @VP_RESULTADO	VARCHAR(300)
	
	SET		@VP_RESULTADO	= ''
		
	-- /////////////////////////////////////////////////////

	SELECT	@VP_RESULTADO	=	D_BANCO 
								FROM TABLA_AMORTIZACION,CREDITO_BANCARIO,BANCO
								WHERE TABLA_AMORTIZACION.K_CREDITO_BANCARIO=CREDITO_BANCARIO.K_CREDITO_BANCARIO
								AND	CREDITO_BANCARIO.K_BANCO=BANCO.K_BANCO
								AND	TABLA_AMORTIZACION.K_TABLA_AMORTIZACION=@PP_K_TABLA_AMORTIZACION
			
	-- /////////////////////////////////////////////////////
	
	SET @OU_RESULTADO = @VP_RESULTADO

	-- /////////////////////////////////////////////////////
GO




	
-- //////////////////////////////////////////////////////////////
-- // STORED PROCEDURE ---> SELECT / LISTADO
-- //////////////////////////////////////////////////////////////
-- EXECUTE [dbo].[PG_RT_SOLICITUD_DE_SERVICIOS_BANCA_DE_EMPRESAS]		0,0,0,		29


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_RP_004_SOLICITUD_DE_SERVICIOS_BANCA_DE_EMPRESAS]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_RP_004_SOLICITUD_DE_SERVICIOS_BANCA_DE_EMPRESAS]
GO


CREATE PROCEDURE [dbo].[PG_RP_004_SOLICITUD_DE_SERVICIOS_BANCA_DE_EMPRESAS]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ===========================
	@PP_K_TABLA_AMORTIZACION	INT
AS

	DECLARE	@VP_IMPORTE AS DECIMAL(19,4)=0
	SELECT @VP_IMPORTE	=	PAGO_TOTAL
							FROM TABLA_AMORTIZACION
							WHERE TABLA_AMORTIZACION.K_TABLA_AMORTIZACION=@PP_K_TABLA_AMORTIZACION

	DECLARE	@VP_IMPORTE_CON_LETRA VARCHAR(400)

--	SELECT	@VP_IMPORTE_CON_LETRA	=	[dbo].[FG_CANTIDAD_LETRAS](@VP_IMPORTE)
	
	EXECUTE [dbo].[PG_PR_NUM_CONVERSION_A_TEXTO_OUT]		@VP_IMPORTE,
															@OU_IMPORTE_LETRA = @VP_IMPORTE_CON_LETRA		OUTPUT

	IF @VP_IMPORTE_CON_LETRA IS NULL
		SET @VP_IMPORTE_CON_LETRA='----'

	SET @VP_IMPORTE_CON_LETRA = '(' + @VP_IMPORTE_CON_LETRA + ')'

	IF @PP_L_DEBUG>0
		BEGIN
		PRINT '@VP_IMPORTE					:'+ cast(@VP_IMPORTE AS VARCHAR(400))
		PRINT '@@VP_IMPORTE_CON_LETRA		:'+@VP_IMPORTE_CON_LETRA
		END		

	DECLARE @VP_NOTA_AUTORIZACION AS VARCHAR(1000)

	EXECUTE [dbo].[PG_RP_004A_NOTA_AUTORIZACION]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
														@PP_K_TABLA_AMORTIZACION, -- @PP_K_DATA_SISTEMA,	
														@OU_RESULTADO = @VP_NOTA_AUTORIZACION		OUTPUT
	-- ==============================================

	DECLARE	@VP_AUTORIZADOR_IZQUIERDA AS VARCHAR(300)
	
	EXECUTE [dbo].[PG_RP_004B_AUTORIZADOR_IZQUIERDA]	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
														@PP_K_TABLA_AMORTIZACION, -- @PP_K_DATA_SISTEMA,	
														@OU_RESULTADO = @VP_AUTORIZADOR_IZQUIERDA		OUTPUT
	-- ==============================================

	DECLARE	@VP_AUTORIZADOR_DERECHA	 AS VARCHAR(300)

	EXECUTE [dbo].[PG_RP_004C_AUTORIZADOR_DERECHA]		@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
														@PP_K_TABLA_AMORTIZACION, -- @PP_K_DATA_SISTEMA,	
														@OU_RESULTADO = @VP_AUTORIZADOR_DERECHA		OUTPUT
	-- ==============================================

	DECLARE	@VP_EJECUTIVO_CUENTA	 AS VARCHAR(300)

	EXECUTE [dbo].[PG_RP_004D_EJECUTIVO_CUENTA]			@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
														@PP_K_TABLA_AMORTIZACION, -- @PP_K_DATA_SISTEMA,	
														@OU_RESULTADO = @VP_EJECUTIVO_CUENTA		OUTPUT
	-- ==============================================

	DECLARE	@VP_BANCO_TABLA_AMORTIZACION AS VARCHAR(300)

	EXECUTE [dbo].[PG_RP_004E_BANCO_TABLA_AMORTIZACION]			@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION,	
																@PP_K_TABLA_AMORTIZACION, -- @PP_K_DATA_SISTEMA,	
																@OU_RESULTADO = @VP_BANCO_TABLA_AMORTIZACION		OUTPUT												
	-- ==============================================
	
	IF @PP_L_DEBUG>0
		BEGIN
		PRINT '@VP_NOTA_AUTORIZACION			:'+ @VP_NOTA_AUTORIZACION 
		PRINT '@VP_AUTORIZADOR_IZQUIERDA		:'+ @VP_AUTORIZADOR_IZQUIERDA
		PRINT '@VP_AUTORIZADOR_DERECHA			:'+ @VP_AUTORIZADOR_DERECHA
		PRINT '@VP_EJECUTIVO_CUENTA				:'+ @VP_EJECUTIVO_CUENTA
		PRINT '@VP_BANCO_TABLA_AMORTIZACION		:'+ @VP_BANCO_TABLA_AMORTIZACION
		END		
		
	DECLARE	@VP_RAZON_SOCIAL_ORDENANTE	AS VARCHAR(300)
	DECLARE @VP_CUENTA_CARGO			AS VARCHAR(20)
	DECLARE	@VP_RFC_ORDENANTE			AS VARCHAR(20)

	SELECT	@VP_RAZON_SOCIAL_ORDENANTE	=	RAZON_SOCIAL.D_RAZON_SOCIAL,
			@VP_CUENTA_CARGO			=	CUENTA_BANCO.CUENTA,
			@VP_RFC_ORDENANTE			=	RAZON_SOCIAL.RFC_RAZON_SOCIAL
											FROM TABLA_AMORTIZACION, CREDITO_BANCARIO,RAZON_SOCIAL,CUENTA_BANCO
											WHERE	TABLA_AMORTIZACION.K_CREDITO_BANCARIO=CREDITO_BANCARIO.K_CREDITO_BANCARIO
											AND		CREDITO_BANCARIO.K_RAZON_SOCIAL_ACREDITADA=RAZON_SOCIAL.K_RAZON_SOCIAL
											AND		CREDITO_BANCARIO.K_CUENTA_BANCO_PAGO=CUENTA_BANCO.K_CUENTA_BANCO
											AND		TABLA_AMORTIZACION.K_TABLA_AMORTIZACION=@PP_K_TABLA_AMORTIZACION

	IF @PP_L_DEBUG>0
		BEGIN
		PRINT '@VP_RAZON_SOCIAL_ORDENANTE		:'+ @VP_RAZON_SOCIAL_ORDENANTE 
		PRINT '@VP_CUENTA_CARGO					:'+ @VP_CUENTA_CARGO
		PRINT '@VP_RFC_ORDENANTE				:'+ @VP_RFC_ORDENANTE
		END		

	DECLARE	@VP_CUENTA_BENEFICIARIO		AS VARCHAR(300)

	DECLARE @VP_BANCO_BENEFICIARIO		AS VARCHAR(20)
	DECLARE	@VP_DIRECCION_BANCO			AS VARCHAR(20)

	SELECT	@VP_CUENTA_BENEFICIARIO	=	RAZON_SOCIAL.D_RAZON_SOCIAL,
			@VP_BANCO_BENEFICIARIO	=	BANCO.D_BANCO,
			@VP_DIRECCION_BANCO		=	BANCO.C_BANCO
										FROM TABLA_AMORTIZACION, CREDITO_BANCARIO,RAZON_SOCIAL,CUENTA_BANCO,BANCO
										WHERE	TABLA_AMORTIZACION.K_CREDITO_BANCARIO=CREDITO_BANCARIO.K_CREDITO_BANCARIO
										AND		CREDITO_BANCARIO.K_RAZON_SOCIAL_BENEFICIADA=RAZON_SOCIAL.K_RAZON_SOCIAL
										AND		CREDITO_BANCARIO.K_CUENTA_BANCO_PAGO=CUENTA_BANCO.K_CUENTA_BANCO		
										AND		TABLA_AMORTIZACION.K_TABLA_AMORTIZACION=@PP_K_TABLA_AMORTIZACION

	IF @PP_L_DEBUG>0
		BEGIN
		PRINT '@VP_CUENTA_BENEFICIARIO		:'+ @VP_CUENTA_BENEFICIARIO 
		PRINT '@VP_BANCO_BENEFICIARIO		:'+ @VP_BANCO_BENEFICIARIO
		PRINT '@VP_DIRECCION_BANCO			:'+ @VP_DIRECCION_BANCO
		END		

	DECLARE	@VP_CIUDAD		AS VARCHAR(300)
	DECLARE @VP_ESTADO		AS VARCHAR(20)
	DECLARE	@VP_PAIS		AS VARCHAR(20)

	SELECT	@VP_CIUDAD	=	'JUAREZ',
			@VP_ESTADO	=	'CHIHUAHUA',
			@VP_PAIS	=	'MEXICO'
			

	--IF @PP_L_DEBUG>0
	--BEGIN
	--	--PRINT '@VP_CUENTA_BENEFICIARIO		:'+ @VP_CUENTA_BENEFICIARIO 
	--	--PRINT '@VP_BANCO_BENEFICIARIO		:'+ @VP_BANCO_BENEFICIARIO
	--	--PRINT '@VP_DIRECCION_BANCO			:'+ @VP_DIRECCION_BANCO
	--END		

	DECLARE @VP_FECHA DATE

	SELECT @VP_FECHA =	F_PERIODO_FIN 
						FROM TABLA_AMORTIZACION
						WHERE K_TABLA_AMORTIZACION=@PP_K_TABLA_AMORTIZACION

	DECLARE @VP_MONEDA VARCHAR(50)

	SELECT @VP_MONEDA =	D_MONEDA 
						FROM CREDITO_BANCARIO
						INNER JOIN TABLA_AMORTIZACION ON CREDITO_BANCARIO.K_CREDITO_BANCARIO=TABLA_AMORTIZACION.K_CREDITO_BANCARIO
						AND K_TABLA_AMORTIZACION=@PP_K_TABLA_AMORTIZACION
						INNER JOIN MONEDA ON  CREDITO_BANCARIO.K_MONEDA = MONEDA.K_MONEDA
						



	SELECT 	@VP_IMPORTE				AS RP_IMPORTE,
			@VP_IMPORTE_CON_LETRA IMPORTE_CON_LETRA,
			@VP_BANCO_TABLA_AMORTIZACION BANCO_TABLA_AMORTIZACION,
			@VP_RAZON_SOCIAL_ORDENANTE NOMBRE_ORDENANTE,
			@VP_CUENTA_CARGO CUENTA_CARGO,@VP_RFC_ORDENANTE RFC,
			@VP_RAZON_SOCIAL_ORDENANTE NOMBRE_BENEFICIARIO,
			@VP_CUENTA_BENEFICIARIO CUENTA_BENEFICIARIO,
			@VP_BANCO_BENEFICIARIO BANCO_BENEFICIARIO,
			@VP_DIRECCION_BANCO DIRECCION_BANCO,
			@VP_CIUDAD CIUDAD,	
			@VP_ESTADO ESTADO,	
			@VP_PAIS PAIS,
			@VP_NOTA_AUTORIZACION NOTA_AUTORIZACION, 
			@VP_AUTORIZADOR_IZQUIERDA AUTORIZACION_IZQUIERDA,
			@VP_AUTORIZADOR_DERECHA AUTORIZADOR_DERECHA, 
			@VP_EJECUTIVO_CUENTA EJECUTIVO_CUENTA,
			@VP_BANCO_TABLA_AMORTIZACION BANCO_TABLA_AMORTIZACION,
			@VP_FECHA FECHA,
			@VP_MONEDA MONEDA	
	
	-- /////////////////////////////////////////////////////////////////////
GO



--EXECUTE [dbo].[PG_RT_SOLICITUD_DE_SERVICIOS_BANCA_DE_EMPRESAS]  1,0,69,85

-- //////////////////////////////////////////////////////////////////////////////////
