-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			CLASIFICACION GASTO
-- // OPERACION:		LIBERACION / TABLAS
-- // AUTOR:			LBG
-- // FECHA:            20180911
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0]
GO

-- //////////////////////////////////////////////////////////////



-- //////////////////////////////////////////////////////////////
-- // DROPs
-- //////////////////////////////////////////////////////////////



IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLASIFICACION_GASTO]') AND type in (N'U'))
	DELETE	FROM [dbo].[CLASIFICACION_GASTO]
GO




-- //////////////////////////////////////////////////////////////


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_CI_CLASIFICACION_GASTO]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_CI_CLASIFICACION_GASTO]
GO


CREATE PROCEDURE [dbo].[PG_CI_CLASIFICACION_GASTO]
	@PP_L_DEBUG							INT,
	@PP_K_SISTEMA_EXE					INT,
	@PP_K_USUARIO_ACCION				INT,	
	@PP_K_CLASIFICACION_GASTO			INT,
	@PP_D_CLASIFICACION_GASTO			VARCHAR(100),
	@PP_S_CLASIFICACION_GASTO			VARCHAR(10),
	@PP_O_CLASIFICACION_GASTO			INT,
	@PP_C_CLASIFICACION_GASTO			VARCHAR(255),
	@PP_L_CLASIFICACION_GASTO			INT,
	@PP_K_RUBRO_GASTO					INT		
AS

	INSERT INTO CLASIFICACION_GASTO
		(	K_CLASIFICACION_GASTO,				D_CLASIFICACION_GASTO, 
			S_CLASIFICACION_GASTO,				O_CLASIFICACION_GASTO,
			C_CLASIFICACION_GASTO,
			L_CLASIFICACION_GASTO,
			K_RUBRO_GASTO,
			K_USUARIO_ALTA,						F_ALTA,
			K_USUARIO_CAMBIO,					F_CAMBIO,
			L_BORRADO					)
	VALUES	
		(	@PP_K_CLASIFICACION_GASTO,			@PP_D_CLASIFICACION_GASTO,	
			@PP_S_CLASIFICACION_GASTO,			@PP_O_CLASIFICACION_GASTO,
			@PP_C_CLASIFICACION_GASTO,
			@PP_L_CLASIFICACION_GASTO,
			@PP_K_RUBRO_GASTO,
			@PP_K_USUARIO_ACCION,				GETDATE(),
			@PP_K_USUARIO_ACCION,				GETDATE(),
			0				)

	-- =========================================================
GO





-- ===============================================

SET NOCOUNT ON

-- ===============================================


EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 1, 'BOLETOS DE AVION', 'SS', 10, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 2, 'BONOS Y GRATIFICACIONES', 'SS', 20, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 3, 'CELULARES', 'SS', 30, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 4, 'EQUIPO DE COMPUTO, RADIO Y SOPORTE', 'SS', 40, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 5, 'GASTOS DIVERSOS EVENTUALES', 'SS', 50, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 6, 'GASTOS DIVERSOS PROGRAMADOS', 'SS', 60, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 7, 'HONORARIOS Y ARRENDAMIENTOS', 'SS', 70, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 8, 'HONORARIOS PROFESIONALES', 'SS', 80, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 9, 'IMPUESTOS', 'SS', 90, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 10, 'MOBILIARIO', 'SS', 100, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 11, 'NOMINA', 'SS', 110, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 12, 'PAPELERIA Y CONSUMOS', 'SS', 120, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 13, 'RECUPERACION DE GASTOS', 'SS', 130, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 14, 'VIATICOS', 'SS', 140, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 15, 'AGUINALDO', 'SS', 150, 'SC', 1, 7
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 16, 'NOMINA ', 'SS', 160, 'SC', 1, 8
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 17, 'IMPUESTOS', 'SS', 170, 'SC', 1, 8
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 18, 'GASTOS', 'SS', 180, 'SC', 1, 8
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 19, 'AEROSILZA', 'SS', 190, 'SC', 1, 10
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 20, 'AEROTOMZA', 'SS', 200, 'SC', 1, 10
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 21, 'CASAS', 'SS', 210, 'SC', 1, 10
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 22, 'COOPERACIONES DIVERSAS EVENTUALES', 'SS', 220, 'SC', 1, 10
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 23, 'COOPERACIONES DIVERSAS PROGRAMADAS', 'SS', 230, 'SC', 1, 10
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 24, 'DONATIVOS', 'SS', 240, 'SC', 1, 10
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 25, 'ENTREGAS AUTORIZADAS', 'SS', 250, 'SC', 1, 10
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 26, 'TARJETAS DE CREDITO', 'SS', 260, 'SC', 1, 10
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 27, 'RECUPERACION DE GASTOS SRES. ZARAGOZA', 'SS', 270, 'SC', 1, 10
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 28, 'INTERESES AL VENCIMIENTO', 'SS', 280, 'SC', 1, 18
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 29, 'PAGO CREDITO TERCEROS', 'SS', 290, 'SC', 1, 18
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 30, 'COOPERACION CREDITO TERCEROS', 'SS', 300, 'SC', 1, 18
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 31, 'FINANCIAMIENTO', 'SS', 310, 'SC', 1, 18
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 32, 'PETROGAS / INGRESOS / TRASPASOS', 'SS', 320, 'SC', 1, 1
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 33, 'PRESUPUESTO', 'SS', 330, 'SC', 1, 2
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 34, 'IMPUESTOS', 'SS', 340, 'SC', 1, 3
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 35, 'EXTRAORDINARIOS DISCRECIONALES', 'SS', 350, 'SC', 1, 4
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 36, 'INVERSION EQUIPO TRANSPORTE', 'SS', 360, 'SC', 1, 5
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 37, 'APORTACION FOINVER GAS / UTILIDAD', 'SS', 370, 'SC', 1, 6
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 38, 'EXTRAORDINARIOS NO DISCRECIONALES', 'SS', 380, 'SC', 1, 9
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 39, 'GASTOS FINANCIEROS', 'SS', 390, 'SC', 1, 11
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 40, 'FLETES', 'SS', 400, 'SC', 1, 12
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 41, 'APORTACION CENTAVOS 0.38 Y 0.27 Y 0.16 Y SMRU', 'SS', 410, 'SC', 1, 13
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 42, 'INZA PAGO DE CILINDROS', 'SS', 420, 'SC', 1, 14
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 43, 'INTERESES PEMEX', 'SS', 430, 'SC', 1, 15
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 44, 'INVERSION PLANTA', 'SS', 440, 'SC', 1, 16
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 45, 'PRESTAMOS FONDO EMERGENTE', 'SS', 450, 'SC', 1, 17
EXECUTE [dbo].[PG_CI_CLASIFICACION_GASTO] 0, 0, 0, 46, 'PRESTAMOS INTERCOMPANIAS', 'SS', 460, 'SC', 1, 19

GO





-- ===============================================

SET NOCOUNT OFF


