-- //////////////////////////////////////////////////////////////
-- // ARCHIVO:			
-- //////////////////////////////////////////////////////////////
-- // BASE DE DATOS:	PYF18_Finanzas
-- // MODULO:			
-- // OPERACION:		LIBERACION / STORED PROCEDURE
-- ////////////////////////////////////////////////////////////// 

USE [PYF18_Finanzas_V9999_R0]
GO

-- //////////////////////////////////////////////////////////////

/*


DELETE
FROM	DATA_N1_X_DI_D0M4
WHERE 	1000<=K_DOCUMENTO_D0M4 AND K_DOCUMENTO_D0M4<2000

DELETE
FROM	PARAMETRO_DOCUMENTO_D0M4
WHERE 	1000<=K_DOCUMENTO_D0M4 AND K_DOCUMENTO_D0M4<2000

DELETE
FROM	DOCUMENTO_D0M4
WHERE 	1000<=K_DOCUMENTO_D0M4 AND K_DOCUMENTO_D0M4<2000


*/


-- ///////////////////////////////////////////////////////////////
-- //					
-- ///////////////////////////////////////////////////////////////

--	EXECUTE [dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]	0, 0, 0, 101001, -0.25, 0.005

/*

EXECUTE [dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]	1, 0, 0, 101001, -0.25, 0.005		-- MAR >> ABR
EXECUTE [dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]	1, 0, 0, 1001,   -0.2667, 0.005

EXECUTE [dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]	1, 0, 0, 1002,   -0.0455, 0.005

EXECUTE [dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]	1, 0, 0, 1003,   -0.0476, 0.005

EXECUTE [dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]	1, 0, 0, 1004,   -0.1000, 0.010

EXECUTE [dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]	1, 0, 0, 1005,    0.0556, 0.010

EXECUTE [dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]	1, 0, 0, 1006,    0.0526, 0.010

EXECUTE [dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]	1, 0, 0, 1007,    0.5000, 0.010

EXECUTE [dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]	1, 0, 0, 1008,    0.3333, 0.010

*/


IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]
GO


CREATE PROCEDURE [dbo].[PG_OP_DATA_N1_101_COMPROMISO_PUSH]
	@PP_L_DEBUG					INT,
	@PP_K_SISTEMA_EXE			INT,
	@PP_K_USUARIO_ACCION		INT,
	-- ==============================
	@PP_K_DOCUMENTO_D0M4		INT,
	@PP_ESTACIONALIDAD			DECIMAL(19,4),		-- % COMO NUMERO ENTRE 0.00 Y 0.99
	@PP_CRECIMIENTO				DECIMAL(19,4)		-- % COMO NUMERO ENTRE 0.00 Y 0.99 (PUEDE SER NEGATIVO)
AS
	-- ==============================================
	
	DECLARE @VP_K_UNIDAD_OPERATIVA			INT
	DECLARE @VP_K_YYYY						INT
	DECLARE @VP_K_MM						INT
	DECLARE @VP_K_FORMATO_D0M4_ORIGINAL		INT

	SELECT	@VP_K_UNIDAD_OPERATIVA =		K_UNIDAD_OPERATIVA,		
			@VP_K_YYYY =					K_YYYY,
			@VP_K_MM =						K_MM, 
			@VP_K_FORMATO_D0M4_ORIGINAL =	K_FORMATO_D0M4
											FROM	DOCUMENTO_D0M4
											WHERE 	K_DOCUMENTO_D0M4=@PP_K_DOCUMENTO_D0M4
	-- ==========================
	
	IF @VP_K_FORMATO_D0M4_ORIGINAL=101
		BEGIN
	
		-- ==========================
		-- == PASO 1 // DOCUMENTO_D0M4
		SET		@VP_K_MM =  @VP_K_MM+1

		DELETE 
		FROM	DOCUMENTO_D0M4
		WHERE 	K_UNIDAD_OPERATIVA=@VP_K_UNIDAD_OPERATIVA
		AND		K_YYYY=@VP_K_YYYY
		AND		K_MM=@VP_K_MM
		AND		K_FORMATO_D0M4=@VP_K_FORMATO_D0M4_ORIGINAL
	
		-- ==========================

		DECLARE @VP_K_DOCUMENTO_D0M4_NEW		INT
		
		SELECT	@VP_K_DOCUMENTO_D0M4_NEW =		MAX(K_DOCUMENTO_D0M4)
												FROM	DOCUMENTO_D0M4
												WHERE 	1000<=K_DOCUMENTO_D0M4 AND K_DOCUMENTO_D0M4<2000
		IF @VP_K_DOCUMENTO_D0M4_NEW IS NULL
			SET @VP_K_DOCUMENTO_D0M4_NEW = 1001
		ELSE
			SET @VP_K_DOCUMENTO_D0M4_NEW = @VP_K_DOCUMENTO_D0M4_NEW + 1

		IF @PP_L_DEBUG>1
			PRINT '@VP_K_DOCUMENTO_D0M4_NEW = ' + CONVERT(VARCHAR(100),@VP_K_DOCUMENTO_D0M4_NEW)

		INSERT INTO DOCUMENTO_D0M4
				(	[K_DOCUMENTO_D0M4], 
					[D_DOCUMENTO_D0M4], [C_DOCUMENTO_D0M4], [S_DOCUMENTO_D0M4], [O_DOCUMENTO_D0M4], 
					[K_FORMATO_D0M4], [K_UNIDAD_OPERATIVA], [K_YYYY], [K_MM], [K_PRECIO_COSTO_PERFIL], [L_RECALCULAR], 
					[K_ESTATUS_DOCUMENTO_D0M4]	)
			SELECT	
					@VP_K_DOCUMENTO_D0M4_NEW, 
					[D_DOCUMENTO_D0M4], [C_DOCUMENTO_D0M4], [S_DOCUMENTO_D0M4], [O_DOCUMENTO_D0M4], 
					[K_FORMATO_D0M4], [K_UNIDAD_OPERATIVA], [K_YYYY], @VP_K_MM, [K_PRECIO_COSTO_PERFIL], 1,
					1
			FROM	DOCUMENTO_D0M4
			WHERE 	K_DOCUMENTO_D0M4=@PP_K_DOCUMENTO_D0M4

		-- ==========================
		-- == PASO 2 // PARAMETRO_DOCUMENTO_D0M4	

		INSERT INTO PARAMETRO_DOCUMENTO_D0M4
				(	[K_DOCUMENTO_D0M4],
					[P2016_DTO_DESCUENTO_X_KG], [DESCUENTO_CONTADO], [DESCUENTO_CREDITO],
					[P2023_PCN],
					[P1003_VENTA_KG_CONTADO], [P1004_VENTA_KG_CREDITO], 
					[P1012_CARTERA_CYC_INICIAL], [P1013_CARTERA_CYC_FINAL], [COBRANZA_HOLGURA],
					[PERFIL_VENTA_CONTADO_1_LUNES], [PERFIL_VENTA_CONTADO_2_MARTES], [PERFIL_VENTA_CONTADO_3_MIERCOLES], [PERFIL_VENTA_CONTADO_4_JUEVES], [PERFIL_VENTA_CONTADO_5_VIERNES], [PERFIL_VENTA_CONTADO_6_SABADO], [PERFIL_VENTA_CONTADO_7_DOMINGO],
					[PERFIL_VENTA_CREDITO_1_LUNES], [PERFIL_VENTA_CREDITO_2_MARTES], [PERFIL_VENTA_CREDITO_3_MIERCOLES], [PERFIL_VENTA_CREDITO_4_JUEVES], [PERFIL_VENTA_CREDITO_5_VIERNES], [PERFIL_VENTA_CREDITO_6_SABADO], [PERFIL_VENTA_CREDITO_7_DOMINGO],
					[PERFIL_COBRANZA_1_LUNES], [PERFIL_COBRANZA_2_MARTES], [PERFIL_COBRANZA_3_MIERCOLES], [PERFIL_COBRANZA_4_JUEVES], [PERFIL_COBRANZA_5_VIERNES], [PERFIL_COBRANZA_6_SABADO], [PERFIL_COBRANZA_7_DOMINGO]		)
			SELECT	
					@VP_K_DOCUMENTO_D0M4_NEW, 
					[P2016_DTO_DESCUENTO_X_KG], [DESCUENTO_CONTADO], [DESCUENTO_CREDITO],
					[P2023_PCN],
					[P1003_VENTA_KG_CONTADO], [P1004_VENTA_KG_CREDITO], 
					[P1012_CARTERA_CYC_INICIAL], [P1013_CARTERA_CYC_FINAL], [COBRANZA_HOLGURA],
					[PERFIL_VENTA_CONTADO_1_LUNES], [PERFIL_VENTA_CONTADO_2_MARTES], [PERFIL_VENTA_CONTADO_3_MIERCOLES], [PERFIL_VENTA_CONTADO_4_JUEVES], [PERFIL_VENTA_CONTADO_5_VIERNES], [PERFIL_VENTA_CONTADO_6_SABADO], [PERFIL_VENTA_CONTADO_7_DOMINGO],
					[PERFIL_VENTA_CREDITO_1_LUNES], [PERFIL_VENTA_CREDITO_2_MARTES], [PERFIL_VENTA_CREDITO_3_MIERCOLES], [PERFIL_VENTA_CREDITO_4_JUEVES], [PERFIL_VENTA_CREDITO_5_VIERNES], [PERFIL_VENTA_CREDITO_6_SABADO], [PERFIL_VENTA_CREDITO_7_DOMINGO],
					[PERFIL_COBRANZA_1_LUNES], [PERFIL_COBRANZA_2_MARTES], [PERFIL_COBRANZA_3_MIERCOLES], [PERFIL_COBRANZA_4_JUEVES], [PERFIL_COBRANZA_5_VIERNES], [PERFIL_COBRANZA_6_SABADO], [PERFIL_COBRANZA_7_DOMINGO]		
			FROM	PARAMETRO_DOCUMENTO_D0M4
			WHERE 	K_DOCUMENTO_D0M4=@PP_K_DOCUMENTO_D0M4

			-- ===============================
			UPDATE	PARAMETRO_DOCUMENTO_D0M4
			SET		[P1003_VENTA_KG_CONTADO] = ( [P1003_VENTA_KG_CONTADO] * (1+@PP_ESTACIONALIDAD) ), 
					[P1004_VENTA_KG_CREDITO] = ( [P1004_VENTA_KG_CREDITO] * (1+@PP_ESTACIONALIDAD) )								
			WHERE 	K_DOCUMENTO_D0M4=@VP_K_DOCUMENTO_D0M4_NEW

			-- ===============================
			UPDATE	PARAMETRO_DOCUMENTO_D0M4
			SET		[P1003_VENTA_KG_CONTADO] = ( [P1003_VENTA_KG_CONTADO] * (1+@PP_CRECIMIENTO) ), 
					[P1004_VENTA_KG_CREDITO] = ( [P1004_VENTA_KG_CREDITO] * (1+@PP_CRECIMIENTO) )								
			WHERE 	K_DOCUMENTO_D0M4=@VP_K_DOCUMENTO_D0M4_NEW

		-- ==========================
		-- == PASO 3 // GENERAR REGISTROS BASE	
		EXECUTE [dbo].[PG_IN_DATA_N1_X_DI_D0M4_X_K_DOCUMENTO_D0M4] 	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION, 
																	@VP_K_DOCUMENTO_D0M4_NEW
		-- ==========================
		-- == PASO 4 // PROCESAR	
		EXECUTE [dbo].[PG_OP_DOCUMENTO_DOM4_RECALCULAR]			 	@PP_L_DEBUG, @PP_K_SISTEMA_EXE, @PP_K_USUARIO_ACCION, 
																	@VP_K_DOCUMENTO_D0M4_NEW

	

		END

	-- //////////////////////////////////////////////////////////////
GO



-- ////////////////////////////////////////////////////////////////////////////////////
-- ************************************************************************************
-- ////////////////////////////////////////////////////////////////////////////////////
-- ************************************************************************************
-- ////////////////////////////////////////////////////////////////////////////////////
